### ISSUE TITLE
Josué 

### ISSUE THREAD

**Issue by JOSUEzamu** [rafaelvcaetano/melonDS-android#1008]
* **Device model:** Redmi Note 9S
* **Android version:** Android API 29
* **melonDS version:** Beta 1.7.0 (d4899ed) GH

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$c: Failed to load ROM: NDS_FAILED
	at i9.m$d$b.c(Unknown Source:129)
	at i9.m$d$b.a(Unknown Source:0)
	at i9.p.a(Unknown Source:8)
	at n6.a.t(Unknown Source:10)
	at y5.u.a(Unknown Source:14)
	at n6.e$a.c(Unknown Source:27)
	at n6.o$b.c(Unknown Source:26)
	at n6.o$c.c(Unknown Source:4)
	at k6.l$a.c(Unknown Source:6)
	at k6.i$a.run(Unknown Source:21)
	at y5.t$a.run(Unknown Source:9)
	at p6.k.run(Unknown Source:13)
	at p6.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=false, showBootScreen=false, dsBios7Uri=null, dsBios9Uri=null, dsFirmwareUri=null, dsiBios7Uri=null, dsiBios9Uri=null, dsiFirmwareUri=null, dsiNandUri=null, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, rewindEnabled=false, rewindPeriodSeconds=10, rewindWindowSeconds=60, useJit=true, consoleType=DS, soundEnabled=true, audioInterpolation=NONE, audioBitrate=AUTO, volume=256, audioLatency=MEDIUM, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1, randomizeMacAddress=false, internalMacAddress=00:09:BF:27:6C:E0), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.externalstorage.documents/tree/primary%3ADownload, romUri=content://com.android.externalstorage.documents/tree/primary%3ADownload/document/primary%3ADownload%2FSVME01.nds, sramUri=content://com.android.externalstorage.documents/tree/primary%3ADownload/document/primary%3ADownload%2FSVME01.sav)
```

**Comment by rafaelvcaetano** [comment]
It looks like you are using a bad ROM. Try launching it on another emulator and they also fail, it means the ROM is broken. If other emulators work fine, please open another issue.
