### ISSUE TITLE
Wtf

### ISSUE THREAD

**Issue by gui565br** [rafaelvcaetano/melonDS-android#101]
* **Device model:** moto g(6) plus
* **Android version:** Android API 28

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
java.lang.SecurityException: Permission Denial: reading com.android.providers.downloads.DownloadStorageProvider uri content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2Fds/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2Fds%2F0442%20-%20New%20Super%20Mario%20Bros.%20(J)(WRG).nds from pid=6262, uid=11059 requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
	at android.os.Parcel.createException(Parcel.java:1950)
	at android.os.Parcel.readException(Parcel.java:1918)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:698)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1458)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1295)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1015)
	at me.magnum.melonds.q.i.e(Unknown Source:9)
	at me.magnum.melonds.ui.emulator.j$e.a(Unknown Source:17)
	at f.a.b0.e.b.c.m(Unknown Source:10)
	at f.a.h.a(Unknown Source:14)
	at f.a.b0.e.b.k$b.run(Unknown Source:4)
	at f.a.x.b.b$b.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6923)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)

```

**Comment by rafaelvcaetano** [comment]
Could you give me a screenshot of your Settings screen in the "ROMs" section?

**Comment by shabbirmahmud** [comment]
Can you use the latest beta [v1.3.0](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.3.0) and open a new issue? The latest version does not fix the problem but includes additional info that will help to find the cause.

**Comment by rafaelvcaetano** [comment]
I will suggest a clean install and try using the [Beta 1.4.0](https://github.com/rafaelvcaetano/melonDS-android/releases/latest) release. If the problem is not fixed, please open a new issue.
