### ISSUE TITLE
Trying to boot up a DSiware game on melonds for android on chromebook

### ISSUE THREAD

**Issue by DemiGamerX** [rafaelvcaetano/melonDS-android#1047]
* **Device model:** jacuzzi
* **Android version:** Android API 28
* **melonDS version:** Beta 1.7.0 PS

**Problem:**  
So I finally got the correct DSi bios files for the melonds for android, I wanted to make it works so I tried to boot it up, first it just boots up as a white screen and just sits there. Then I tried to boot crystal adventures to see if it works, and I got hit with the error below..no idea what to do..

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$c: Failed to load ROM: NDS_FAILED
	at k6.q.N(Unknown Source:143)
	at k6.q.x(Unknown Source:0)
	at k6.p.a(Unknown Source:8)
	at a4.a.v(Unknown Source:10)
	at m3.t.b(Unknown Source:14)
	at a4.f$a.d(Unknown Source:27)
	at a4.p$b.c(Unknown Source:26)
	at a4.p$c.d(Unknown Source:4)
	at x3.m$a.a(Unknown Source:10)
	at x3.j$a.run(Unknown Source:27)
	at m3.s$a.run(Unknown Source:9)
	at c4.k.run(Unknown Source:13)
	at c4.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=true, showBootScreen=false, dsBios7Uri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FMelonDS%2FBios%2FDS/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FMelonDS%2FBios%2FDS%2Fbios7.bin, dsBios9Uri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FMelonDS%2FBios%2FDS/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FMelonDS%2FBios%2FDS%2Fbios9.bin, dsFirmwareUri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FMelonDS%2FBios%2FDS/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FMelonDS%2FBios%2FDS%2Ffirmware.bin, dsiBios7Uri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FMelonDS%2FBios%2FDSi/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FMelonDS%2FBios%2FDSi%2Fbios7.bin, dsiBios9Uri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FMelonDS%2FBios%2FDSi/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FMelonDS%2FBios%2FDSi%2Fbios9.bin, dsiFirmwareUri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FMelonDS%2FBios%2FDSi/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FMelonDS%2FBios%2FDSi%2Ffirmware.bin, dsiNandUri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FMelonDS%2FBios%2FDSi/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FMelonDS%2FBios%2FDSi%2Fnand.bin, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=1.5, rewindEnabled=false, rewindPeriodSeconds=10, rewindWindowSeconds=60, useJit=true, consoleType=DSi, soundEnabled=true, audioInterpolation=LINEAR, audioBitrate=AUTO, volume=106, audioLatency=MEDIUM, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=DemiGamerX, message=Nice to meet ya!, language=1, favouriteColour=2, birthdayMonth=5, birthdayDay=2, randomizeMacAddress=false, internalMacAddress=null), rendererConfiguration=RendererConfiguration(videoFiltering=NONE, threadedRendering=true)), romSearchDirUri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FDS%20roms, romUri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FDS%20roms/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FDS%20roms%2FZelda%20Four%20Swords%20-%20Anniversary%20Edition%20(USA)%20(En%2CFr%2CEs).nds, sramUri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FDS%20roms/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FDS%20roms%2FZelda%20Four%20Swords%20-%20Anniversary%20Edition%20(USA)%20(En%2CFr%2CEs).sav)
```

**Comment by alexmi256** [comment]
I tried the latest nightly build (you can get this via actions artifacts) for a DSiWare game and had no issues using the DSiWare manager and then booting into the DSi firmware and playing the game.
