### ISSUE TITLE
No mames 

### ISSUE THREAD

**Issue by roberto97426** [rafaelvcaetano/melonDS-android#1049]
* **Device model:** REVVLPLUS C3701A
* **Android version:** Android API 25
* **melonDS version:** Beta 1.7.0 PS

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
java.lang.IllegalArgumentException: Invalid mode. Only reading "r" supported, but got: "r".
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
	at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:621)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1004)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:839)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:793)
	at me.magnum.melonds.common.UriFileHandler.open()
	at me.magnum.melonds.MelonEmulator.loadRomInternal(Native Method)
	at me.magnum.melonds.MelonEmulator.b()
	at k6.q.N()
	at k6.q.x()
	at k6.p.a()
	at a4.a.v()
	at m3.t.b()
	at a4.f$a.d()
	at a4.p$b.c()
	at a4.p$c.d()
	at x3.m$a.d()
	at x3.j$a.run()
	at m3.s$a.run()
	at c4.k.run()
	at c4.k.call()
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run
	at java.lang.Thread.run(Thread.java:761)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=false, showBootScreen=false, dsBios7Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload/document/primary%3ADownload%2Fbios7.bin, dsBios9Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload/document/primary%3ADownload%2Fbios9.bin, dsFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3ADownload/document/primary%3ADownload%2Ffirmware.bin, dsiBios7Uri=null, dsiBios9Uri=null, dsiFirmwareUri=null, dsiNandUri=null, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, rewindEnabled=false, rewindPeriodSeconds=10, rewindWindowSeconds=60, useJit=true, consoleType=DS, soundEnabled=true, audioInterpolation=NONE, audioBitrate=AUTO, volume=256, audioLatency=MEDIUM, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=5, favouriteColour=0, birthdayMonth=1, birthdayDay=1, randomizeMacAddress=false, internalMacAddress=00:09:BF:22:33:C9), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.externalstorage.documents/tree/primary%3ADownload, romUri=content://com.android.externalstorage.documents/tree/primary%3ADownload/document/primary%3ADownload%2FPokemon%20%20Edicion%20Platino.nds, sramUri=content://com.android.externalstorage.documents/tree/primary%3ADownload/document/primary%3ADownload%2FPokemon%20%20Edicion%20Platino.sav)
```

**Comment by roberto97426** [comment]
No funciona
