### ISSUE TITLE
Lag on S22 Ultra

### ISSUE THREAD

**Issue by UnveilingCoyote** [rafaelvcaetano/melonDS-android#1088]
Emulator starts lagging minutes after starting a game

**Comment by Littlemac123** [comment]
Can you document what games you been trying to play, or if you have the DS BIOS, or the dsi mode

**Comment by UnveilingCoyote** [comment]
When will the lag be fixed

**Comment by rafaelvcaetano** [comment]
With this information, there's nothing I can do. And the S22 is more than capable of running the emulator without issue. Make sure JIT is enabled in the "System" section in the settings. You can also try disabling sustained performance mode in the "General" section in the settings.

**Comment by UnveilingCoyote** [comment]
When I play I get bad stuttering throughout

**Comment by Gamemulatorer** [comment]
Hopefully in the future melonds software rendering will improve the performance.
![Screenshot_20230219_081655](https://user-images.githubusercontent.com/37603562/219905344-beba9125-ef11-4401-a812-3011162ce0e8.jpg)

**Comment by Gamemulatorer** [comment]
Here's some adb log
```
Entered adb shell
Success! ※\(^o^)/※
--------- beginning of system
--------- beginning of crash
--------- beginning of main
02-19 11:15:00.410 19260 19260 E AndroidRuntime: FATAL EXCEPTION: main
02-19 11:15:00.410 19260 19260 E AndroidRuntime: Process: me.magnum.melonds, PID: 19260
02-19 11:15:00.410 19260 19260 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 67108880 byte allocation with 25165824 free bytes and 28MB until OOM, target footprint 263838400, growth limit 268435456
02-19 11:15:00.410 19260 19260 E AndroidRuntime: 	at la.c.a(Unknown Source:0)
02-19 11:15:00.410 19260 19260 E AndroidRuntime: 	at na.a.<init>(Unknown Source:18)
02-19 11:15:00.410 19260 19260 E AndroidRuntime: 	at la.j.<init>(Unknown Source:49)
02-19 11:15:00.410 19260 19260 E AndroidRuntime: 	at la.j.<init>(Unknown Source:4)
02-19 11:15:00.410 19260 19260 E AndroidRuntime: 	at la.j.<init>(Unknown Source:1)
02-19 11:15:00.410 19260 19260 E AndroidRuntime: 	at org.apache.commons.compress.archivers.sevenz.j.b(Unknown Source:12)
02-19 11:15:00.410 19260 19260 E AndroidRuntime: 	at org.apache.commons.compress.archivers.sevenz.g.a(Unknown Source:18)
02-19 11:15:00.410 19260 19260 E AndroidRuntime: 	at org.apache.commons.compress.archivers.sevenz.n.i(Unknown Source:89)
02-19 11:15:00.410 19260 19260 E AndroidRuntime: 	at org.apache.commons.compress.archivers.sevenz.n.G0(Unknown Source:40)
02-19 11:15:00.410 19260 19260 E AndroidRuntime: 	at org.apache.commons.compress.archivers.sevenz.n.j(Unknown Source:71)
02-19 11:15:00.410 19260 19260 E AndroidRuntime: 	at org.apache.commons.compress.archivers.sevenz.n.P(Unknown Source:43)
02-19 11:15:00.410 19260 19260 E AndroidRuntime: 	at f8.f.k(Unknown Source:0)
02-19 11:15:00.410 19260 19260 E AndroidRuntime: 	at f8.f.i(Unknown Source:22)
02-19 11:15:00.410 19260 19260 E AndroidRuntime: 	at f8.b.h(Unknown Source:38)
02-19 11:15:00.410 19260 19260 E AndroidRuntime: 	at f8.b.d(Unknown Source:6)
02-19 11:15:00.410 19260 19260 E AndroidRuntime: 	at t8.b0.g(Unknown Source:61)
02-19 11:15:00.410 19260 19260 E AndroidRuntime: 	at t8.b0.h(Unknown Source:11)
02-19 11:15:00.410 19260 19260 E AndroidRuntime: 	at t8.b0.b(Unknown Source:0)
02-19 11:15:00.410 19260 19260 E AndroidRuntime: 	at t8.b0$b.l(Unknown Source:37)
02-19 11:15:00.410 19260 19260 E AndroidRuntime: 	at e7.a.q(Unknown Source:11)
02-19 11:15:00.410 19260 19260 E AndroidRuntime: 	at u7.x0.run(Unknown Source:88)
02-19 11:15:00.410 19260 19260 E AndroidRuntime: 	at kotlinx.coroutines.internal.j.run(Unknown Source:12)
02-19 11:15:00.410 19260 19260 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.k.run(Unknown Source:2)
02-19 11:15:00.410 19260 19260 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.a.E(Unknown Source:0)
02-19 11:15:00.410 19260 19260 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.a$c.d(Unknown Source:14)
02-19 11:15:00.410 19260 19260 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.a$c.n(Unknown Source:28)
02-19 11:15:00.410 19260 19260 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.a$c.run(Unknown Source:0)
02-19 11:15:00.410 19260 19260 E AndroidRuntime: 	Suppressed: u7.v0: [k2{Cancelling}@b580f69, Dispatchers.Main.immediate]
```

**Comment by LuanVSO** [comment]
I'm on s20+ exynos and am also seeing the slow down after a few minutes of play, i have installed a DS and DSi bios, DSi mode is turned off, I seen it happen on castlevania dawn of sorrow and on the DSi firmware.
If I pause and unpause the emulation it returns to normal levels of performance

**Comment by Gamemulatorer** [comment]
This might help in melonds?
![IMG_20230219_103636](https://user-images.githubusercontent.com/37603562/219909120-5b4ff859-ebaf-4076-9bf3-63baf4a2ec48.jpg)

**Comment by UnveilingCoyote** [comment]
Any update on this?

**Comment by Gamemulatorer** [comment]
> Any update on this?

Performance of this emulator will only improve if ever opengl renderer is implemented.

**Comment by UnveilingCoyote** [comment]
When will this issue be fixed

**Comment by rafaelvcaetano** [comment]
I don't have that specific device to be able to reproduce your problem. The closest thing I have is a Galaxy S10 and it doesn't suffer from the same problem. As such, you will have to be patient because addressing these things is not easy.

**Comment by UnveilingCoyote** [comment]
Thank you Rafael for responding, I will wait.

**Comment by LuanVSO** [comment]
You can test apps on Samsung devices here for free:
https://developer.samsung.com/remote-test-lab

**Comment by Gamemulatorer** [comment]
@rafaelvcaetano JIT doesn't work on my vivo y11 snapdragon 439 performance.
I tried it disable/enable the fps doesn't change but the threaded rendering really helps.

Does JIT only optimize in higher specs devices?

**Comment by Gamemulatorer** [comment]
>> Performance is solid on 64 bit devices with thread rendering and JIT enabled, and should run at full speed on flagship devices. Performance on older devices, specially 32 bit devices, is very poor due to the lack of JIT support.

Maybe melonDS detected my phone as 32bit? What do you think about this?

But in DevCheck app my phone is 64bit supported.
![Screenshot_20230315_203553](https://user-images.githubusercontent.com/37603562/225310816-3e23e2be-293a-4782-9fd9-0c7ba70ef744.jpg)

**Comment by LuanVSO** [comment]
> @rafaelvcaetano JIT doesn't work on my vivo y11 snapdragon 439 performance.
> I tried it disable/enable the fps doesn't change but the threaded rendering really helps.
> 
> Does JIT only optimize in higher specs devices? 

Please open another issue

**Comment by UnveilingCoyote** [comment]
It still slows down after a few minutes, please fix this

**Comment by UnveilingCoyote** [comment]
Update on this?

**Comment by LuanVSO** [comment]
Could you stop pinging this thread? Everyone who is subscribed receives notifications when you do that.
Besides that, annoying people will not get them any more inclined to fix this, especially because he has no obligation to do it

**Comment by UnveilingCoyote** [comment]
Jeez, I didn't expect this kind of answer, I am sorry

**Comment by FATCatAndroid12** [comment]
@UnveilingCoyote can you try the latest nightly build https://github.com/rafaelvcaetano/melonDS-android/releases
