### ISSUE TITLE
Transferencia 

### ISSUE THREAD

**Issue by Mariano027** [rafaelvcaetano/melonDS-android#1097]
* **Device model:** POT-LX1
* **Android version:** Android API 29
* **melonDS version:** Beta 1.7.0 PS

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
java.io.FileNotFoundException: Unsupported mode: rw
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:149)
	at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:631)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1532)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1349)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1297)
	at me.magnum.melonds.common.UriFileHandler.open(Unknown Source:89)
	at me.magnum.melonds.MelonEmulator.loadRomInternal(Native Method)
	at me.magnum.melonds.MelonEmulator.b(Unknown Source:49)
	at k6.q.N(Unknown Source:110)
	at k6.q.x(Unknown Source:0)
	at k6.p.a(Unknown Source:8)
	at a4.a.v(Unknown Source:10)
	at m3.t.b(Unknown Source:14)
	at a4.f$a.d(Unknown Source:27)
	at a4.p$b.c(Unknown Source:26)
	at a4.p$c.d(Unknown Source:4)
	at x3.m$a.d(Unknown Source:6)
	at x3.j$a.run(Unknown Source:21)
	at m3.s$a.run(Unknown Source:9)
	at c4.k.run(Unknown Source:13)
	at c4.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=true, showBootScreen=false, dsBios7Uri=content://com.android.providers.downloads.documents/tree/msd%3A133803/document/msf%3A133829, dsBios9Uri=content://com.android.providers.downloads.documents/tree/msd%3A133803/document/msf%3A133830, dsFirmwareUri=content://com.android.providers.downloads.documents/tree/msd%3A133803/document/msf%3A133806, dsiBios7Uri=null, dsiBios9Uri=null, dsiFirmwareUri=null, dsiNandUri=null, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=8.0, rewindEnabled=false, rewindPeriodSeconds=10, rewindWindowSeconds=60, useJit=true, consoleType=DS, soundEnabled=true, audioInterpolation=NONE, audioBitrate=AUTO, volume=256, audioLatency=MEDIUM, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1, randomizeMacAddress=false, internalMacAddress=null), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.providers.downloads.documents/tree/downloads, romUri=content://com.android.providers.downloads.documents/tree/downloads/document/msf%3A133801, sramUri=content://com.android.providers.downloads.documents/tree/downloads/document/458)
```

**Comment by rafaelvcaetano** [comment]
Please try the [latest version](https://github.com/rafaelvcaetano/melonDS-android/releases/latest) where this problem should be fixed. Or download it from the [Play Store](https://play.google.com/store/apps/details?id=me.magnum.melonds) to always keep the app up-to-date. If you still encounter errors after updating, please open a new issue.
