### ISSUE TITLE
No me corre el pokemon blanco 2

### ISSUE THREAD

**Issue by Ceromasterace27** [rafaelvcaetano/melonDS-android#1103]
* **Device model:** moto e5 play
* **Android version:** Android API 27
* **melonDS version:** Beta 1.8.0 PS

**Problem:**  
Insert a small description of the problem.
No me inicia el pokemón blanco 2 
**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$c: Failed to load ROM: NDS_FAILED
	at i9.m$d$b.c(Unknown Source:129)
	at i9.m$d$b.a(Unknown Source:0)
	at i9.p.a(Unknown Source:8)
	at p6.a.t(Unknown Source:10)
	at b6.t.a(Unknown Source:14)
	at p6.e$a.c(Unknown Source:27)
	at p6.o$b.c(Unknown Source:26)
	at p6.o$c.c(Unknown Source:4)
	at m6.l$a.c(Unknown Source:6)
	at m6.i$a.run(Unknown Source:21)
	at b6.s$a.run(Unknown Source:9)
	at r6.k.run(Unknown Source:13)
	at r6.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=true, showBootScreen=false, dsBios7Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload/document/primary%3ADownload%2Fbios7.bin, dsBios9Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload/document/primary%3ADownload%2Fbios9.bin, dsFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3ADownload/document/primary%3ADownload%2Ffirmware.bin, dsiBios7Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FNintendo%20DSI%20Bios%20and%20Firmware/document/primary%3ADownload%2FNintendo%20DSI%20Bios%20and%20Firmware%2Fbios7.bin, dsiBios9Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FNintendo%20DSI%20Bios%20and%20Firmware/document/primary%3ADownload%2FNintendo%20DSI%20Bios%20and%20Firmware%2Fbios9.bin, dsiFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FNintendo%20DSI%20Bios%20and%20Firmware/document/primary%3ADownload%2FNintendo%20DSI%20Bios%20and%20Firmware%2Ffirmware.bin, dsiNandUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FNintendo%20DSI%20Bios%20and%20Firmware/document/primary%3ADownload%2FNintendo%20DSI%20Bios%20and%20Firmware%2Fnand.bin, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=2.0, rewindEnabled=false, rewindPeriodSeconds=10, rewindWindowSeconds=60, useJit=false, consoleType=DS, soundEnabled=true, audioInterpolation=NONE, audioBitrate=AUTO, volume=256, audioLatency=LOW, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1, randomizeMacAddress=false, internalMacAddress=00:09:BF:4F:80:93), rendererConfiguration=RendererConfiguration(videoFiltering=XBR2, threadedRendering=false)), romSearchDirUri=content://com.android.externalstorage.documents/tree/primary%3Ads%2FROMS, romUri=content://com.android.externalstorage.documents/tree/primary%3Ads%2FROMS/document/primary%3Ads%2FROMS%2FPokemon%20-%20Edicion%20Blanca%202%20(Spain)%20(NDSi%20Enhanced)%20%5Bb%5D.zip, sramUri=content://com.android.externalstorage.documents/tree/primary%3Ads%2FROMS/document/primary%3Ads%2FROMS%2FPokemon%20-%20Edicion%20Blanca%202%20(Spain)%20(NDSi%20Enhanced)%20%5Bb%5D.sav)
```

**Comment by rafaelvcaetano** [comment]
It looks like you are using a bad ROM. Try launching it on another emulator and they also fail, it means the ROM is broken. If other emulators work fine, please open another issue.
