### ISSUE TITLE
Problemas con arranque 

### ISSUE THREAD

**Issue by Israel0323** [rafaelvcaetano/melonDS-android#1104]
* **Device model:** V2050
* **Android version:** Android API 31
* **melonDS version:** Beta 1.8.0 PS

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$c: Failed to load ROM: NDS_FAILED
	at i9.m$d$b.c(Unknown Source:129)
	at i9.m$d$b.a(Unknown Source:0)
	at i9.p.a(Unknown Source:8)
	at p6.a.t(Unknown Source:10)
	at b6.t.a(Unknown Source:14)
	at p6.e$a.c(Unknown Source:27)
	at p6.o$b.c(Unknown Source:26)
	at p6.o$c.c(Unknown Source:4)
	at m6.l$a.a(Unknown Source:10)
	at m6.i$a.run(Unknown Source:27)
	at b6.s$a.run(Unknown Source:9)
	at r6.k.run(Unknown Source:13)
	at r6.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=false, showBootScreen=false, dsBios7Uri=null, dsBios9Uri=null, dsFirmwareUri=null, dsiBios7Uri=null, dsiBios9Uri=null, dsiFirmwareUri=null, dsiNandUri=null, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, rewindEnabled=false, rewindPeriodSeconds=10, rewindWindowSeconds=60, useJit=true, consoleType=DS, soundEnabled=true, audioInterpolation=NONE, audioBitrate=AUTO, volume=256, audioLatency=MEDIUM, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=5, favouriteColour=0, birthdayMonth=1, birthdayDay=1, randomizeMacAddress=true, internalMacAddress=null), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.externalstorage.documents/tree/primary%3ACMA_Zip%2FDecompressed%2FPokemon%20pack%201_20230212, romUri=content://com.android.externalstorage.documents/tree/primary%3ACMA_Zip%2FDecompressed%2FPokemon%20pack%201_20230212/document/primary%3ACMA_Zip%2FDecompressed%2FPokemon%20pack%201_20230212%2F4ta%20Generacion%2FPokemon%20Edicion%20Perla.nds, sramUri=content://com.android.externalstorage.documents/tree/primary%3ACMA_Zip%2FDecompressed%2FPokemon%20pack%201_20230212/document/primary%3ACMA_Zip%2FDecompressed%2FPokemon%20pack%201_20230212%2F4ta%20Generacion%2FPokemon%20Edicion%20Perla.sav)
```

**Comment by rafaelvcaetano** [comment]
It looks like you are using a bad ROM. Try launching it on another emulator and they also fail, it means the ROM is broken. If other emulators work fine, please open another issue.
