### ISSUE TITLE
DS BIOS won't boot when I put DSi BIOS Files into different directory

### ISSUE THREAD

**Issue by sehunoh2005** [rafaelvcaetano/melonDS-android#1111]
* **Device model:** IN2019
* **Android version:** Android API 30
* **melonDS version:** Beta 1.8.0 PS

**Problem:**  
I tried to load DS BIOS Files but it won't boot. Please fix this problem.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$b: Failed to load firmware: FIRMWARE_NOT_BOOTABLE
	at f9.b$b.c(Unknown Source:57)
	at f9.b$b.a(Unknown Source:0)
	at f9.c.a(Unknown Source:4)
	at l6.a.j(Unknown Source:10)
	at b6.a.a(Unknown Source:14)
	at p6.f$a.c(Unknown Source:20)
	at p6.h.t(Unknown Source:9)
	at b6.t.a(Unknown Source:14)
	at p6.f.j(Unknown Source:12)
	at b6.a.a(Unknown Source:14)
	at l6.e$a.run(Unknown Source:2)
	at b6.s$a.run(Unknown Source:9)
	at r6.k.run(Unknown Source:13)
	at r6.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```

**Configuration:**  
```
FirmwareCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=true, showBootScreen=true, dsBios7Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FDS%20BIOS%2FDS/document/primary%3ADownload%2FDS%20BIOS%2FDS%2Fbios7.bin, dsBios9Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FDS%20BIOS%2FDS/document/primary%3ADownload%2FDS%20BIOS%2FDS%2Fbios9.bin, dsFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FDS%20BIOS%2FDS/document/primary%3ADownload%2FDS%20BIOS%2FDS%2Ffirmware.bin, dsiBios7Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FDSI%20BIOS%2FAmerican/document/primary%3ADownload%2FDSI%20BIOS%2FAmerican%2Fbios7.bin, dsiBios9Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FDSI%20BIOS%2FAmerican/document/primary%3ADownload%2FDSI%20BIOS%2FAmerican%2Fbios9.bin, dsiFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FDSI%20BIOS%2FAmerican/document/primary%3ADownload%2FDSI%20BIOS%2FAmerican%2Ffirmware.bin, dsiNandUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FDSI%20BIOS%2FAmerican/document/primary%3ADownload%2FDSI%20BIOS%2FAmerican%2Fnand.bin, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, rewindEnabled=true, rewindPeriodSeconds=10, rewindWindowSeconds=60, useJit=false, consoleType=DS, soundEnabled=true, audioInterpolation=NONE, audioBitrate=AUTO, volume=256, audioLatency=LOW, micSource=DEVICE, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1, randomizeMacAddress=false, internalMacAddress=null), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=false)), dsiBiosDirUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FDS%20BIOS%2FDS, dsBiosDirUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FDSI%20BIOS%2FAmerican)
```

**Comment by Gamemulatorer** [comment]
Create bios folder inside melonds
DL ds/dsi bios and firmware here
https://emulation.gametechwiki.com/index.php/Emulator_files

**Comment by rafaelvcaetano** [comment]
This error should be fixed in the latest nightly build.
