### ISSUE TITLE
 Melonds

### ISSUE THREAD

**Issue by Taz12345686** [rafaelvcaetano/melonDS-android#1135]
* **Device model:** SM-A315G
* **Android version:** Android API 31
* **melonDS version:** Beta 1.8.0 PS

**Problem:**  
My roms not downloading

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$b: Failed to load firmware: FIRMWARE_NOT_BOOTABLE
	at f9.b$b.c(Unknown Source:57)
	at f9.b$b.a(Unknown Source:0)
	at f9.c.a(Unknown Source:4)
	at l6.a.j(Unknown Source:10)
	at b6.a.a(Unknown Source:14)
	at p6.f$a.c(Unknown Source:20)
	at p6.h.t(Unknown Source:9)
	at b6.t.a(Unknown Source:14)
	at p6.f.j(Unknown Source:12)
	at b6.a.a(Unknown Source:14)
	at l6.e$a.run(Unknown Source:2)
	at b6.s$a.run(Unknown Source:9)
	at r6.k.run(Unknown Source:13)
	at r6.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
```

**Configuration:**  
```
FirmwareCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=true, showBootScreen=true, dsBios7Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FCarpeta%20Juegos/document/primary%3ADownload%2FCarpeta%20Juegos%2Fbios7.bin, dsBios9Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FCarpeta%20Juegos/document/primary%3ADownload%2FCarpeta%20Juegos%2Fbios9.bin, dsFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FCarpeta%20Juegos/document/primary%3ADownload%2FCarpeta%20Juegos%2Ffirmware.bin, dsiBios7Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FCarpeta%20melon%2Frebuilt.melonds%20Bios%20(1)%2FBios%2FDSi%20USA/document/primary%3ADownload%2FCarpeta%20melon%2Frebuilt.melonds%20Bios%20(1)%2FBios%2FDSi%20USA%2Fbios7.bin, dsiBios9Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FCarpeta%20melon%2Frebuilt.melonds%20Bios%20(1)%2FBios%2FDSi%20USA/document/primary%3ADownload%2FCarpeta%20melon%2Frebuilt.melonds%20Bios%20(1)%2FBios%2FDSi%20USA%2Fbios9.bin, dsiFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FCarpeta%20melon%2Frebuilt.melonds%20Bios%20(1)%2FBios%2FDSi%20USA/document/primary%3ADownload%2FCarpeta%20melon%2Frebuilt.melonds%20Bios%20(1)%2FBios%2FDSi%20USA%2Ffirmware.bin, dsiNandUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FCarpeta%20melon%2Frebuilt.melonds%20Bios%20(1)%2FBios%2FDSi%20USA/document/primary%3ADownload%2FCarpeta%20melon%2Frebuilt.melonds%20Bios%20(1)%2FBios%2FDSi%20USA%2Fnand.bin, internalDirectory=/data/user/150/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, rewindEnabled=false, rewindPeriodSeconds=10, rewindWindowSeconds=60, useJit=true, consoleType=DS, soundEnabled=true, audioInterpolation=NONE, audioBitrate=AUTO, volume=256, audioLatency=MEDIUM, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Taz, message=Hello!, language=5, favouriteColour=0, birthdayMonth=12, birthdayDay=9, randomizeMacAddress=false, internalMacAddress=00:09:BF:4A:2E:43), rendererConfiguration=RendererConfiguration(videoFiltering=XBR2, threadedRendering=true)), dsiBiosDirUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FCarpeta%20Juegos, dsBiosDirUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FCarpeta%20melon%2Frebuilt.melonds%20Bios%20(1)%2FBios%2FDSi%20USA)
```

**Comment by rafaelvcaetano** [comment]
It looks like you are trying to boot an invalid firmware. Please try using another BIOS set.
