### ISSUE TITLE
When i load firmware then show a error

### ISSUE THREAD

**Issue by SohamRoy20Gaming** [rafaelvcaetano/melonDS-android#1147]
* **Device model:** Moto E (4) Plus
* **Android version:** Android API 25
* **melonDS version:** Beta 1.8.0 PS

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$b: Failed to load firmware: FIRMWARE_NOT_BOOTABLE
	at f9.b$b.c(SourceFile)
	at f9.b$b.a(SourceFile)
	at f9.c.a(SourceFile)
	at l6.a.j(SourceFile)
	at b6.a.a(SourceFile)
	at p6.f$a.c(SourceFile)
	at p6.h.t(SourceFile)
	at b6.t.a(SourceFile)
	at p6.f.j(SourceFile)
	at b6.a.a(SourceFile)
	at l6.e$a.run(SourceFile)
	at b6.s$a.run(SourceFile)
	at r6.k.run(SourceFile)
	at r6.k.call(SourceFile)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

```

**Configuration:**  
```
FirmwareCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=true, showBootScreen=false, dsBios7Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FRoms%2FNintendo%20DS%20(NDS)%2FBIOS%2FDS/document/primary%3ADownload%2FRoms%2FNintendo%20DS%20(NDS)%2FBIOS%2FDS%2Fbios7.bin, dsBios9Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FRoms%2FNintendo%20DS%20(NDS)%2FBIOS%2FDS/document/primary%3ADownload%2FRoms%2FNintendo%20DS%20(NDS)%2FBIOS%2FDS%2Fbios9.bin, dsFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FRoms%2FNintendo%20DS%20(NDS)%2FBIOS%2FDS/document/primary%3ADownload%2FRoms%2FNintendo%20DS%20(NDS)%2FBIOS%2FDS%2Ffirmware.bin, dsiBios7Uri=null, dsiBios9Uri=null, dsiFirmwareUri=null, dsiNandUri=null, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, rewindEnabled=false, rewindPeriodSeconds=10, rewindWindowSeconds=60, useJit=false, consoleType=DS, soundEnabled=true, audioInterpolation=NONE, audioBitrate=AUTO, volume=256, audioLatency=MEDIUM, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1, randomizeMacAddress=false, internalMacAddress=00:09:BF:BC:54:A9), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), dsiBiosDirUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FRoms%2FNintendo%20DS%20(NDS)%2FBIOS%2FDS, dsBiosDirUri=null)
```

**Comment by rafaelvcaetano** [comment]
This error should be fixed in the latest nightly build.
