### ISSUE TITLE
Pokemon black 2

### ISSUE THREAD

**Issue by Du8727** [rafaelvcaetano/melonDS-android#1149]
* **Device model:** SM-A105M
* **Android version:** Android API 30
* **melonDS version:** Beta 1.8.0 PS

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
e9.c: Could not create temporary SRAM file at content://com.android.externalstorage.documents/tree/primary%3Amelon/document/primary%3Amelon
	at me.magnum.melonds.ui.emulator.EmulatorViewModel.R(Unknown Source:117)
	at i9.m$d$b.c(Unknown Source:67)
	at i9.m$d$b.a(Unknown Source:0)
	at i9.p.a(Unknown Source:8)
	at p6.a.t(Unknown Source:10)
	at b6.t.a(Unknown Source:14)
	at p6.e$a.c(Unknown Source:27)
	at p6.o$b.c(Unknown Source:26)
	at p6.o$c.c(Unknown Source:4)
	at m6.l$a.c(Unknown Source:6)
	at m6.i$a.run(Unknown Source:21)
	at b6.s$a.run(Unknown Source:9)
	at r6.k.run(Unknown Source:13)
	at r6.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=false, showBootScreen=false, dsBios7Uri=content://com.android.externalstorage.documents/tree/primary%3Amelonds%2Fmelonbios%2FBIOS%20DS%20%2B%20firmware%20DS/document/primary%3Amelonds%2Fmelonbios%2FBIOS%20DS%20%2B%20firmware%20DS%2Fbios7.bin, dsBios9Uri=content://com.android.externalstorage.documents/tree/primary%3Amelonds%2Fmelonbios%2FBIOS%20DS%20%2B%20firmware%20DS/document/primary%3Amelonds%2Fmelonbios%2FBIOS%20DS%20%2B%20firmware%20DS%2Fbios9.bin, dsFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3Amelonds%2Fmelonbios%2FBIOS%20DS%20%2B%20firmware%20DS/document/primary%3Amelonds%2Fmelonbios%2FBIOS%20DS%20%2B%20firmware%20DS%2Ffirmware.bin, dsiBios7Uri=content://com.android.externalstorage.documents/tree/primary%3Amelonds%2Fmelonbios%2FNova%20pasta%20(8)%2FBIOS%20DS%20%2B%20firmware%20DS/document/primary%3Amelonds%2Fmelonbios%2FNova%20pasta%20(8)%2FBIOS%20DS%20%2B%20firmware%20DS%2Fbios7.bin, dsiBios9Uri=content://com.android.externalstorage.documents/tree/primary%3Amelonds%2Fmelonbios%2FNova%20pasta%20(8)%2FBIOS%20DS%20%2B%20firmware%20DS/document/primary%3Amelonds%2Fmelonbios%2FNova%20pasta%20(8)%2FBIOS%20DS%20%2B%20firmware%20DS%2Fbios9.bin, dsiFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3Amelonds%2Fmelonbios%2FNova%20pasta%20(8)%2FBIOS%20DS%20%2B%20firmware%20DS/document/primary%3Amelonds%2Fmelonbios%2FNova%20pasta%20(8)%2FBIOS%20DS%20%2B%20firmware%20DS%2Ffirmware.bin, dsiNandUri=null, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, rewindEnabled=false, rewindPeriodSeconds=10, rewindWindowSeconds=60, useJit=false, consoleType=DS, soundEnabled=true, audioInterpolation=NONE, audioBitrate=AUTO, volume=256, audioLatency=MEDIUM, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=du8727, message=eu sou BR, language=1, favouriteColour=2, birthdayMonth=12, birthdayDay=6, randomizeMacAddress=false, internalMacAddress=00:09:BF:2B:07:FD), rendererConfiguration=RendererConfiguration(videoFiltering=QUILEZ, threadedRendering=true)), romSearchDirUri=content://com.android.externalstorage.documents/tree/primary%3APokemon, romUri=content://com.android.externalstorage.documents/tree/primary%3APokemon/document/primary%3APokemon%2FPokemon%20Black%202%20(BR).nds, sramUri=null)
```

**Comment by rafaelvcaetano** [comment]
Please try the [latest version](https://github.com/rafaelvcaetano/melonDS-android/releases/latest) where this problem should be fixed. Or download it from the [Play Store](https://play.google.com/store/apps/details?id=me.magnum.melonds) to always keep the app up-to-date. If you still encounter errors after updating, please open a new issue.
