### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by LtGray7** [rafaelvcaetano/melonDS-android#1150]
* **Device model:** SM-A515U
* **Android version:** Android API 31
* **melonDS version:** Beta 1.8.0 PS

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$b: Failed to load firmware: FIRMWARE_NOT_BOOTABLE
	at f9.b$b.c(Unknown Source:57)
	at f9.b$b.a(Unknown Source:0)
	at f9.c.a(Unknown Source:4)
	at l6.a.j(Unknown Source:10)
	at b6.a.a(Unknown Source:14)
	at p6.f$a.c(Unknown Source:20)
	at p6.h.t(Unknown Source:9)
	at b6.t.a(Unknown Source:14)
	at p6.f.j(Unknown Source:12)
	at b6.a.a(Unknown Source:14)
	at l6.e$a.run(Unknown Source:2)
	at b6.s$a.run(Unknown Source:9)
	at r6.k.run(Unknown Source:13)
	at r6.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

```

**Configuration:**  
```
FirmwareCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=true, showBootScreen=true, dsBios7Uri=content://com.android.externalstorage.documents/tree/primary%3ARoms%2FDS%2FNDS%20Bios%20%26%20Firmware/document/primary%3ARoms%2FDS%2FNDS%20Bios%20%26%20Firmware%2Fbios7.bin, dsBios9Uri=content://com.android.externalstorage.documents/tree/primary%3ARoms%2FDS%2FNDS%20Bios%20%26%20Firmware/document/primary%3ARoms%2FDS%2FNDS%20Bios%20%26%20Firmware%2Fbios9.bin, dsFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3ARoms%2FDS%2FNDS%20Bios%20%26%20Firmware/document/primary%3ARoms%2FDS%2FNDS%20Bios%20%26%20Firmware%2Ffirmware.bin, dsiBios7Uri=null, dsiBios9Uri=null, dsiFirmwareUri=null, dsiNandUri=null, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, rewindEnabled=false, rewindPeriodSeconds=10, rewindWindowSeconds=60, useJit=true, consoleType=DS, soundEnabled=true, audioInterpolation=NONE, audioBitrate=AUTO, volume=256, audioLatency=MEDIUM, micSource=DEVICE, firmwareConfiguration=FirmwareConfiguration(nickname=LtGray, message=Hello!, language=1, favouriteColour=13, birthdayMonth=8, birthdayDay=30, randomizeMacAddress=false, internalMacAddress=null), rendererConfiguration=RendererConfiguration(videoFiltering=LCD, threadedRendering=true)), dsiBiosDirUri=content://com.android.externalstorage.documents/tree/primary%3ARoms%2FDS%2FNDS%20Bios%20%26%20Firmware, dsBiosDirUri=content://com.android.externalstorage.documents/tree/primary%3ARoms%2FDS%2FDSi%20firmware%20files)
```

**Comment by rafaelvcaetano** [comment]
Looks like you are trying to boot a BIOS and firmware that are not bootable. You will need to user a proper BIOS and firmware dump to be able to boot it.
