### ISSUE TITLE
NTR FIRMWARE_NOT_BOOTABLE

### ISSUE THREAD

**Issue by RaichuBender** [rafaelvcaetano/melonDS-android#1162]
* **Device model:** SM-N981B
* **Android version:** Android API 31
* **melonDS version:** Beta 1.8.0 (cc8c3a9) GH

**Problem:**  
Insert a small description of the problem.
[Actually, I think I see what I did wrong... Instead of booting my own firmware files, I might have mixed up the No$GBA ones, which aren't bootable. Might close this issue after some invest.]

EDIT: Nope, quadruple-checked. Works on hardware. It's not the binary files themselves.
Strange, because TWL mode works flawlessly, almost native level in most instances...

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$b: Failed to load firmware: FIRMWARE_NOT_BOOTABLE
	at i9.b$b.c(Unknown Source:57)
	at i9.b$b.a(Unknown Source:0)
	at i9.c.a(Unknown Source:4)
	at l6.a.k(Unknown Source:10)
	at b6.b.a(Unknown Source:14)
	at q6.f$a.c(Unknown Source:20)
	at q6.h.t(Unknown Source:9)
	at b6.u.a(Unknown Source:14)
	at q6.f.k(Unknown Source:12)
	at b6.b.a(Unknown Source:14)
	at l6.e$a.run(Unknown Source:2)
	at b6.t$a.run(Unknown Source:9)
	at s6.k.run(Unknown Source:13)
	at s6.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

```

**Configuration:**  
```
FirmwareCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=true, showBootScreen=true, dsBios7Uri=content://com.android.externalstorage.documents/tree/primary%3AROMs%2FBIOS_NTR_No%24/document/primary%3AROMs%2FBIOS_NTR_No%24%2Fbios7.bin, dsBios9Uri=content://com.android.externalstorage.documents/tree/primary%3AROMs%2FBIOS_NTR_No%24/document/primary%3AROMs%2FBIOS_NTR_No%24%2Fbios9.bin, dsFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3AROMs%2FBIOS_NTR_No%24/document/primary%3AROMs%2FBIOS_NTR_No%24%2Ffirmware.bin, dsiBios7Uri=content://com.android.externalstorage.documents/tree/primary%3AROMs%2FBIOS_TWL/document/primary%3AROMs%2FBIOS_TWL%2Fbios7.bin, dsiBios9Uri=content://com.android.externalstorage.documents/tree/primary%3AROMs%2FBIOS_TWL/document/primary%3AROMs%2FBIOS_TWL%2Fbios9.bin, dsiFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3AROMs%2FBIOS_TWL/document/primary%3AROMs%2FBIOS_TWL%2Ffirmware.bin, dsiNandUri=content://com.android.externalstorage.documents/tree/primary%3AROMs%2FBIOS_TWL/document/primary%3AROMs%2FBIOS_TWL%2Fnand.bin, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, rewindEnabled=false, rewindPeriodSeconds=10, rewindWindowSeconds=60, useJit=true, consoleType=DS, soundEnabled=true, audioInterpolation=NONE, audioBitrate=AUTO, volume=256, audioLatency=MEDIUM, micSource=DEVICE, firmwareConfiguration=FirmwareConfiguration(nickname=\0, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1, randomizeMacAddress=true, internalMacAddress=null), rendererConfiguration=RendererConfiguration(videoFiltering=NONE, threadedRendering=true)), dsiBiosDirUri=content://com.android.externalstorage.documents/tree/primary%3AROMs%2FBIOS_NTR_No%24, dsBiosDirUri=content://com.android.externalstorage.documents/tree/primary%3AROMs%2FBIOS_TWL)
```

**Comment by rafaelvcaetano** [comment]
Please try the [latest version](https://github.com/rafaelvcaetano/melonDS-android/releases/latest) where this problem should be fixed. Or download it from the [Play Store](https://play.google.com/store/apps/details?id=me.magnum.melonds) to always keep the app up-to-date. If you still encounter errors after updating, please open a new issue.

**Comment by RaichuBender** [comment]
Thanks! Yes! I can confirm it works now as of the latest version (updated via in-app update prompt)
