### ISSUE TITLE
Issue Could not load Rom MELONDS

### ISSUE THREAD

**Issue by SonicTheHedgehogClassic** [rafaelvcaetano/melonDS-android#1173]
0* **Device model:** SM-A226B
* **Android version:** Android API 33
* **melonDS version:** Beta 1.8.0 PS

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
e9.c: Could not create temporary SRAM file at content://com.android.externalstorage.documents/tree/primary%3ADS%2Fsavefile/document/primary%3ADS%2Fsavefile
	at me.magnum.melonds.ui.emulator.EmulatorViewModel.R(Unknown Source:117)
	at i9.m$d$b.c(Unknown Source:67)
	at i9.m$d$b.a(Unknown Source:0)
	at i9.p.a(Unknown Source:8)
	at p6.a.t(Unknown Source:10)
	at b6.t.a(Unknown Source:14)
	at p6.e$a.c(Unknown Source:27)
	at p6.o$b.c(Unknown Source:26)
	at p6.o$c.c(Unknown Source:4)
	at m6.l$a.c(Unknown Source:6)
	at m6.i$a.run(Unknown Source:21)
	at b6.s$a.run(Unknown Source:9)
	at r6.k.run(Unknown Source:13)
	at r6.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=true, showBootScreen=true, dsBios7Uri=content://com.android.externalstorage.documents/tree/primary%3AEMULATOR%20PACK%200.0.1%2FDS%2Fbios/document/primary%3AEMULATOR%20PACK%200.0.1%2FDS%2Fbios%2Fbios7.bin, dsBios9Uri=content://com.android.externalstorage.documents/tree/primary%3AEMULATOR%20PACK%200.0.1%2FDS%2Fbios/document/primary%3AEMULATOR%20PACK%200.0.1%2FDS%2Fbios%2Fbios9.bin, dsFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3AEMULATOR%20PACK%200.0.1%2FDS%2Fbios/document/primary%3AEMULATOR%20PACK%200.0.1%2FDS%2Fbios%2Ffirmware.bin, dsiBios7Uri=content://com.android.externalstorage.documents/tree/primary%3AEMULATOR%20PACK%200.0.1%2FDS%2FDSI/document/primary%3AEMULATOR%20PACK%200.0.1%2FDS%2FDSI%2Fbios7.bin, dsiBios9Uri=content://com.android.externalstorage.documents/tree/primary%3AEMULATOR%20PACK%200.0.1%2FDS%2FDSI/document/primary%3AEMULATOR%20PACK%200.0.1%2FDS%2FDSI%2Fbios9.bin, dsiFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3AEMULATOR%20PACK%200.0.1%2FDS%2FDSI/document/primary%3AEMULATOR%20PACK%200.0.1%2FDS%2FDSI%2Ffirmware.bin, dsiNandUri=content://com.android.externalstorage.documents/tree/primary%3AEMULATOR%20PACK%200.0.1%2FDS%2FDSI/document/primary%3AEMULATOR%20PACK%200.0.1%2FDS%2FDSI%2Fnand.bin, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, rewindEnabled=true, rewindPeriodSeconds=10, rewindWindowSeconds=60, useJit=true, consoleType=DSi, soundEnabled=true, audioInterpolation=LINEAR, audioBitrate=BIT16, volume=256, audioLatency=HIGH, micSource=DEVICE, firmwareConfiguration=FirmwareConfiguration(nickname=SonicGameraki, message=Why are you touching my DSi?!?!, language=1, favouriteColour=11, birthdayMonth=12, birthdayDay=28, randomizeMacAddress=false, internalMacAddress=null), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=false)), romSearchDirUri=content://com.android.externalstorage.documents/tree/primary%3AEMULATOR%20PACK%200.0.1, romUri=content://com.android.externalstorage.documents/tree/primary%3AEMULATOR%20PACK%200.0.1/document/primary%3AEMULATOR%20PACK%200.0.1%2FMario%20%26%20Sonic%20at%20the%20Olympic%20Winter%20Games%20(USA)%20(En%2CFr%2CEs).nds, sramUri=null)
```

**Comment by SonicTheHedgehogClassic** [comment]
Its ok now
