### ISSUE TITLE
Couldn't load rom firmware error

### ISSUE THREAD

**Issue by aqbert** [rafaelvcaetano/melonDS-android#1174]
* **Device model:** HD1925
* **Android version:** Android API 31
* **melonDS version:** Beta 1.8.0 PS

**Problem:**  
Tried booting my DS firmware, error read "Couldn't load rom". When I click on a game it works fine (I have it boot into the firmware upon launching a game). After I do that, if I exit out and retry booting the firmware by itself, it works fine. 

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$b: Failed to load firmware: FIRMWARE_NOT_BOOTABLE
	at f9.b$b.c(Unknown Source:57)
	at f9.b$b.a(Unknown Source:0)
	at f9.c.a(Unknown Source:4)
	at l6.a.j(Unknown Source:10)
	at b6.a.a(Unknown Source:14)
	at p6.f$a.c(Unknown Source:20)
	at p6.h.t(Unknown Source:9)
	at b6.t.a(Unknown Source:14)
	at p6.f.j(Unknown Source:12)
	at b6.a.a(Unknown Source:14)
	at l6.e$a.run(Unknown Source:2)
	at b6.s$a.run(Unknown Source:9)
	at r6.k.run(Unknown Source:13)
	at r6.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

```

**Configuration:**  
```
FirmwareCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=true, showBootScreen=true, dsBios7Uri=content://com.android.externalstorage.documents/tree/primary%3AEmulation%2FBios%2FDS/document/primary%3AEmulation%2FBios%2FDS%2Fbios7.bin, dsBios9Uri=content://com.android.externalstorage.documents/tree/primary%3AEmulation%2FBios%2FDS/document/primary%3AEmulation%2FBios%2FDS%2Fbios9.bin, dsFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3AEmulation%2FBios%2FDS/document/primary%3AEmulation%2FBios%2FDS%2Ffirmware.bin, dsiBios7Uri=content://com.android.externalstorage.documents/tree/primary%3AEmulation%2FBios%2FDSI/document/primary%3AEmulation%2FBios%2FDSI%2Fbios7.bin, dsiBios9Uri=content://com.android.externalstorage.documents/tree/primary%3AEmulation%2FBios%2FDSI/document/primary%3AEmulation%2FBios%2FDSI%2Fbios9.bin, dsiFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3AEmulation%2FBios%2FDSI/document/primary%3AEmulation%2FBios%2FDSI%2Ffirmware.bin, dsiNandUri=content://com.android.externalstorage.documents/tree/primary%3AEmulation%2FBios%2FDSI/document/primary%3AEmulation%2FBios%2FDSI%2Fnand.bin, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, rewindEnabled=false, rewindPeriodSeconds=10, rewindWindowSeconds=60, useJit=false, consoleType=DS, soundEnabled=true, audioInterpolation=CUBIC, audioBitrate=AUTO, volume=256, audioLatency=HIGH, micSource=DEVICE, firmwareConfiguration=FirmwareConfiguration(nickname=&E, message=how are you reading this? , language=1, favouriteColour=2, birthdayMonth=11, birthdayDay=15, randomizeMacAddress=false, internalMacAddress=null), rendererConfiguration=RendererConfiguration(videoFiltering=LCD, threadedRendering=true)), dsiBiosDirUri=content://com.android.externalstorage.documents/tree/primary%3AEmulation%2FBios%2FDS, dsBiosDirUri=content://com.android.externalstorage.documents/tree/primary%3AEmulation%2FBios%2FDSI)
```

**Comment by rafaelvcaetano** [comment]
This error should be fixed in the latest nightly build.
