### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by FrankGliker** [rafaelvcaetano/melonDS-android#1187]
* **Device model:** MI 5
* **Android version:** Android API 26
* **melonDS version:** Beta 1.8.0 PS

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
e9.c: Could not create temporary SRAM file at content://com.android.externalstorage.documents/tree/primary%3Aramdump/document/primary%3Aramdump
	at me.magnum.melonds.ui.emulator.EmulatorViewModel.R(Unknown Source:117)
	at i9.m$d$b.c(Unknown Source:67)
	at i9.m$d$b.a(Unknown Source:0)
	at i9.p.a(Unknown Source:8)
	at p6.a.t(Unknown Source:10)
	at b6.t.a(Unknown Source:14)
	at p6.e$a.c(Unknown Source:27)
	at p6.o$b.c(Unknown Source:26)
	at p6.o$c.c(Unknown Source:4)
	at m6.l$a.c(Unknown Source:6)
	at m6.i$a.run(Unknown Source:21)
	at b6.s$a.run(Unknown Source:9)
	at r6.k.run(Unknown Source:13)
	at r6.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=true, showBootScreen=false, dsBios7Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FKings%20of%20LA%20%26%20A4%20DSi%2FDS%20Environment/document/primary%3ADownload%2FKings%20of%20LA%20%26%20A4%20DSi%2FDS%20Environment%2Fbios7.bin, dsBios9Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FKings%20of%20LA%20%26%20A4%20DSi%2FDS%20Environment/document/primary%3ADownload%2FKings%20of%20LA%20%26%20A4%20DSi%2FDS%20Environment%2Fbios9.bin, dsFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FKings%20of%20LA%20%26%20A4%20DSi%2FDS%20Environment/document/primary%3ADownload%2FKings%20of%20LA%20%26%20A4%20DSi%2FDS%20Environment%2Ffirmware.bin, dsiBios7Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FKings%20of%20LA%20%26%20A4%20DSi%2FDSi%20Environment/document/primary%3ADownload%2FKings%20of%20LA%20%26%20A4%20DSi%2FDSi%20Environment%2Fbios7.bin, dsiBios9Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FKings%20of%20LA%20%26%20A4%20DSi%2FDSi%20Environment/document/primary%3ADownload%2FKings%20of%20LA%20%26%20A4%20DSi%2FDSi%20Environment%2Fbios9.bin, dsiFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FKings%20of%20LA%20%26%20A4%20DSi%2FDSi%20Environment/document/primary%3ADownload%2FKings%20of%20LA%20%26%20A4%20DSi%2FDSi%20Environment%2Ffirmware.bin, dsiNandUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FKings%20of%20LA%20%26%20A4%20DSi%2FDSi%20Environment/document/primary%3ADownload%2FKings%20of%20LA%20%26%20A4%20DSi%2FDSi%20Environment%2Fnand.bin, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=1.5, rewindEnabled=false, rewindPeriodSeconds=10, rewindWindowSeconds=60, useJit=true, consoleType=DSi, soundEnabled=true, audioInterpolation=CUBIC, audioBitrate=AUTO, volume=256, audioLatency=LOW, micSource=DEVICE, firmwareConfiguration=FirmwareConfiguration(nickname=FrankGliker, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1, randomizeMacAddress=false, internalMacAddress=null), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.externalstorage.documents/tree/primary%3ADownload, romUri=content://com.android.externalstorage.documents/tree/primary%3ADownload/document/primary%3ADownload%2FAsphalt%20-%20Urban%20GT%202%20(USA)%20(En%2CFr%2CEs)%2F0689%20-%20Asphalt%20-%20Urban%20GT%202%20(USA)%20(En%2CFr%2CEs).nds, sramUri=null)
```

**Comment by rafaelvcaetano** [comment]
Please try the [latest version](https://github.com/rafaelvcaetano/melonDS-android/releases/latest) where this problem should be fixed. Or download it from the [Play Store](https://play.google.com/store/apps/details?id=me.magnum.melonds) to always keep the app up-to-date. If you still encounter errors after updating, please open a new issue.
