### ISSUE TITLE
Mario? 

### ISSUE THREAD

**Issue by YinCastilloA** [rafaelvcaetano/melonDS-android#1189]
* **Device model:** JKM-
* **Android version:** Android API 28
* **melonDS version:** Beta 1.8.0 PS

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
e9.c: Could not create temporary SRAM file at content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FMario%20Party%20DS%20(USA)/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FMario%20Party%20DS%20(USA)
	at me.magnum.melonds.ui.emulator.EmulatorViewModel.R(Unknown Source:117)
	at i9.m$d$b.c(Unknown Source:67)
	at i9.m$d$b.a(Unknown Source:0)
	at i9.p.a(Unknown Source:8)
	at p6.a.t(Unknown Source:10)
	at b6.t.a(Unknown Source:14)
	at p6.e$a.c(Unknown Source:27)
	at p6.o$b.c(Unknown Source:26)
	at p6.o$c.c(Unknown Source:4)
	at m6.l$a.a(Unknown Source:10)
	at m6.i$a.run(Unknown Source:27)
	at b6.s$a.run(Unknown Source:9)
	at r6.k.run(Unknown Source:13)
	at r6.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:784)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=true, showBootScreen=true, dsBios7Uri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FNintendo/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FNintendo%2Fbios7.bin, dsBios9Uri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FNintendo/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FNintendo%2Fbios9.bin, dsFirmwareUri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FNintendo/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FNintendo%2Ffirmware.bin, dsiBios7Uri=null, dsiBios9Uri=null, dsiFirmwareUri=null, dsiNandUri=null, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, rewindEnabled=false, rewindPeriodSeconds=10, rewindWindowSeconds=60, useJit=true, consoleType=DS, soundEnabled=true, audioInterpolation=NONE, audioBitrate=AUTO, volume=256, audioLatency=MEDIUM, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Yin < 3, message=Hello, ball! , language=5, favouriteColour=4, birthdayMonth=11, birthdayDay=14, randomizeMacAddress=false, internalMacAddress=null), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FMario%20Party%20DS%20(USA), romUri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FMario%20Party%20DS%20(USA)/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FMario%20Party%20DS%20(USA)%2F1694%20-%20Mario%20Party%20DS%20(USA).nds, sramUri=null)
```

**Comment by rafaelvcaetano** [comment]
Please try the [latest version](https://github.com/rafaelvcaetano/melonDS-android/releases/latest) where this problem should be fixed. Or download it from the [Play Store](https://play.google.com/store/apps/details?id=me.magnum.melonds) to always keep the app up-to-date. If you still encounter errors after updating, please open a new issue.
