### ISSUE TITLE
Melon ds booting ROM issue

### ISSUE THREAD

**Issue by TheHeadlessC** [rafaelvcaetano/melonDS-android#1203]
* **Device model:** SM-A346E
* **Android version:** Android API 33
* **melonDS version:** Beta 1.8.0 PS

**Problem:**  
Melon DS cannot load ROM for mario kart DS.

**Stack trace:**  
```
e9.c: Could not create temporary SRAM file at content://com.android.externalstorage.documents/tree/primary%3ADS%20Games%2FMKDS%20Emulator/document/primary%3ADS%20Games%2FMKDS%20Emulator
	at me.magnum.melonds.ui.emulator.EmulatorViewModel.R(Unknown Source:117)
	at i9.m$d$b.c(Unknown Source:67)
	at i9.m$d$b.a(Unknown Source:0)
	at i9.p.a(Unknown Source:8)
	at p6.a.t(Unknown Source:10)
	at b6.t.a(Unknown Source:14)
	at p6.e$a.c(Unknown Source:27)
	at p6.o$b.c(Unknown Source:26)
	at p6.o$c.c(Unknown Source:4)
	at m6.l$a.c(Unknown Source:6)
	at m6.i$a.run(Unknown Source:21)
	at b6.s$a.run(Unknown Source:9)
	at r6.k.run(Unknown Source:13)
	at r6.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=false, showBootScreen=false, dsBios7Uri=content://com.android.externalstorage.documents/tree/primary%3AMKDS%20Emulator/document/primary%3AMKDS%20Emulator%2Fbios7.bin, dsBios9Uri=content://com.android.externalstorage.documents/tree/primary%3AMKDS%20Emulator/document/primary%3AMKDS%20Emulator%2Fbios9.bin, dsFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3AMKDS%20Emulator/document/primary%3AMKDS%20Emulator%2Ffirmware.bin, dsiBios7Uri=content://com.android.externalstorage.documents/tree/primary%3AMKDS%20Emulator/document/primary%3AMKDS%20Emulator%2Fbios7.bin, dsiBios9Uri=content://com.android.externalstorage.documents/tree/primary%3AMKDS%20Emulator/document/primary%3AMKDS%20Emulator%2Fbios9.bin, dsiFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3AMKDS%20Emulator/document/primary%3AMKDS%20Emulator%2Ffirmware.bin, dsiNandUri=null, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, rewindEnabled=false, rewindPeriodSeconds=10, rewindWindowSeconds=60, useJit=true, consoleType=DS, soundEnabled=true, audioInterpolation=NONE, audioBitrate=AUTO, volume=197, audioLatency=MEDIUM, micSource=DEVICE, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1, randomizeMacAddress=false, internalMacAddress=00:09:BF:A5:FD:01), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.externalstorage.documents/tree/primary%3AMKDS%20Emulator, romUri=content://com.android.externalstorage.documents/tree/primary%3AMKDS%20Emulator/document/primary%3AMKDS%20Emulator%2FMario%20Kart%20DS%20(USA%2C%20Australia)%20(En%2CFr%2CDe%2CEs%2CIt)%2FMario%20Kart%20DS%20(USA%2C%20Australia)%20(En%2CFr%2CDe%2CEs%2CIt).nds, sramUri=null)
```

**Comment by rafaelvcaetano** [comment]
Please try the [latest version](https://github.com/rafaelvcaetano/melonDS-android/releases/latest) where this problem should be fixed. Or download it from the [Play Store](https://play.google.com/store/apps/details?id=me.magnum.melonds) to always keep the app up-to-date. If you still encounter errors after updating, please open a new issue.
