### ISSUE TITLE
Can't play games in DS 

### ISSUE THREAD

**Issue by Jscnejdnxn** [rafaelvcaetano/melonDS-android#1206]
* **Device model:** GN2200
* **Android version:** Android API 31
* **melonDS version:** Beta 1.8.0 PS

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$b: Failed to load firmware: FIRMWARE_NOT_BOOTABLE
	at f9.b$b.c(Unknown Source:57)
	at f9.b$b.a(Unknown Source:0)
	at f9.c.a(Unknown Source:4)
	at l6.a.j(Unknown Source:10)
	at b6.a.a(Unknown Source:14)
	at p6.f$a.c(Unknown Source:20)
	at p6.h.t(Unknown Source:9)
	at b6.t.a(Unknown Source:14)
	at p6.f.j(Unknown Source:12)
	at b6.a.a(Unknown Source:14)
	at l6.e$a.run(Unknown Source:2)
	at b6.s$a.run(Unknown Source:9)
	at r6.k.run(Unknown Source:13)
	at r6.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

```

**Configuration:**  
```
FirmwareCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=true, showBootScreen=true, dsBios7Uri=content://com.android.providers.downloads.documents/tree/msd%3A1000004129/document/msf%3A1000004132, dsBios9Uri=content://com.android.providers.downloads.documents/tree/msd%3A1000004129/document/msf%3A1000004131, dsFirmwareUri=content://com.android.providers.downloads.documents/tree/msd%3A1000004129/document/msf%3A1000004130, dsiBios7Uri=content://com.android.providers.downloads.documents/tree/msd%3A1000004129/document/msf%3A1000004132, dsiBios9Uri=content://com.android.providers.downloads.documents/tree/msd%3A1000004129/document/msf%3A1000004131, dsiFirmwareUri=content://com.android.providers.downloads.documents/tree/msd%3A1000004129/document/msf%3A1000004130, dsiNandUri=null, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, rewindEnabled=false, rewindPeriodSeconds=10, rewindWindowSeconds=60, useJit=true, consoleType=DS, soundEnabled=true, audioInterpolation=NONE, audioBitrate=AUTO, volume=256, audioLatency=MEDIUM, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1, randomizeMacAddress=false, internalMacAddress=null), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), dsiBiosDirUri=content://com.android.providers.downloads.documents/tree/msd%3A1000004129, dsBiosDirUri=content://com.android.providers.downloads.documents/tree/msd%3A1000004129)
```

**Comment by 53bas** [comment]
me.magnum.melonds.ui.emulator.EmulatorActivity$b: Failed to load firmware: FIRMWARE_NOT_BOOTABLE
	at f9.b$b.c(Unknown Source:57)
	at f9.b$b.a(Unknown Source:0)
	at f9.c.a(Unknown Source:4)
	at l6.a.j(Unknown Source:10)
	at b6.a.a(Unknown Source:14)
	at p6.f$a.c(Unknown Source:20)
	at p6.h.t(Unknown Source:9)
	at b6.t.a(Unknown Source:14)
	at p6.f.j(Unknown Source:12)
	at b6.a.a(Unknown Source:14)
	at l6.e$a.run(Unknown Source:2)
	at b6.s$a.run(Unknown Source:9)
	at r6.k.run(Unknown Source:13)
	at r6.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by rafaelvcaetano** [comment]
Please try the [latest version](https://github.com/rafaelvcaetano/melonDS-android/releases/latest) where this problem should be fixed. Or download it from the [Play Store](https://play.google.com/store/apps/details?id=me.magnum.melonds) to always keep the app up-to-date. If you still encounter errors after updating, please open a new issue.
