### ISSUE TITLE
Pokémon black version 2

### ISSUE THREAD

**Issue by yhamskee** [rafaelvcaetano/melonDS-android#1210]
* **Device model:** RMX3081
* **Android version:** Android API 33
* **melonDS version:** Beta 1.8.0 GH

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
h9.c: Could not create temporary SRAM file at content://com.android.externalstorage.documents/tree/primary%3ADownload%2FPlayStation%202%C2%AE%2Fds%2FSaveData/document/primary%3ADownload%2FPlayStation%202%C2%AE%2Fds%2FSaveData
	at me.magnum.melonds.ui.emulator.EmulatorViewModel.R(Unknown Source:117)
	at l9.m$d$b.c(Unknown Source:67)
	at l9.m$d$b.a(Unknown Source:0)
	at l9.p.a(Unknown Source:8)
	at q6.a.t(Unknown Source:10)
	at b6.u.a(Unknown Source:14)
	at q6.e$a.c(Unknown Source:27)
	at q6.o$b.c(Unknown Source:26)
	at q6.o$c.c(Unknown Source:4)
	at n6.l$a.c(Unknown Source:6)
	at n6.i$a.run(Unknown Source:21)
	at b6.t$a.run(Unknown Source:9)
	at s6.k.run(Unknown Source:13)
	at s6.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=true, showBootScreen=false, dsBios7Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FNintendo%20DSI%20Bios%20and%20Firmware/document/primary%3ADownload%2FNintendo%20DSI%20Bios%20and%20Firmware%2Fbios7.bin, dsBios9Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FNintendo%20DSI%20Bios%20and%20Firmware/document/primary%3ADownload%2FNintendo%20DSI%20Bios%20and%20Firmware%2Fbios9.bin, dsFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FNintendo%20DSI%20Bios%20and%20Firmware/document/primary%3ADownload%2FNintendo%20DSI%20Bios%20and%20Firmware%2Ffirmware.bin, dsiBios7Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FNintendo%20DSI%20Bios%20and%20Firmware%2FNintendo%20DSI%20Bios%20and%20Firmware/document/primary%3ADownload%2FNintendo%20DSI%20Bios%20and%20Firmware%2FNintendo%20DSI%20Bios%20and%20Firmware%2Fbios7.bin, dsiBios9Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FNintendo%20DSI%20Bios%20and%20Firmware%2FNintendo%20DSI%20Bios%20and%20Firmware/document/primary%3ADownload%2FNintendo%20DSI%20Bios%20and%20Firmware%2FNintendo%20DSI%20Bios%20and%20Firmware%2Fbios9.bin, dsiFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FNintendo%20DSI%20Bios%20and%20Firmware%2FNintendo%20DSI%20Bios%20and%20Firmware/document/primary%3ADownload%2FNintendo%20DSI%20Bios%20and%20Firmware%2FNintendo%20DSI%20Bios%20and%20Firmware%2Ffirmware.bin, dsiNandUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FNintendo%20DSI%20Bios%20and%20Firmware%2FNintendo%20DSI%20Bios%20and%20Firmware/document/primary%3ADownload%2FNintendo%20DSI%20Bios%20and%20Firmware%2FNintendo%20DSI%20Bios%20and%20Firmware%2Fnand.bin, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, rewindEnabled=false, rewindPeriodSeconds=10, rewindWindowSeconds=60, useJit=true, consoleType=DS, soundEnabled=true, audioInterpolation=NONE, audioBitrate=AUTO, volume=256, audioLatency=MEDIUM, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1, randomizeMacAddress=true, internalMacAddress=null), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FNDS, romUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FNDS/document/primary%3ADownload%2FNDS%2FPokemon%20Black%20Version%202%20(DSi%20Enhanced).nds, sramUri=null)
```

**Comment by rafaelvcaetano** [comment]
Please try the [latest version](https://github.com/rafaelvcaetano/melonDS-android/releases/latest) where this problem should be fixed. Or download it from the [Play Store](https://play.google.com/store/apps/details?id=me.magnum.melonds) to always keep the app up-to-date. If you still encounter errors after updating, please open a new issue.
