### ISSUE TITLE
Pokémon 

### ISSUE THREAD

**Issue by 53bas** [rafaelvcaetano/melonDS-android#1213]
* **Device model:** SM-J610G
* **Android version:** Android API 29
* **melonDS version:** Beta 1.8.0 PS

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$c: Failed to load ROM: NDS_FAILED
	at i9.m$d$b.c(Unknown Source:129)
	at i9.m$d$b.a(Unknown Source:0)
	at i9.p.a(Unknown Source:8)
	at p6.a.t(Unknown Source:10)
	at b6.t.a(Unknown Source:14)
	at p6.e$a.c(Unknown Source:27)
	at p6.o$b.c(Unknown Source:26)
	at p6.o$c.c(Unknown Source:4)
	at m6.l$a.c(Unknown Source:6)
	at m6.i$a.run(Unknown Source:21)
	at b6.s$a.run(Unknown Source:9)
	at r6.k.run(Unknown Source:13)
	at r6.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=false, showBootScreen=false, dsBios7Uri=null, dsBios9Uri=null, dsFirmwareUri=null, dsiBios7Uri=null, dsiBios9Uri=null, dsiFirmwareUri=null, dsiNandUri=null, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, rewindEnabled=false, rewindPeriodSeconds=10, rewindWindowSeconds=60, useJit=false, consoleType=DS, soundEnabled=true, audioInterpolation=NONE, audioBitrate=AUTO, volume=256, audioLatency=MEDIUM, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1, randomizeMacAddress=false, internalMacAddress=00:09:BF:BC:0F:07), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.externalstorage.documents/tree/0403-0201%3AAndroid%2Fdata%2Fcom.android.chrome%2Ffiles%2FDownload, romUri=content://com.android.externalstorage.documents/tree/0403-0201%3AAndroid%2Fdata%2Fcom.android.chrome%2Ffiles%2FDownload/document/0403-0201%3AAndroid%2Fdata%2Fcom.android.chrome%2Ffiles%2FDownload%2FPokemon%20Mega%20Delta%20(v2.2).nds.zip, sramUri=content://com.android.externalstorage.documents/tree/0403-0201%3AAndroid%2Fdata%2Fcom.android.chrome%2Ffiles%2FDownload/document/0403-0201%3AAndroid%2Fdata%2Fcom.android.chrome%2Ffiles%2FDownload%2FPokemon%20Mega%20Delta%20(v2.2).nds.sav)
```

**Comment by chichibooxd** [comment]
Get the BIOS.

**Comment by rafaelvcaetano** [comment]
It looks like you are using a bad ROM. Try launching it on another emulator and they also fail, it means the ROM is broken. If other emulators work fine, please open another issue.
