### ISSUE TITLE
Puyo Puyo 20th anniversary eng translation

### ISSUE THREAD

**Issue by Drago-Cuven** [rafaelvcaetano/melonDS-android#1218]
* **Device model:** octopus (ChromeOS)
* **Android version:** Android API 30
* **melonDS version:** Beta 1.8.0 PS

**Problem:**  
rom crash

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$c: Failed to load ROM: NDS_FAILED
	at i9.m$d$b.c(Unknown Source:129)
	at i9.m$d$b.a(Unknown Source:0)
	at i9.p.a(Unknown Source:8)
	at p6.a.t(Unknown Source:10)
	at b6.t.a(Unknown Source:14)
	at p6.e$a.c(Unknown Source:27)
	at p6.o$b.c(Unknown Source:26)
	at p6.o$c.c(Unknown Source:4)
	at m6.l$a.a(Unknown Source:10)
	at m6.i$a.run(Unknown Source:27)
	at b6.s$a.run(Unknown Source:9)
	at r6.k.run(Unknown Source:13)
	at r6.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=false, showBootScreen=false, dsBios7Uri=null, dsBios9Uri=null, dsFirmwareUri=null, dsiBios7Uri=null, dsiBios9Uri=null, dsiFirmwareUri=null, dsiNandUri=null, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, rewindEnabled=false, rewindPeriodSeconds=10, rewindWindowSeconds=60, useJit=true, consoleType=DS, soundEnabled=true, audioInterpolation=NONE, audioBitrate=AUTO, volume=256, audioLatency=MEDIUM, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1, randomizeMacAddress=false, internalMacAddress=00:09:BF:74:56:F5), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.externalstorage.documents/tree/0000000000000000000000000000CAFEF00D2019%3ADownloads%2FRoms%2FDS, romUri=content://com.android.externalstorage.documents/tree/0000000000000000000000000000CAFEF00D2019%3ADownloads%2FRoms%2FDS/document/0000000000000000000000000000CAFEF00D2019%3ADownloads%2FRoms%2FDS%2FPuyo%20Puyo%2020th%20Anniversary%20(English%20v1.2).nds, sramUri=content://com.android.externalstorage.documents/tree/0000000000000000000000000000CAFEF00D2019%3ADownloads%2FRoms%2FDS/document/0000000000000000000000000000CAFEF00D2019%3ADownloads%2FRoms%2FDS%2FPuyo%20Puyo%2020th%20Anniversary%20(English%20v1.2).sav)
```

**Comment by rafaelvcaetano** [comment]
Have you tried running it in another emulator to confirm that the ROM works fine? It looks like you have a bad ROM.

**Comment by Drago-Cuven** [comment]
Honestly I don't remember this issue but you were probably right...
