### ISSUE TITLE
Will nicht funktionieren

### ISSUE THREAD

**Issue by Rafaeldtdzrzezwf** [rafaelvcaetano/melonDS-android#1225]
* **Device model:** SM-X200
* **Android version:** Android API 33
* **melonDS version:** Beta 1.8.0 PS

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
e9.c: Could not create temporary SRAM file at content://com.android.externalstorage.documents/tree/primary%3ADownload%2FMDS%20Firmware%20USA_AdeDomplang%2FMelonDS%2FBios/document/primary%3ADownload%2FMDS%20Firmware%20USA_AdeDomplang%2FMelonDS%2FBios
	at me.magnum.melonds.ui.emulator.EmulatorViewModel.R(Unknown Source:117)
	at i9.m$d$b.c(Unknown Source:67)
	at i9.m$d$b.a(Unknown Source:0)
	at i9.p.a(Unknown Source:8)
	at p6.a.t(Unknown Source:10)
	at b6.t.a(Unknown Source:14)
	at p6.e$a.c(Unknown Source:27)
	at p6.o$b.c(Unknown Source:26)
	at p6.o$c.c(Unknown Source:4)
	at m6.l$a.c(Unknown Source:6)
	at m6.i$a.run(Unknown Source:21)
	at b6.s$a.run(Unknown Source:9)
	at r6.k.run(Unknown Source:13)
	at r6.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=true, showBootScreen=true, dsBios7Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FMDS%20Firmware%20USA_AdeDomplang%2FMelonDS%2FBios%2FDS/document/primary%3ADownload%2FMDS%20Firmware%20USA_AdeDomplang%2FMelonDS%2FBios%2FDS%2Fbios7.bin, dsBios9Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FMDS%20Firmware%20USA_AdeDomplang%2FMelonDS%2FBios%2FDS/document/primary%3ADownload%2FMDS%20Firmware%20USA_AdeDomplang%2FMelonDS%2FBios%2FDS%2Fbios9.bin, dsFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FMDS%20Firmware%20USA_AdeDomplang%2FMelonDS%2FBios%2FDS/document/primary%3ADownload%2FMDS%20Firmware%20USA_AdeDomplang%2FMelonDS%2FBios%2FDS%2Ffirmware.bin, dsiBios7Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FMDS%20Firmware%20USA_AdeDomplang%2FMelonDS%2FBios%2FDSi/document/primary%3ADownload%2FMDS%20Firmware%20USA_AdeDomplang%2FMelonDS%2FBios%2FDSi%2Fbios7.bin, dsiBios9Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FMDS%20Firmware%20USA_AdeDomplang%2FMelonDS%2FBios%2FDSi/document/primary%3ADownload%2FMDS%20Firmware%20USA_AdeDomplang%2FMelonDS%2FBios%2FDSi%2Fbios9.bin, dsiFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FMDS%20Firmware%20USA_AdeDomplang%2FMelonDS%2FBios%2FDSi/document/primary%3ADownload%2FMDS%20Firmware%20USA_AdeDomplang%2FMelonDS%2FBios%2FDSi%2Ffirmware.bin, dsiNandUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FMDS%20Firmware%20USA_AdeDomplang%2FMelonDS%2FBios%2FDSi/document/primary%3ADownload%2FMDS%20Firmware%20USA_AdeDomplang%2FMelonDS%2FBios%2FDSi%2Fnand.bin, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=8.0, rewindEnabled=true, rewindPeriodSeconds=60, rewindWindowSeconds=300, useJit=true, consoleType=DSi, soundEnabled=true, audioInterpolation=NONE, audioBitrate=AUTO, volume=256, audioLatency=MEDIUM, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=8, birthdayDay=22, randomizeMacAddress=false, internalMacAddress=null), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FDs, romUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FDs/document/primary%3ADownload%2FDs%2F0434%20-%20New%20Super%20Mario%20Bros.%20(USA).nds, sramUri=null)
```
/kill
```c++

```

**Comment by rafaelvcaetano** [comment]
Please try the [latest version](https://github.com/rafaelvcaetano/melonDS-android/releases/latest) where this problem should be fixed. Or download it from the [Play Store](https://play.google.com/store/apps/details?id=me.magnum.melonds) to always keep the app up-to-date. If you still encounter errors after updating, please open a new issue.

**Comment by Rafaeldtdzrzezwf** [comment]
Danke

Rafael Caetano ***@***.***> schrieb am So., 5. Nov. 2023,
18:13:
