### ISSUE TITLE
I have DS and not working on MelonDS! Help!

### ISSUE THREAD

**Issue by truth2022-1A** [rafaelvcaetano/melonDS-android#1227]
* **Device model:** SCG02
* **Android version:** Android API 25
* **melonDS version:** Beta 1.8.0 PS

**Problem:**  
not working.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$b: Failed to load firmware: FIRMWARE_NOT_BOOTABLE
	at f9.b$b.c(SourceFile)
	at f9.b$b.a(SourceFile)
	at f9.c.a(SourceFile)
	at l6.a.j(SourceFile)
	at b6.a.a(SourceFile)
	at p6.f$a.c(SourceFile)
	at p6.h.t(SourceFile)
	at b6.t.a(SourceFile)
	at p6.f.j(SourceFile)
	at b6.a.a(SourceFile)
	at l6.e$a.run(SourceFile)
	at b6.s$a.run(SourceFile)
	at r6.k.run(SourceFile)
	at r6.k.call(SourceFile)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

```

**Configuration:**  
```
FirmwareCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=true, showBootScreen=true, dsBios7Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDS/document/primary%3ADownload%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDS%2Fbios7.bin, dsBios9Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDS/document/primary%3ADownload%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDS%2Fbios9.bin, dsFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDS/document/primary%3ADownload%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDS%2Ffirmware.bin, dsiBios7Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDSi/document/primary%3ADownload%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDSi%2Fbios7.bin, dsiBios9Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDSi/document/primary%3ADownload%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDSi%2Fbios9.bin, dsiFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDSi/document/primary%3ADownload%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDSi%2Ffirmware.bin, dsiNandUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDSi/document/primary%3ADownload%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDSi%2Fnand.bin, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, rewindEnabled=false, rewindPeriodSeconds=10, rewindWindowSeconds=60, useJit=true, consoleType=DS, soundEnabled=true, audioInterpolation=NONE, audioBitrate=AUTO, volume=256, audioLatency=MEDIUM, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1, randomizeMacAddress=false, internalMacAddress=null), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), dsiBiosDirUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDS, dsBiosDirUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDSi)
```

**Comment by rafaelvcaetano** [comment]
Please try the [latest version](https://github.com/rafaelvcaetano/melonDS-android/releases/latest) where this problem should be fixed. Or download it from the [Play Store](https://play.google.com/store/apps/details?id=me.magnum.melonds) to always keep the app up-to-date. If you still encounter errors after updating, please open a new issue.
