### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by iamweeb2** [rafaelvcaetano/melonDS-android#1228]
* **Device model:** SM-A515F
* **Android version:** Android API 33
* **melonDS version:** Beta 1.8.0 PS

**Problem:**  
It has all these chinese characters. I'm not sure if i installed the rom right cuz its my first time using so i renamed it to .nds

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$c: Failed to load ROM: NDS_FAILED
	at i9.m$d$b.c(Unknown Source:129)
	at i9.m$d$b.a(Unknown Source:0)
	at i9.p.a(Unknown Source:8)
	at p6.a.t(Unknown Source:10)
	at b6.t.a(Unknown Source:14)
	at p6.e$a.c(Unknown Source:27)
	at p6.o$b.c(Unknown Source:26)
	at p6.o$c.c(Unknown Source:4)
	at m6.l$a.c(Unknown Source:6)
	at m6.i$a.run(Unknown Source:21)
	at b6.s$a.run(Unknown Source:9)
	at r6.k.run(Unknown Source:13)
	at r6.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=false, showBootScreen=false, dsBios7Uri=null, dsBios9Uri=null, dsFirmwareUri=null, dsiBios7Uri=null, dsiBios9Uri=null, dsiFirmwareUri=null, dsiNandUri=null, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, rewindEnabled=false, rewindPeriodSeconds=10, rewindWindowSeconds=60, useJit=true, consoleType=DS, soundEnabled=true, audioInterpolation=NONE, audioBitrate=AUTO, volume=256, audioLatency=MEDIUM, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1, randomizeMacAddress=false, internalMacAddress=00:09:BF:FB:6F:7D), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.externalstorage.documents/tree/primary%3ADS%20Games, romUri=content://com.android.externalstorage.documents/tree/primary%3ADS%20Games/document/primary%3ADS%20Games%2FHatsune%20Miku%20-%20Project%20Mirai%20DX%20(USA).nds, sramUri=content://com.android.externalstorage.documents/tree/primary%3ADS%20Games/document/primary%3ADS%20Games%2FHatsune%20Miku%20-%20Project%20Mirai%20DX%20(USA).sav)
```

**Comment by rafaelvcaetano** [comment]
Are you sure you are trying to run a proper NDS ROM? Anyway, I'll close this issue for now, but try again using the new version and feel free to open a new issue if it still happens. Also try running the ROM in other emulators to see if they work fine with it. If other emulators cannot open it, then it's a problem with the ROM.
