### ISSUE TITLE
MelonDs

### ISSUE THREAD

**Issue by fantoniooliveros** [rafaelvcaetano/melonDS-android#129]
* **Device model:** CAM-L23
* **Android version:** Android API 23

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$f: Failed to load ROM: NDS_FAILED
	at me.magnum.melonds.ui.emulator.j$d$a$a.a()
	at f.a.b0.e.e.a.o()
	at f.a.s.a()
	at f.a.b0.e.b.e$a.d()
	at f.a.b0.e.b.l$a.d()
	at f.a.b0.e.b.j$a.run()
	at f.a.r$a.run()
	at f.a.b0.g.j.run()
	at f.a.b0.g.j.call()
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:833)

```

**Comment by rafaelvcaetano** [comment]
Please try the latest [Beta 1.2.2](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.2.2) release. If the problem persists, please open a new issue.
