### ISSUE TITLE
Dont play

### ISSUE THREAD

**Issue by bruno7575** [rafaelvcaetano/melonDS-android#131]
* **Device model:** SM-G965F
* **Android version:** Android API 29
* **melonDS version:** Beta 1.2.2

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$f: Failed to load ROM: NDS_FAILED
	at me.magnum.melonds.ui.emulator.j$e$a$a.a(Unknown Source:204)
	at f.a.b0.e.e.a.o(Unknown Source:10)
	at f.a.s.a(Unknown Source:14)
	at f.a.b0.e.b.e$a.d(Unknown Source:26)
	at f.a.b0.e.b.l$a.d(Unknown Source:2)
	at f.a.b0.e.b.j$a.run(Unknown Source:21)
	at f.a.r$a.run(Unknown Source:9)
	at f.a.b0.g.j.run(Unknown Source:13)
	at f.a.b0.g.j.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=false, dsConfigDirectory=null/, dsiConfigDirectory=null/, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, useJit=true, consoleType=DS, soundEnabled=true, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romPath=/storage/msf/116057, sramPath=/storage/msf/116057.sav)
```

**Comment by rafaelvcaetano** [comment]
In which directory did you place your ROM files?

**Comment by bruno7575** [comment]
Descargas

**Comment by rafaelvcaetano** [comment]
Intenta mover las ROMs a otra carpeta afuera de las descargas y intenta de nuevo. Después dime como te va.

**Comment by bruno7575** [comment]
Funciono, gracias

**Comment by bruno7575** [comment]
Aun no hay multiplayer ?

**Comment by rafaelvcaetano** [comment]
Más o menos. Puedes encontrar más informacion acerca de eso en la [Wiki](https://github.com/rafaelvcaetano/melonDS-android/wiki/Local-multiplayer) y en [esta discusión](https://github.com/rafaelvcaetano/melonDS-android/discussions/66).

**Comment by bruno7575** [comment]
Perfecto
