### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Gurtarans** [rafaelvcaetano/melonDS-android#1312]
* **Device model:** I2127
* **Android version:** Android API 34
* **melonDS version:** Beta 1.8.0 PS

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
e9.c: Could not create temporary SRAM file at content://com.android.externalstorage.documents/tree/primary%3AEmulator%20Rom%20And%20Save%20Building%20%20For%20DS%2C3DS%20GbaSp%20and%20GBA%2FDS%20Emulator%20Roms%20And%20Saves%20Room%2FDS%20Emulator%20Saves%20Room/document/primary%3AEmulator%20Rom%20And%20Save%20Building%20%20For%20DS%2C3DS%20GbaSp%20and%20GBA%2FDS%20Emulator%20Roms%20And%20Saves%20Room%2FDS%20Emulator%20Saves%20Room
	at me.magnum.melonds.ui.emulator.EmulatorViewModel.R(Unknown Source:117)
	at i9.m$d$b.c(Unknown Source:67)
	at i9.m$d$b.a(Unknown Source:0)
	at i9.p.a(Unknown Source:8)
	at p6.a.t(Unknown Source:10)
	at b6.t.a(Unknown Source:14)
	at p6.e$a.c(Unknown Source:27)
	at p6.o$b.c(Unknown Source:26)
	at p6.o$c.c(Unknown Source:4)
	at m6.l$a.c(Unknown Source:6)
	at m6.i$a.run(Unknown Source:21)
	at b6.s$a.run(Unknown Source:9)
	at r6.k.run(Unknown Source:13)
	at r6.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=true, showBootScreen=true, dsBios7Uri=content://com.android.externalstorage.documents/tree/primary%3AEmulator%20Rom%20And%20Save%20Building%20%20For%20DS%2C3DS%20GbaSp%20and%20GBA%2FDS%20And%20DSi%20BiWare%2FMelonDS%20%2B%20BIOS%20Files%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDS/document/primary%3AEmulator%20Rom%20And%20Save%20Building%20%20For%20DS%2C3DS%20GbaSp%20and%20GBA%2FDS%20And%20DSi%20BiWare%2FMelonDS%20%2B%20BIOS%20Files%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDS%2Fbios7.bin, dsBios9Uri=content://com.android.externalstorage.documents/tree/primary%3AEmulator%20Rom%20And%20Save%20Building%20%20For%20DS%2C3DS%20GbaSp%20and%20GBA%2FDS%20And%20DSi%20BiWare%2FMelonDS%20%2B%20BIOS%20Files%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDS/document/primary%3AEmulator%20Rom%20And%20Save%20Building%20%20For%20DS%2C3DS%20GbaSp%20and%20GBA%2FDS%20And%20DSi%20BiWare%2FMelonDS%20%2B%20BIOS%20Files%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDS%2Fbios9.bin, dsFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3AEmulator%20Rom%20And%20Save%20Building%20%20For%20DS%2C3DS%20GbaSp%20and%20GBA%2FDS%20And%20DSi%20BiWare%2FMelonDS%20%2B%20BIOS%20Files%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDS/document/primary%3AEmulator%20Rom%20And%20Save%20Building%20%20For%20DS%2C3DS%20GbaSp%20and%20GBA%2FDS%20And%20DSi%20BiWare%2FMelonDS%20%2B%20BIOS%20Files%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDS%2Ffirmware.bin, dsiBios7Uri=content://com.android.externalstorage.documents/tree/primary%3AEmulator%20Rom%20And%20Save%20Building%20%20For%20DS%2C3DS%20GbaSp%20and%20GBA%2FDS%20And%20DSi%20BiWare%2FMelonDS%20%2B%20BIOS%20Files%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDSi/document/primary%3AEmulator%20Rom%20And%20Save%20Building%20%20For%20DS%2C3DS%20GbaSp%20and%20GBA%2FDS%20And%20DSi%20BiWare%2FMelonDS%20%2B%20BIOS%20Files%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDSi%2Fbios7.bin, dsiBios9Uri=content://com.android.externalstorage.documents/tree/primary%3AEmulator%20Rom%20And%20Save%20Building%20%20For%20DS%2C3DS%20GbaSp%20and%20GBA%2FDS%20And%20DSi%20BiWare%2FMelonDS%20%2B%20BIOS%20Files%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDSi/document/primary%3AEmulator%20Rom%20And%20Save%20Building%20%20For%20DS%2C3DS%20GbaSp%20and%20GBA%2FDS%20And%20DSi%20BiWare%2FMelonDS%20%2B%20BIOS%20Files%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDSi%2Fbios9.bin, dsiFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3AEmulator%20Rom%20And%20Save%20Building%20%20For%20DS%2C3DS%20GbaSp%20and%20GBA%2FDS%20And%20DSi%20BiWare%2FMelonDS%20%2B%20BIOS%20Files%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDSi/document/primary%3AEmulator%20Rom%20And%20Save%20Building%20%20For%20DS%2C3DS%20GbaSp%20and%20GBA%2FDS%20And%20DSi%20BiWare%2FMelonDS%20%2B%20BIOS%20Files%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDSi%2Ffirmware.bin, dsiNandUri=content://com.android.externalstorage.documents/tree/primary%3AEmulator%20Rom%20And%20Save%20Building%20%20For%20DS%2C3DS%20GbaSp%20and%20GBA%2FDS%20And%20DSi%20BiWare%2FMelonDS%20%2B%20BIOS%20Files%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDSi/document/primary%3AEmulator%20Rom%20And%20Save%20Building%20%20For%20DS%2C3DS%20GbaSp%20and%20GBA%2FDS%20And%20DSi%20BiWare%2FMelonDS%20%2B%20BIOS%20Files%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDSi%2Fnand.bin, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=8.0, rewindEnabled=false, rewindPeriodSeconds=10, rewindWindowSeconds=60, useJit=true, consoleType=DS, soundEnabled=true, audioInterpolation=NONE, audioBitrate=AUTO, volume=256, audioLatency=MEDIUM, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1, randomizeMacAddress=false, internalMacAddress=null), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.externalstorage.documents/tree/primary%3AEmulator%20Rom%20And%20Save%20Building%20%20For%20DS%2C3DS%20GbaSp%20and%20GBA%2FDS%20Emulator%20Roms%20And%20Saves%20Room, romUri=content://com.android.externalstorage.documents/tree/primary%3AEmulator%20Rom%20And%20Save%20Building%20%20For%20DS%2C3DS%20GbaSp%20and%20GBA%2FDS%20Emulator%20Roms%20And%20Saves%20Room/document/primary%3AEmulator%20Rom%20And%20Save%20Building%20%20For%20DS%2C3DS%20GbaSp%20and%20GBA%2FDS%20Emulator%20Roms%20And%20Saves%20Room%2FPokemon%20Black%202%20Redux%20Complete%20(v1.4.1).zip, sramUri=null)
```

**Comment by rafaelvcaetano** [comment]
This issue should already be fixed. Please try the latest version of the app. If the issue persists, please open a new ticket.

**Comment by Gurtarans** [comment]
Ill try it
