### ISSUE TITLE
Pokemon

### ISSUE THREAD

**Issue by MCCaisen** [rafaelvcaetano/melonDS-android#1326]
* **Device model:** STK-LX3
* **Android version:** Android API 29
* **melonDS version:** Beta 1.7.0 GH

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$c: Failed to load ROM: NDS_FAILED
	at n6.q.N(Unknown Source:143)
	at n6.q.x(Unknown Source:0)
	at n6.p.a(Unknown Source:8)
	at b4.a.v(Unknown Source:10)
	at m3.u.b(Unknown Source:14)
	at b4.f$a.d(Unknown Source:27)
	at b4.p$b.c(Unknown Source:26)
	at b4.p$c.d(Unknown Source:4)
	at y3.m$a.a(Unknown Source:10)
	at y3.j$a.run(Unknown Source:27)
	at m3.t$a.run(Unknown Source:9)
	at d4.k.run(Unknown Source:13)
	at d4.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=true, showBootScreen=false, dsBios7Uri=content://com.android.providers.downloads.documents/tree/msd%3A228331/document/msf%3A228332, dsBios9Uri=content://com.android.providers.downloads.documents/tree/msd%3A228331/document/msf%3A228333, dsFirmwareUri=content://com.android.providers.downloads.documents/tree/msd%3A228331/document/msf%3A228334, dsiBios7Uri=null, dsiBios9Uri=null, dsiFirmwareUri=null, dsiNandUri=null, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, rewindEnabled=false, rewindPeriodSeconds=10, rewindWindowSeconds=60, useJit=true, consoleType=DS, soundEnabled=true, audioInterpolation=NONE, audioBitrate=AUTO, volume=256, audioLatency=MEDIUM, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1, randomizeMacAddress=false, internalMacAddress=null), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.providers.downloads.documents/tree/msd%3A228317, romUri=content://com.android.providers.downloads.documents/tree/msd%3A228317/document/msf%3A228329, sramUri=content://com.android.providers.downloads.documents/tree/msd%3A228317/document/msf%3A228339)
```

**Comment by rafaelvcaetano** [comment]
Please try the [latest version](https://github.com/rafaelvcaetano/melonDS-android/releases/latest) where this problem should be fixed. Or download it from the [Play Store](https://play.google.com/store/apps/details?id=me.magnum.melonds) to always keep the app up-to-date. If you still encounter errors after updating, please open a new issue.
