### ISSUE TITLE
Erro no Pokemon 

### ISSUE THREAD

**Issue by akirasilva** [rafaelvcaetano/melonDS-android#140]
* **Device model:** SM-A307GT
* **Android version:** Android API 29
* **melonDS version:** Beta 1.2.2

**Problem:**  
Pokemon White 2 Version erro

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$f: Failed to load ROM: NDS_FAILED
	at me.magnum.melonds.ui.emulator.j$e$a$a.a(Unknown Source:204)
	at f.a.b0.e.e.a.o(Unknown Source:10)
	at f.a.s.a(Unknown Source:14)
	at f.a.b0.e.b.e$a.d(Unknown Source:26)
	at f.a.b0.e.b.l$a.d(Unknown Source:2)
	at f.a.b0.e.b.j$a.run(Unknown Source:21)
	at f.a.r$a.run(Unknown Source:9)
	at f.a.b0.g.j.run(Unknown Source:13)
	at f.a.b0.g.j.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=false, dsConfigDirectory=null/, dsiConfigDirectory=null/, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, useJit=true, consoleType=DS, soundEnabled=true, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=AkiraX , message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romPath=/storage/raw//storage/emulated/0/Download/Pokemon Branco 2 (BR).nds, sramPath=/storage/raw/storage/emulated/0/Download/Pokemon Branco 2 (BR).sav)
```

**Comment by rafaelvcaetano** [comment]
Tenta colocar as ROMs numa pasta diferente, fora da pasta "Downloads". Não te esqueças de atualizar depois nas definições do emulador o caminho para a nova pasta.

**Comment by akirasilva** [comment]
Funcional obrigado.
Como eu consigo as baixar bios para colocar no melonds?

Em qui, 4 de mar de 2021 8:02 PM, Rafael Caetano <notifications@github.com>
escreveu:

**Comment by rafaelvcaetano** [comment]
Desde a última versão que já não é preciso BIOS para usar o emulador. Mas se ainda quiseres, terás que extrair os ficheiros de um sistema real.

**Comment by akirasilva** [comment]
Obrigado.

Em qui, 4 de mar de 2021 8:16 PM, Rafael Caetano <notifications@github.com>
escreveu:
