### ISSUE TITLE
Couldn't load the rom

### ISSUE THREAD

**Issue by ASGAMING009** [rafaelvcaetano/melonDS-android#141]
* **Device model:** SM-J400F
* **Android version:** Android API 29
* **melonDS version:** Beta 1.2.2

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$f: Failed to load ROM: NDS_FAILED
	at me.magnum.melonds.ui.emulator.j$e$a$a.a(Unknown Source:204)
	at f.a.b0.e.e.a.o(Unknown Source:10)
	at f.a.s.a(Unknown Source:14)
	at f.a.b0.e.b.e$a.d(Unknown Source:26)
	at f.a.b0.e.b.l$a.d(Unknown Source:2)
	at f.a.b0.e.b.j$a.run(Unknown Source:21)
	at f.a.r$a.run(Unknown Source:9)
	at f.a.b0.g.j.run(Unknown Source:13)
	at f.a.b0.g.j.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=false, dsConfigDirectory=null/, dsiConfigDirectory=null/, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, useJit=false, consoleType=DS, soundEnabled=true, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romPath=/storage/msf/341, sramPath=/storage/msf/341.sav)
```

**Comment by shabbirmahmud** [comment]
Without the custom bios no rom load either it is internal or external,download folder or outside the download folder.Only show a white screen.
Tested:Realme 5i, Redmi 5+

**Comment by ASGAMING009** [comment]
Thx

**Comment by shabbirmahmud** [comment]
Is your rom load when rom is outside the download folder or external storage without custom bios?

**Comment by shabbirmahmud** [comment]
> Is your rom load when rom is outside the download folder or external storage without custom bios?

Is it load with custom bios?

**Comment by shabbirmahmud** [comment]
Can you use the latest beta [v1.3.0](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.3.0) and open a new issue? The latest version does not fix the problem but includes additional info that will help to find the cause.
