### ISSUE TITLE
Hola

### ISSUE THREAD

**Issue by gallard42470** [rafaelvcaetano/melonDS-android#205]
* **Device model:** Hisense L675 PRO
* **Android version:** Android API 24
* **melonDS version:** Beta 1.3.0

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$f: Failed to load ROM: NDS_FAILED
	at me.magnum.melonds.ui.emulator.j$e$a$a.a()
	at f.a.b0.e.e.a.q()
	at f.a.s.a()
	at f.a.b0.e.b.e$a.d()
	at f.a.b0.e.b.l$a.d()
	at f.a.b0.e.b.j$a.run()
	at f.a.r$a.run()
	at f.a.b0.g.k.run()
	at f.a.b0.g.k.call()
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=false, dsConfigDirectory=null/, dsiConfigDirectory=null/, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, useJit=false, consoleType=DS, soundEnabled=true, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FMario%20Kart%20DS%20-%20MEGA%20DESCARGAS%20XD.zip, romUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FMario%20Kart%20DS%20-%20MEGA%20DESCARGAS%20XD.zip/document/primary%3ADownload%2FMario%20Kart%20DS%20-%20MEGA%20DESCARGAS%20XD.zip%00Mario%20Kart%20DS%20-%20MEGA%20DESCARGAS%20XD.nds, romPath=/storage/emulated/0/Download/Mario Kart DS - MEGA DESCARGAS XD.zipMario Kart DS - MEGA DESCARGAS XD.nds, sramPath=/storage/emulated/0/Download/Mario Kart DS - MEGA DESCARGAS XD.zipMario Kart DS - MEGA DESCARGAS XD.sav)
```

**Comment by rafaelvcaetano** [comment]
If your problem is not yet fixed, try the latest [Beta 1.4.0](https://github.com/rafaelvcaetano/melonDS-android/releases/latest) release. If the problem is not fixed, please open a new issue.
