### ISSUE TITLE
No deja entrar a los roms 

### ISSUE THREAD

**Issue by samuel12733** [rafaelvcaetano/melonDS-android#206]
* **Device model:** LG-X170g
* **Android version:** Android API 21
* **melonDS version:** Beta 1.3.0

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$f: Failed to load ROM: NDS_FAILED
	at me.magnum.melonds.ui.emulator.j$e$a$a.a()
	at f.a.b0.e.e.a.q()
	at f.a.s.a()
	at f.a.b0.e.b.e$a.d()
	at f.a.b0.e.b.l$a.d()
	at f.a.b0.e.b.j$a.run()
	at f.a.r$a.run()
	at f.a.b0.g.k.run()
	at f.a.b0.g.k.call()
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=true, dsConfigDirectory=/storage/sdcard1/melonds/Bios Melonds/, dsiConfigDirectory=/storage/sdcard1/melonds/Bios Melonds/, internalDirectory=/data/data/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, useJit=false, consoleType=DS, soundEnabled=true, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Samuel, message=Hello!, language=5, favouriteColour=2, birthdayMonth=6, birthdayDay=11), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.externalstorage.documents/tree/6DA7-1B07%3Aroms%2FNDS, romUri=content://com.android.externalstorage.documents/tree/6DA7-1B07%3Aroms%2FNDS/document/6DA7-1B07%3Aroms%2FNDS%2F1492%20-%20Donkey%20Kong%20-%20Jungle%20Climber%20(Europe)%20(En%2CFr%2CDe%2CEs%2CIt).nds, romPath=/storage/6DA7-1B07/roms/NDS/1492 - Donkey Kong - Jungle Climber (Europe) (En,Fr,De,Es,It).nds, sramPath=/storage/6DA7-1B07/roms/NDS/1492 - Donkey Kong - Jungle Climber (Europe) (En,Fr,De,Es,It).sav)
```

**Comment by rafaelvcaetano** [comment]
Does it work if you disable the "Custom BIOS and firmware" option?

**Comment by rafaelvcaetano** [comment]
Closed due to lack of feedback.
