### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by zhantty** [rafaelvcaetano/melonDS-android#210]
* **Device model:** T702
* **Android version:** Android API 22

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
java.lang.SecurityException: Permission Denial: reading com.android.externalstorage.ExternalStorageProvider uri content://com.android.externalstorage.documents/tree/4258-19F8%3ADownload%2Froms/document/4258-19F8%3ADownload%2Froms%2FMario%20Kart%20DS%20%5BNDS%5D%20%5BRoms%20Nintendo%20en%20Espa%C3%B1ol%5D.nds from pid=20983, uid=10092 requires android.permission.MANAGE_DOCUMENTS, or grantUriPermission()
	at android.os.Parcel.readException(Parcel.java:1547)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:691)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1116)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:937)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:662)
	at me.magnum.melonds.q.i.e()
	at me.magnum.melonds.ui.emulator.j$e.a()
	at f.a.b0.e.b.c.m()
	at f.a.h.a()
	at f.a.b0.e.b.k$b.run()
	at f.a.x.b.b$b.run()
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5637)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

```

**Comment by rafaelvcaetano** [comment]
Not sure what could have gone wrong here. I will suggest a clean install, preferably using the latest [Beta 1.4.0](https://github.com/rafaelvcaetano/melonDS-android/releases/latest) release.

**Comment by rafaelvcaetano** [comment]
Closed due to lack of feedback.
