### ISSUE TITLE
Bug Report - System Crash

### ISSUE THREAD

**Issue by Varrbaj** [rafaelvcaetano/melonDS-android#235]
* **Device model:** Redmi Note 5A
* **Android version:** Android API 25
* **melonDS version:** Beta 1.3.0

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$f: Failed to load ROM: NDS_FAILED
	at me.magnum.melonds.ui.emulator.j$e$a$a.a()
	at f.a.b0.e.e.a.q()
	at f.a.s.a()
	at f.a.b0.e.b.e$a.d()
	at f.a.b0.e.b.l$a.d()
	at f.a.b0.e.b.j$a.run()
	at f.a.r$a.run()
	at f.a.b0.g.k.run()
	at f.a.b0.g.k.call()
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:760)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=true, dsConfigDirectory=/storage/emulated/0/Bios/NDS/, dsiConfigDirectory=/storage/emulated/0/Bios/DSi/, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, useJit=true, consoleType=DS, soundEnabled=true, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Arba, message=WAZZUP MAN, language=1, favouriteColour=13, birthdayMonth=11, birthdayDay=11), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.externalstorage.documents/tree/home%3A, romUri=content://com.android.externalstorage.documents/tree/home%3A/document/home%3A3541%20-%20Pokemon%20Platinum%20Version%20(US)(XenoPhobia).nds, romPath=/storage/home/3541 - Pokemon Platinum Version (US)(XenoPhobia).nds, sramPath=/storage/home/3541 - Pokemon Platinum Version (US)(XenoPhobia).sav)
```

**Comment by rafaelvcaetano** [comment]
Try the latest [Beta 1.4.0](https://github.com/rafaelvcaetano/melonDS-android/releases/latest) release. If the problem is not fixed, please open a new issue.
