### ISSUE TITLE
The Legend of Zelda: Phantom Hourglass e The Legend of Zelda: Spirit Tracks não rodam

### ISSUE THREAD

**Issue by Danilo2505** [rafaelvcaetano/melonDS-android#236]
* **Device model:** SM-A530F
* **Android version:** Android API 26
* **melonDS version:** Beta 1.3.0

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$f: Failed to load ROM: NDS_FAILED
	at me.magnum.melonds.ui.emulator.j$e$a$a.a(Unknown Source:204)
	at f.a.b0.e.e.a.q(Unknown Source:10)
	at f.a.s.a(Unknown Source:14)
	at f.a.b0.e.b.e$a.d(Unknown Source:26)
	at f.a.b0.e.b.l$a.d(Unknown Source:2)
	at f.a.b0.e.b.j$a.run(Unknown Source:21)
	at f.a.r$a.run(Unknown Source:9)
	at f.a.b0.g.k.run(Unknown Source:13)
	at f.a.b0.g.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=false, dsConfigDirectory=null/, dsiConfigDirectory=null/, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, useJit=true, consoleType=DS, soundEnabled=true, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Danilo, message=Hello!, language=1, favouriteColour=10, birthdayMonth=5, birthdayDay=25), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.externalstorage.documents/tree/primary%3AJogos%20e%20emuladores%2FNintendo%2FJogos%20NDS, romUri=content://com.android.externalstorage.documents/tree/primary%3AJogos%20e%20emuladores%2FNintendo%2FJogos%20NDS/document/primary%3AJogos%20e%20emuladores%2FNintendo%2FJogos%20NDS%2FThe%20Legend%20of%20Zelda%3A%20Phantom%20Hourglass%2FThe%20Legend%20of%20Zelda%3A%20Phantom%20Hourglass%20(USA).nds, romPath=/storage/emulated/0/Jogos e emuladores/Nintendo/Jogos NDS/The Legend of Zelda, sramPath=/storage/emulated/0/Jogos e emuladores/Nintendo/Jogos NDS/The Legend of Zelda.sav)
```
Prints:

Print do erro, que aparece quando eu tento iniciar uma das duas ROMs:

![Screenshot_20210322-213521_melonDS](https://user-images.githubusercontent.com/77727610/112076916-1aed2a00-8b5a-11eb-82a0-6fb87399a317.jpg)

Print das minhas ROMs,todas iniciando e rodando normalmente menos as ROMs de The Legend of Zelda:

![Screenshot_20210322-214342_melonDS](https://user-images.githubusercontent.com/77727610/112076922-1cb6ed80-8b5a-11eb-8719-b522b3bb4030.jpg)

Bom espero que este erro seja resolvido.

**Comment by rafaelvcaetano** [comment]
Não sei como é possível, mas o carácter ":" não deveria aparecer no nome do ficheiro. Altera os nomes dos ficheiros desses dois jogos e remove esse carácter em ambos.

**Comment by Danilo2505** [comment]
Obrigado, funcionou.
