### ISSUE TITLE
LG k40s melonDS dsi not work

### ISSUE THREAD

**Issue by Brasil150** [rafaelvcaetano/melonDS-android#246]
* **Device model:** LM-X430
* **Android version:** Android API 29
* **melonDS version:** Beta 1.3.0

**Problem:**  
MelonDS not start emulator.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$d: Failed to load firmware: BIOS9_MISSING
	at me.magnum.melonds.ui.emulator.h$c.a(Unknown Source:67)
	at f.a.b0.e.a.a.g(Unknown Source:10)
	at f.a.a.a(Unknown Source:14)
	at f.a.b0.e.a.e$a.run(Unknown Source:2)
	at f.a.r$a.run(Unknown Source:9)
	at f.a.b0.g.k.run(Unknown Source:13)
	at f.a.b0.g.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```

**Configuration:**  
```
FirmwareCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=true, dsConfigDirectory=null/, dsiConfigDirectory=/storage/emulated/0/melonds/, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, useJit=false, consoleType=DSi, soundEnabled=true, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), dsiBiosDirUri=null, dsBiosDirUri=content://com.android.externalstorage.documents/tree/primary%3Amelonds)
```

**Comment by rafaelvcaetano** [comment]
DSi requires both the DS and DSi BIOS directories to be set. I see that you haven't configured DS BIOS directory. I know the UI doesn't enforce that but it's something I'm working on.

**Comment by Brasil150** [comment]
> DSi requires both the DS and DSi BIOS directories to be set. I see that you haven't configured DS BIOS directory. I know the UI doesn't enforce that but it's something I'm working on.

Sorry. Already work! But Fps is very low :/

**Comment by rafaelvcaetano** [comment]
Unfortunately, there's nothing that can be done to solve that. Futher performance improvements should come eventually.
