### ISSUE TITLE
🤔

### ISSUE THREAD

**Issue by xXMatteosXx8332** [rafaelvcaetano/melonDS-android#291]
* **Device model:** G3313
* **Android version:** Android API 24
* **melonDS version:** Beta 1.3.0

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$f: Failed to load ROM: NDS_FAILED
	at me.magnum.melonds.ui.emulator.j$e$a$a.a()
	at f.a.b0.e.e.a.q()
	at f.a.s.a()
	at f.a.b0.e.b.e$a.d()
	at f.a.b0.e.b.l$a.d()
	at f.a.b0.e.b.j$a.run()
	at f.a.r$a.run()
	at f.a.b0.g.k.run()
	at f.a.b0.g.k.call()
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=false, dsConfigDirectory=null/, dsiConfigDirectory=null/, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, useJit=true, consoleType=DS, soundEnabled=true, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FPlants%20vs.%20Zombies%20(USA).zip, romUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FPlants%20vs.%20Zombies%20(USA).zip/document/primary%3ADownload%2FPlants%20vs.%20Zombies%20(USA).zip%005496%20-%20Plants%20vs.%20Zombies%20(USA).nds, romPath=/storage/emulated/0/Download/Plants vs. Zombies (USA).zip5496 - Plants vs. Zombies (USA).nds, sramPath=/storage/emulated/0/Download/Plants vs. Zombies (USA).zip5496 - Plants vs. Zombies (USA).sav)
```

**Comment by rafaelvcaetano** [comment]
This problem has been fixed in the [Beta 1.4.0](https://github.com/rafaelvcaetano/melonDS-android/releases/latest) release. However, if you still encounter this problem, feel free to open a new issue.
