### ISSUE TITLE
help?

### ISSUE THREAD

**Issue by jhznXx** [rafaelvcaetano/melonDS-android#309]
* **Device model:** moto g(8) play
* **Android version:** Android API 29
* **melonDS version:** Beta 1.5.0

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.n.b: Could not create temporary SRAM file at content://com.android.providers.downloads.documents/tree/msd%3A313824/document/msf%3A
	at me.magnum.melonds.ui.emulator.EmulatorViewModel.B(Unknown Source:128)
	at me.magnum.melonds.ui.emulator.k$e$a$a.a(Unknown Source:86)
	at f.a.c0.e.e.a.q(Unknown Source:10)
	at f.a.t.a(Unknown Source:14)
	at f.a.c0.e.b.e$a.d(Unknown Source:26)
	at f.a.c0.e.b.m$a.d(Unknown Source:2)
	at f.a.c0.e.b.k$a.run(Unknown Source:21)
	at f.a.s$a.run(Unknown Source:9)
	at f.a.c0.g.k.run(Unknown Source:13)
	at f.a.c0.g.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=false, showBootScreen=false, dsBios7Uri=null, dsBios9Uri=null, dsFirmwareUri=null, dsiBios7Uri=null, dsiBios9Uri=null, dsiFirmwareUri=null, dsiNandUri=null, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, useJit=false, consoleType=DS, soundEnabled=true, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1, randomizeMacAddress=false, internalMacAddress=00:09:BF:4F:A4:A0), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.providers.downloads.documents/tree/msd%3A313824, romUri=content://com.android.providers.downloads.documents/tree/msd%3A313824/document/msf%3A313825, sramUri=null)
```

**Comment by rafaelvcaetano** [comment]
Please try the [Beta 1.5.2](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.5.2) where this problem was addressed. If you still encounter errors after updating, please open a new issue.
