### ISSUE TITLE
No me deja jugar 

### ISSUE THREAD

**Issue by nobisue** [rafaelvcaetano/melonDS-android#315]
* **Device model:** VOTO V2i
* **Android version:** Android API 24
* **melonDS version:** Beta 1.5.0

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.n.b: Could not create temporary SRAM file at content://com.android.externalstorage.documents/tree/primary%3ADownload%2FNew%20Super%20Mario%20Bros.%20(Japan).zip/document/primary%3ADownload
	at me.magnum.melonds.ui.emulator.EmulatorViewModel.B()
	at me.magnum.melonds.ui.emulator.k$e$a$a.a()
	at f.a.c0.e.e.a.q()
	at f.a.t.a()
	at f.a.c0.e.b.e$a.d()
	at f.a.c0.e.b.m$a.d()
	at f.a.c0.e.b.k$a.run()
	at f.a.s$a.run()
	at f.a.c0.g.k.run()
	at f.a.c0.g.k.call()
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=false, showBootScreen=false, dsBios7Uri=null, dsBios9Uri=null, dsFirmwareUri=null, dsiBios7Uri=null, dsiBios9Uri=null, dsiFirmwareUri=null, dsiNandUri=null, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, useJit=false, consoleType=DS, soundEnabled=true, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1, randomizeMacAddress=false, internalMacAddress=00:09:BF:04:67:51), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FNew%20Super%20Mario%20Bros.%20(Japan).zip, romUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FNew%20Super%20Mario%20Bros.%20(Japan).zip/document/primary%3ADownload%2FNew%20Super%20Mario%20Bros.%20(Japan).zip%000442%20-%20New%20Super%20Mario%20Bros.%20(Japan).nds, sramUri=null)
```

**Comment by Flamehere** [comment]
https://youtu.be/qwNMPixMusA

**Comment by Flamehere** [comment]
Intenta eso

**Comment by rafaelvcaetano** [comment]
Please try the [Beta 1.5.2](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.5.2) where this problem was addressed. If you still encounter errors after updating, please open a new issue.
