### ISSUE TITLE
Vbb

### ISSUE THREAD

**Issue by roblox78** [rafaelvcaetano/melonDS-android#316]
* **Device model:** Lenovo TB-X505L
* **Android version:** Android API 29

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
java.lang.IllegalStateException: java.io.FileNotFoundException: No item at content://media/external/downloads/26884
	at android.os.Parcel.createException(Parcel.java:2079)
	at android.os.Parcel.readException(Parcel.java:2039)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:705)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1689)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1505)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1189)
	at me.magnum.melonds.q.i.e(Unknown Source:9)
	at me.magnum.melonds.ui.emulator.j$e.a(Unknown Source:17)
	at f.a.b0.e.b.c.m(Unknown Source:10)
	at f.a.h.a(Unknown Source:14)
	at f.a.b0.e.b.k$b.run(Unknown Source:4)
	at f.a.x.b.b$b.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7559)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

```

**Comment by roblox78** [comment]
I voti a problém to play my se game.

**Comment by rafaelvcaetano** [comment]
Could you try the [Beta 1.5.0](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.5.0) release? If the problem is not fixed, please open a new issue.
