### ISSUE TITLE
No carga el rom

### ISSUE THREAD

**Issue by monoshe** [rafaelvcaetano/melonDS-android#322]
* **Device model:** SM-A107M
* **Android version:** Android API 29
* **melonDS version:** Beta 1.5.0

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.n.b: Could not create temporary SRAM file at content://com.android.providers.downloads.documents/tree/msd%3A33333/document/msf%3A
	at me.magnum.melonds.ui.emulator.EmulatorViewModel.B(Unknown Source:128)
	at me.magnum.melonds.ui.emulator.k$e$a$a.a(Unknown Source:86)
	at f.a.c0.e.e.a.q(Unknown Source:10)
	at f.a.t.a(Unknown Source:14)
	at f.a.c0.e.b.e$a.d(Unknown Source:26)
	at f.a.c0.e.b.m$a.d(Unknown Source:2)
	at f.a.c0.e.b.k$a.run(Unknown Source:21)
	at f.a.s$a.run(Unknown Source:9)
	at f.a.c0.g.k.run(Unknown Source:13)
	at f.a.c0.g.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=true, showBootScreen=true, dsBios7Uri=content://com.android.providers.downloads.documents/tree/msd%3A33309/document/msf%3A33310, dsBios9Uri=content://com.android.providers.downloads.documents/tree/msd%3A33309/document/msf%3A33311, dsFirmwareUri=content://com.android.providers.downloads.documents/tree/msd%3A33309/document/msf%3A33312, dsiBios7Uri=content://com.android.providers.downloads.documents/tree/msd%3A33314/document/msf%3A33315, dsiBios9Uri=content://com.android.providers.downloads.documents/tree/msd%3A33314/document/msf%3A33316, dsiFirmwareUri=content://com.android.providers.downloads.documents/tree/msd%3A33314/document/msf%3A33317, dsiNandUri=content://com.android.providers.downloads.documents/tree/msd%3A33314/document/msf%3A33319, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, useJit=false, consoleType=DS, soundEnabled=true, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1, randomizeMacAddress=true, internalMacAddress=null), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.providers.downloads.documents/tree/msd%3A33333, romUri=content://com.android.providers.downloads.documents/tree/msd%3A33333/document/msf%3A33334, sramUri=null)
```

**Comment by Flamehere** [comment]
https://youtu.be/qwNMPixMusA

**Comment by rafaelvcaetano** [comment]
Please try the [Beta 1.5.2](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.5.2) where this problem was addressed. If you still encounter errors after updating, please open a new issue.
