### ISSUE TITLE
Xd. WTF i need to play My roms this **** emulator says github account

### ISSUE THREAD

**Issue by dakki71** [rafaelvcaetano/melonDS-android#324]
* **Device model:** moto g(7) power
* **Android version:** Android API 29
* **melonDS version:** Beta 1.5.0

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.n.b: Could not create temporary SRAM file at content://com.android.providers.downloads.documents/tree/downloads/document/msf%3A
	at me.magnum.melonds.ui.emulator.EmulatorViewModel.B(Unknown Source:128)
	at me.magnum.melonds.ui.emulator.k$e$a$a.a(Unknown Source:86)
	at f.a.c0.e.e.a.q(Unknown Source:10)
	at f.a.t.a(Unknown Source:14)
	at f.a.c0.e.b.e$a.d(Unknown Source:26)
	at f.a.c0.e.b.m$a.d(Unknown Source:2)
	at f.a.c0.e.b.k$a.run(Unknown Source:21)
	at f.a.s$a.run(Unknown Source:9)
	at f.a.c0.g.k.run(Unknown Source:13)
	at f.a.c0.g.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=true, showBootScreen=false, dsBios7Uri=content://com.android.providers.downloads.documents/tree/msd%3A274/document/msf%3A275, dsBios9Uri=content://com.android.providers.downloads.documents/tree/msd%3A274/document/msf%3A276, dsFirmwareUri=content://com.android.providers.downloads.documents/tree/msd%3A274/document/msf%3A277, dsiBios7Uri=content://com.android.providers.downloads.documents/tree/msd%3A279/document/msf%3A280, dsiBios9Uri=content://com.android.providers.downloads.documents/tree/msd%3A279/document/msf%3A281, dsiFirmwareUri=content://com.android.providers.downloads.documents/tree/msd%3A279/document/msf%3A282, dsiNandUri=content://com.android.providers.downloads.documents/tree/msd%3A279/document/msf%3A284, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, useJit=true, consoleType=DSi, soundEnabled=true, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=4, birthdayMonth=1, birthdayDay=1, randomizeMacAddress=false, internalMacAddress=null), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.providers.downloads.documents/tree/downloads, romUri=content://com.android.providers.downloads.documents/tree/downloads/document/msf%3A298, sramUri=null)
```

**Comment by rafaelvcaetano** [comment]
Someone's mad!

Could you give me a screenshot of your file explorer, in the directory where you placed your ROMs? You can upload images to GitHub comments.

**Comment by dakki71** [comment]
Ty. I already uninstall melonds and use drastic xd. sorry for wasting your time. The problem was something like "could not load rooms. Create an account on github for fix".

**Comment by Arisotura** [comment]
Xd. WTF i need to learn My english this shit language says nonsense

**Comment by dakki71** [comment]
I'm a sadly peruvian using the traductor. My English is very badd

**Comment by Arisotura** [comment]
yet your usage of a traductor conveyed very well the fact you are an entitled brat

**Comment by rafaelvcaetano** [comment]
If you are still interested, please try the [Beta 1.5.2](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.5.2) where this problem was addressed. If you still encounter errors after updating, please open a new issue.

**Comment by dakki71** [comment]
Ty
