### ISSUE TITLE
Doesn't load ROMs

### ISSUE THREAD

**Issue by Crisg13206** [rafaelvcaetano/melonDS-android#353]
* **Device model:** M2006C3LG
* **Android version:** Android API 29
* **melonDS version:** Beta 1.5.1

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.n.b: Could not create temporary SRAM file at content://com.android.externalstorage.documents/tree/primary%3ADownload/document/primary%3ADownload
	at me.magnum.melonds.ui.emulator.EmulatorViewModel.B(Unknown Source:128)
	at me.magnum.melonds.ui.emulator.k$d$a$a.a(Unknown Source:86)
	at f.a.c0.e.e.a.q(Unknown Source:10)
	at f.a.t.a(Unknown Source:14)
	at f.a.c0.e.b.e$a.d(Unknown Source:26)
	at f.a.c0.e.b.m$a.d(Unknown Source:2)
	at f.a.c0.e.b.k$a.run(Unknown Source:21)
	at f.a.s$a.run(Unknown Source:9)
	at f.a.c0.g.k.run(Unknown Source:13)
	at f.a.c0.g.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=false, showBootScreen=false, dsBios7Uri=null, dsBios9Uri=null, dsFirmwareUri=null, dsiBios7Uri=null, dsiBios9Uri=null, dsiFirmwareUri=null, dsiNandUri=null, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, useJit=false, consoleType=DS, soundEnabled=true, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1, randomizeMacAddress=false, internalMacAddress=00:09:BF:00:54:F7), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.externalstorage.documents/tree/primary%3ADownload, romUri=content://com.android.externalstorage.documents/tree/primary%3ADownload/document/primary%3ADownload%2FPhoenix%20Wright%20-%20Ace%20Attorney%20(Europe)%20(De%2CEs%2CIt).zip, sramUri=content://com.android.externalstorage.documents/tree/primary%3ADownload/document/primary%3ADownload%2FPhoenix%20Wright%20-%20Ace%20Attorney%20(Europe)%20(De%2CEs%2CIt).sav)
```

**Comment by rafaelvcaetano** [comment]
Please try the [Beta 1.5.2](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.5.2) where this problem was addressed. If you still encounter errors after updating, please open a new issue.

**Comment by Crisg13206** [comment]
Hello, I have downloaded the new version and the ROMs are loaded but it has
lag. I have downloaded another emulator to test if it is my device but it
is not my phone. I will download the emulator again when More developed

**Comment by Crisg13206** [comment]
Thank you
