### ISSUE TITLE
The room doesn't open

### ISSUE THREAD

**Issue by AstaG7** [rafaelvcaetano/melonDS-android#379]
* **Device model:** LM-X410.F
* **Android version:** Android API 25
* **melonDS version:** Beta 1.5.2

**Problem:**  
My room doesn't `open`

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.n.c: Could not create temporary SRAM file at content://com.android.externalstorage.documents/tree/72B3-1EF5%3A5584%20-%20Pokemon%20-%20White%20Version%20(DSi%20Enhanced)(USA)%20(E)-2.zip/document/72B3-1EF5%3A5584%20-%20Pokemon%20-%20White%20Version%20(DSi%20Enhanced)(USA)%20(E)-2.zip
	at me.magnum.melonds.ui.emulator.EmulatorViewModel.B()
	at me.magnum.melonds.ui.emulator.k$e$a$a.a()
	at f.a.c0.e.e.a.s()
	at f.a.t.a()
	at f.a.c0.e.b.e$a.d()
	at f.a.c0.e.b.m$a.d()
	at f.a.c0.e.b.k$a.run()
	at f.a.s$a.run()
	at f.a.c0.g.k.run()
	at f.a.c0.g.k.call()
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=false, showBootScreen=false, dsBios7Uri=null, dsBios9Uri=null, dsFirmwareUri=null, dsiBios7Uri=null, dsiBios9Uri=null, dsiFirmwareUri=null, dsiNandUri=null, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, useJit=false, consoleType=DS, soundEnabled=true, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1, randomizeMacAddress=false, internalMacAddress=00:09:BF:D2:0E:D1), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.externalstorage.documents/tree/72B3-1EF5%3A5584%20-%20Pokemon%20-%20White%20Version%20(DSi%20Enhanced)(USA)%20(E)-2.zip, romUri=content://com.android.externalstorage.documents/tree/72B3-1EF5%3A5584%20-%20Pokemon%20-%20White%20Version%20(DSi%20Enhanced)(USA)%20(E)-2.zip/document/72B3-1EF5%3A5584%20-%20Pokemon%20-%20White%20Version%20(DSi%20Enhanced)(USA)%20(E)-2.zip%005584%20-%20Pokemon%20-%20White%20Version%20(DSi%20Enhanced)(USA)%20(E)(SweeTnDs).nds, sramUri=null)
```

**Comment by rafaelvcaetano** [comment]
Could you give me a screenshot of your file explorer showing the folder where you placed your ROMs?

**Comment by AstaG7** [comment]
I was able to open it, I didn't know that the emulator didn't emulate
.zip or .7z roms. I humbly apologize for the inconvenience.


[image: Ícone "Verificada pela comunidade"]

Em Qui, 27 de mai de 2021 11:26, Rafael Caetano ***@***.***>
escreveu:
