### ISSUE TITLE
My Problem with MelonNDS

### ISSUE THREAD

**Issue by penguinyoutuber** [rafaelvcaetano/melonDS-android#386]
* **Device model:** Moto C Plus
* **Android version:** Android API 24
* **melonDS version:** Beta 1.3.0

**Problem:**  
I no can play my games, he says to me make
A account in github, i created now but hE KEEPS ASKING!!!!
HELP ### ME

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$f: Failed to load ROM: NDS_FAILED
	at me.magnum.melonds.ui.emulator.j$e$a$a.a()
	at f.a.b0.e.e.a.q()
	at f.a.s.a()
	at f.a.b0.e.b.e$a.d()
	at f.a.b0.e.b.l$a.d()
	at f.a.b0.e.b.j$a.run()
	at f.a.r$a.run()
	at f.a.b0.g.k.run()
	at f.a.b0.g.k.call()
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=false, dsConfigDirectory=null/, dsiConfigDirectory=null/, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, useJit=false, consoleType=DS, soundEnabled=true, micSource=NONE, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FBust-A-Move%20DS.zip, romUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FBust-A-Move%20DS.zip/document/primary%3ADownload%2FBust-A-Move%20DS.zip%00Bust-A-Move%20DS.nds, romPath=/storage/emulated/0/Download/Bust-A-Move DS.zipBust-A-Move DS.nds, sramPath=/storage/emulated/0/Download/Bust-A-Move DS.zipBust-A-Move DS.sav)
```

**Comment by rafaelvcaetano** [comment]
Please try the [Beta 1.5.2](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.5.2) where this problem was addressed. If you still encounter errors after updating, please open a new issue.
