### ISSUE TITLE
Final fantasy

### ISSUE THREAD

**Issue by niki44353** [rafaelvcaetano/melonDS-android#388]
* **Device model:** LM-X210
* **Android version:** Android API 25
* **melonDS version:** Beta 1.5.2

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.n.c: Could not create temporary SRAM file at content://com.android.externalstorage.documents/tree/primary%3ADownload%2FFinal%20Fantasy%20IV%20(Europe)%20(En%2CFr%2CDe%2CEs%2CIt).zip/document/primary%3ADownload%2FFinal%20Fantasy%20IV%20(Europe)%20(En%2CFr%2CDe%2CEs%2CIt).zip
	at me.magnum.melonds.ui.emulator.EmulatorViewModel.B()
	at me.magnum.melonds.ui.emulator.k$e$a$a.a()
	at f.a.c0.e.e.a.s()
	at f.a.t.a()
	at f.a.c0.e.b.e$a.d()
	at f.a.c0.e.b.m$a.d()
	at f.a.c0.e.b.k$a.run()
	at f.a.s$a.run()
	at f.a.c0.g.k.run()
	at f.a.c0.g.k.call()
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=false, showBootScreen=false, dsBios7Uri=null, dsBios9Uri=null, dsFirmwareUri=null, dsiBios7Uri=null, dsiBios9Uri=null, dsiFirmwareUri=null, dsiNandUri=null, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, useJit=false, consoleType=DS, soundEnabled=true, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=niki44353, message=oi, language=1, favouriteColour=0, birthdayMonth=3, birthdayDay=24, randomizeMacAddress=false, internalMacAddress=00:09:BF:82:35:6C), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FFinal%20Fantasy%20IV%20(Europe)%20(En%2CFr%2CDe%2CEs%2CIt).zip, romUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FFinal%20Fantasy%20IV%20(Europe)%20(En%2CFr%2CDe%2CEs%2CIt).zip/document/primary%3ADownload%2FFinal%20Fantasy%20IV%20(Europe)%20(En%2CFr%2CDe%2CEs%2CIt).zip%002623%20-%20Final%20Fantasy%20IV%20(Europe)%20(En%2CFr%2CDe%2CEs%2CIt).nds, sramUri=null)
```

**Comment by rafaelvcaetano** [comment]
Did you extract the ROM? Or did you select the zipped file as the ROM search directory?
