### ISSUE TITLE
Ayuda/ help me

### ISSUE THREAD

**Issue by Towboy483** [rafaelvcaetano/melonDS-android#432]
* **Device model:** LG-M250
* **Android version:** Android API 24
* **melonDS version:** Beta 1.5.0

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.n.b: Could not create temporary SRAM file at content://com.android.externalstorage.documents/tree/385F-1BE8%3ARoms/document/385F-1BE8%3ARoms%2FJump!%20Ultimate%20Stars%20%5BNDS%5D%20%5BRoms%20Nintendo%20en%20Espa%C3%B1ol%5D
	at me.magnum.melonds.ui.emulator.EmulatorViewModel.B()
	at me.magnum.melonds.ui.emulator.k$e$a$a.a()
	at f.a.c0.e.e.a.q()
	at f.a.t.a()
	at f.a.c0.e.b.e$a.d()
	at f.a.c0.e.b.m$a.d()
	at f.a.c0.e.b.k$a.run()
	at f.a.s$a.run()
	at f.a.c0.g.k.run()
	at f.a.c0.g.k.call()
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=true, showBootScreen=false, dsBios7Uri=content://com.android.externalstorage.documents/tree/385F-1BE8%3AmelonDS-beta%20APK%20-%20v1.5.0%2FmelonDS-beta%20APK%20-%20v1.5.0%2FBios%20Melonds%2FBios%20NDS/document/385F-1BE8%3AmelonDS-beta%20APK%20-%20v1.5.0%2FmelonDS-beta%20APK%20-%20v1.5.0%2FBios%20Melonds%2FBios%20NDS%2Fbios7.bin, dsBios9Uri=content://com.android.externalstorage.documents/tree/385F-1BE8%3AmelonDS-beta%20APK%20-%20v1.5.0%2FmelonDS-beta%20APK%20-%20v1.5.0%2FBios%20Melonds%2FBios%20NDS/document/385F-1BE8%3AmelonDS-beta%20APK%20-%20v1.5.0%2FmelonDS-beta%20APK%20-%20v1.5.0%2FBios%20Melonds%2FBios%20NDS%2Fbios9.bin, dsFirmwareUri=content://com.android.externalstorage.documents/tree/385F-1BE8%3AmelonDS-beta%20APK%20-%20v1.5.0%2FmelonDS-beta%20APK%20-%20v1.5.0%2FBios%20Melonds%2FBios%20NDS/document/385F-1BE8%3AmelonDS-beta%20APK%20-%20v1.5.0%2FmelonDS-beta%20APK%20-%20v1.5.0%2FBios%20Melonds%2FBios%20NDS%2Ffirmware.bin, dsiBios7Uri=content://com.android.externalstorage.documents/tree/385F-1BE8%3AmelonDS-beta%20APK%20-%20v1.5.0%2FmelonDS-beta%20APK%20-%20v1.5.0%2FBios%20Melonds%2FBios%20NDSi/document/385F-1BE8%3AmelonDS-beta%20APK%20-%20v1.5.0%2FmelonDS-beta%20APK%20-%20v1.5.0%2FBios%20Melonds%2FBios%20NDSi%2Fbios7.bin, dsiBios9Uri=content://com.android.externalstorage.documents/tree/385F-1BE8%3AmelonDS-beta%20APK%20-%20v1.5.0%2FmelonDS-beta%20APK%20-%20v1.5.0%2FBios%20Melonds%2FBios%20NDSi/document/385F-1BE8%3AmelonDS-beta%20APK%20-%20v1.5.0%2FmelonDS-beta%20APK%20-%20v1.5.0%2FBios%20Melonds%2FBios%20NDSi%2Fbios9.bin, dsiFirmwareUri=content://com.android.externalstorage.documents/tree/385F-1BE8%3AmelonDS-beta%20APK%20-%20v1.5.0%2FmelonDS-beta%20APK%20-%20v1.5.0%2FBios%20Melonds%2FBios%20NDSi/document/385F-1BE8%3AmelonDS-beta%20APK%20-%20v1.5.0%2FmelonDS-beta%20APK%20-%20v1.5.0%2FBios%20Melonds%2FBios%20NDSi%2Ffirmware.bin, dsiNandUri=content://com.android.externalstorage.documents/tree/385F-1BE8%3AmelonDS-beta%20APK%20-%20v1.5.0%2FmelonDS-beta%20APK%20-%20v1.5.0%2FBios%20Melonds%2FBios%20NDSi/document/385F-1BE8%3AmelonDS-beta%20APK%20-%20v1.5.0%2FmelonDS-beta%20APK%20-%20v1.5.0%2FBios%20Melonds%2FBios%20NDSi%2Fnand.bin, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, useJit=false, consoleType=DSi, soundEnabled=true, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1, randomizeMacAddress=false, internalMacAddress=null), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.externalstorage.documents/tree/385F-1BE8%3ARoms, romUri=content://com.android.externalstorage.documents/tree/385F-1BE8%3ARoms/document/385F-1BE8%3ARoms%2FJump!%20Ultimate%20Stars%20%5BNDS%5D%20%5BRoms%20Nintendo%20en%20Espa%C3%B1ol%5D%2FJump!%20Ultimate%20Stars%20%5BNDS%5D%20%5BRoms%20Nintendo%20en%20Espa%C3%B1ol%5D.nds, sramUri=null)
```

**Comment by Gamemulatorer** [comment]
https://github.com/rafaelvcaetano/melonDS-android/issues/419#issuecomment-859902049

**Comment by rafaelvcaetano** [comment]
Please try the [Beta 1.5.2](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.5.2) where this problem was addressed. If you still encounter errors after updating, please open a new issue.
