### ISSUE TITLE
Kpa

### ISSUE THREAD

**Issue by MARXCOSSKS** [rafaelvcaetano/melonDS-android#470]
* **Device model:** LG-M250
* **Android version:** Android API 24
* **melonDS version:** Beta 1.3.0

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$f: Failed to load ROM: NDS_FAILED
	at me.magnum.melonds.ui.emulator.j$e$a$a.a()
	at f.a.b0.e.e.a.q()
	at f.a.s.a()
	at f.a.b0.e.b.e$a.d()
	at f.a.b0.e.b.l$a.d()
	at f.a.b0.e.b.j$a.run()
	at f.a.r$a.run()
	at f.a.b0.g.k.run()
	at f.a.b0.g.k.call()
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=false, dsConfigDirectory=null/, dsiConfigDirectory=null/, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, useJit=false, consoleType=DS, soundEnabled=true, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FDragon%20Ball%20Kai%20Ultimate%20Butouden%20(English%20Patched).zip, romUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FDragon%20Ball%20Kai%20Ultimate%20Butouden%20(English%20Patched).zip/document/primary%3ADownload%2FDragon%20Ball%20Kai%20Ultimate%20Butouden%20(English%20Patched).zip%00Dragon%20Ball%20Kai%20Ultimate%20Butouden%20(English%20Patched).nds, romPath=/storage/emulated/0/Download/Dragon Ball Kai Ultimate Butouden (English Patched).zipDragon Ball Kai Ultimate Butouden (English Patched).nds, sramPath=/storage/emulated/0/Download/Dragon Ball Kai Ultimate Butouden (English Patched).zipDragon Ball Kai Ultimate Butouden (English Patched).sav)
```

**Comment by Gamemulatorer** [comment]
Please try the [Beta 1.5.2](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.5.2) where this problem was addressed. If you still encounter errors after updating, please open a new issue.



Please try the [Beta 1.5.2](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.5.2) where this problem was addressed. If you still encounter errors after updating, please open a new issue.
