### ISSUE TITLE
Cadê o gerente quero modo multiplayer 

### ISSUE THREAD

**Issue by Fabiogame1610** [rafaelvcaetano/melonDS-android#473]
* **Device model:** SM-A013M
* **Android version:** Android API 29
* **melonDS version:** Beta 1.3.0

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$d: Failed to load firmware: BIOS9_MISSING
	at me.magnum.melonds.ui.emulator.h$c.a(Unknown Source:67)
	at f.a.b0.e.a.a.g(Unknown Source:10)
	at f.a.a.a(Unknown Source:14)
	at f.a.b0.e.a.e$a.run(Unknown Source:2)
	at f.a.r$a.run(Unknown Source:9)
	at f.a.b0.g.k.run(Unknown Source:13)
	at f.a.b0.g.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```

**Configuration:**  
```
FirmwareCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=true, dsConfigDirectory=null/, dsiConfigDirectory=/storage/emulated/0/Download/Dsi/, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, useJit=false, consoleType=DSi, soundEnabled=true, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), dsiBiosDirUri=null, dsBiosDirUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FDsi)
```

**Comment by SombraShadow** [comment]
Ainda não tem modo multiplayer,porque ainda tá sendo desenvolvido e afinal,porque você está com uma versão antiga do emulador?

**Comment by rafaelvcaetano** [comment]
Tenta a versão [Beta 1.5.2](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.5.2) que deve resolver este problema. Se não resolver, abre um novo problema.

Em relação ao multiplayer, podes tentar algumas coisas mas não prometo nada. Podes ver o que alguns utilizadores fizeram para usar o multiplayer local [nesta discussão](https://github.com/rafaelvcaetano/melonDS-android/discussions/66) e o que tentaram também para multiplayer online [nesta discussão](https://github.com/rafaelvcaetano/melonDS-android/discussions/317).
