### ISSUE TITLE
Ok

### ISSUE THREAD

**Issue by KillerPam** [rafaelvcaetano/melonDS-android#498]
* **Device model:** Redmi 5A
* **Android version:** Android API 25
* **melonDS version:** Beta 1.5.2

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.n.c: Could not create temporary SRAM file at content://com.android.externalstorage.documents/tree/primary%3ADownload%2FPokemon%20HeartGold%20(U)(Xenophobia).zip/document/primary%3ADownload%2FPokemon%20HeartGold%20(U)(Xenophobia).zip
	at me.magnum.melonds.ui.emulator.EmulatorViewModel.B()
	at me.magnum.melonds.ui.emulator.k$e$a$a.a()
	at f.a.c0.e.e.a.s()
	at f.a.t.a()
	at f.a.c0.e.b.e$a.d()
	at f.a.c0.e.b.m$a.d()
	at f.a.c0.e.b.k$a.run()
	at f.a.s$a.run()
	at f.a.c0.g.k.run()
	at f.a.c0.g.k.call()
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:760)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=true, showBootScreen=false, dsBios7Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FDS%20Bios%20%26%20Firmware%2FDS/document/primary%3ADownload%2FDS%20Bios%20%26%20Firmware%2FDS%2Fbios7.bin, dsBios9Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FDS%20Bios%20%26%20Firmware%2FDS/document/primary%3ADownload%2FDS%20Bios%20%26%20Firmware%2FDS%2Fbios9.bin, dsFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FDS%20Bios%20%26%20Firmware%2FDS/document/primary%3ADownload%2FDS%20Bios%20%26%20Firmware%2FDS%2Ffirmware.bin, dsiBios7Uri=null, dsiBios9Uri=null, dsiFirmwareUri=null, dsiNandUri=null, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, useJit=true, consoleType=DS, soundEnabled=true, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1, randomizeMacAddress=false, internalMacAddress=null), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FPokemon%20HeartGold%20(U)(Xenophobia).zip, romUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FPokemon%20HeartGold%20(U)(Xenophobia).zip/document/primary%3ADownload%2FPokemon%20HeartGold%20(U)(Xenophobia).zip%004780%20-%20Pokemon%20HeartGold%20(U)(Xenophobia).nds, sramUri=null)
```

**Comment by XiaomiRedmi9** [comment]
What is your f**cking phone specifications???!!!

**Comment by rafaelvcaetano** [comment]
Please try the [Beta 1.5.2](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.5.2) where this problem was addressed. If you still encounter errors after updating, please open a new issue.

**Comment by rafaelvcaetano** [comment]
> What is your f**cking phone specifications???!!!

Please refrain from aggressive comments. The phone model is clearly stated in the issue.

**Comment by XiaomiRedmi9** [comment]
> > What is your f**cking phone specifications???!!!
> 
> Please refrain from aggressive comments. The phone model is clearly stated in the issue.

SORRY 🙏
