### ISSUE TITLE
Adrian

### ISSUE THREAD

**Issue by Adriancrdv11** [rafaelvcaetano/melonDS-android#544]
* **Device model:** moto g(7) play
* **Android version:** Android API 29

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$f: Failed to load ROM: NDS_FAILED
	at me.magnum.melonds.ui.emulator.j$c$a$a.a(Unknown Source:205)
	at f.a.b0.e.e.a.m(Unknown Source:10)
	at f.a.s.a(Unknown Source:14)
	at f.a.b0.e.b.e$a.d(Unknown Source:26)
	at f.a.b0.e.b.l$a.d(Unknown Source:2)
	at f.a.b0.e.b.j$a.run(Unknown Source:21)
	at f.a.r$a.run(Unknown Source:9)
	at f.a.b0.g.j.run(Unknown Source:13)
	at f.a.b0.g.j.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```

**Comment by Adriancrdv11** [comment]
Aa

**Comment by Adriancrdv11** [comment]
No entra a mi juego

**Comment by Adriancrdv11** [comment]
No sé

**Comment by shabbirmahmud** [comment]
@Adriancrdv11 Download from playstore.

**Comment by rafaelvcaetano** [comment]
Aquí está el link para Play Store: https://play.google.com/store/apps/details?id=me.magnum.melonds

Así deberás tener siempre la aplicación actualizada.
