### ISSUE TITLE
Hola

### ISSUE THREAD

**Issue by Jairo65543** [rafaelvcaetano/melonDS-android#595]
* **Device model:** Moto G Play
* **Android version:** Android API 25
* **melonDS version:** Beta 1.6.1 PS

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
g6.c: Could not create temporary SRAM file at content://com.android.externalstorage.documents/tree/primary%3ADownload%2FNew%20Super%20Mario%20Bros.%20(Europe)%20(En%2CFr%2CDe%2CEs%2CIt).zip/document/primary%3ADownload%2FNew%20Super%20Mario%20Bros.%20(Europe)%20(En%2CFr%2CDe%2CEs%2CIt).zip
	at me.magnum.melonds.ui.emulator.EmulatorViewModel.I()
	at me.magnum.melonds.ui.emulator.d1.I()
	at me.magnum.melonds.ui.emulator.d1.i()
	at me.magnum.melonds.ui.emulator.c1.a()
	at c4.a.v()
	at o3.t.b()
	at c4.f$a.c()
	at c4.p$b.c()
	at c4.p$c.c()
	at z3.m$a.c()
	at z3.j$a.run()
	at o3.s$a.run()
	at e4.k.run()
	at e4.k.call()
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=false, showBootScreen=false, dsBios7Uri=null, dsBios9Uri=null, dsFirmwareUri=null, dsiBios7Uri=null, dsiBios9Uri=null, dsiFirmwareUri=null, dsiNandUri=null, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, useJit=false, consoleType=DS, soundEnabled=true, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1, randomizeMacAddress=false, internalMacAddress=00:09:BF:C1:35:C0), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FNew%20Super%20Mario%20Bros.%20(Europe)%20(En%2CFr%2CDe%2CEs%2CIt).zip, romUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FNew%20Super%20Mario%20Bros.%20(Europe)%20(En%2CFr%2CDe%2CEs%2CIt).zip/document/primary%3ADownload%2FNew%20Super%20Mario%20Bros.%20(Europe)%20(En%2CFr%2CDe%2CEs%2CIt).zip%000479%20-%20New%20Super%20Mario%20Bros.%20(Europe)%20(En%2CFr%2CDe%2CEs%2CIt).nds, sramUri=null)
```

**Comment by rafaelvcaetano** [comment]
This should be fixed in the [Beta 1.7.0](https://github.com/rafaelvcaetano/melonDS-android/releases/latest) release. If it doesn't allow you to select the folder with the ROMs, try extracting them.
