### ISSUE TITLE
Can't load rom

### ISSUE THREAD

**Issue by Ankeraout** [rafaelvcaetano/melonDS-android#60]
* **Device model:** SM-A516B
* **Android version:** Android API 29

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$f: Failed to load ROM: NDS_FAILED
	at me.magnum.melonds.ui.emulator.j$c$a$a.a(Unknown Source:205)
	at f.a.b0.e.e.a.m(Unknown Source:10)
	at f.a.s.a(Unknown Source:14)
	at f.a.b0.e.b.e$a.d(Unknown Source:26)
	at f.a.b0.e.b.l$a.d(Unknown Source:2)
	at f.a.b0.e.b.j$a.run(Unknown Source:21)
	at f.a.r$a.run(Unknown Source:9)
	at f.a.b0.g.j.run(Unknown Source:13)
	at f.a.b0.g.j.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```

**Comment by rafaelvcaetano** [comment]
I think there's something wrong with either your ROM or BIOS. Could try booting the firmware without a ROM? To do this, from the ROM list screen perform these steps:

* Click the 3 dots button
* Click "Boot firmware"
* Click "DS"

If the problem persists, then open a new issue please. If you can boot into the firmware, they your ROM is broken.

**Comment by Ankeraout** [comment]
My ROM file was corrupt. After transferring the correct file again, the emulator is working fine.
