### ISSUE TITLE
Can't boot into firmware OR roms

### ISSUE THREAD

**Issue by peteelandroide** [rafaelvcaetano/melonDS-android#61]
* **Device model:** POCO F1
* **Android version:** Android API 29

**Problem:**  
Same as title, an error screen appears telling me to report on github.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$d: Failed to load firmware: BIOS9_MISSING
	at me.magnum.melonds.ui.emulator.h$b.a(Unknown Source:54)
	at f.a.b0.e.a.a.g(Unknown Source:10)
	at f.a.a.a(Unknown Source:14)
	at f.a.b0.e.a.e$a.run(Unknown Source:2)
	at f.a.r$a.run(Unknown Source:9)
	at f.a.b0.g.j.run(Unknown Source:13)
	at f.a.b0.g.j.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```

**Comment by rafaelvcaetano** [comment]
Could you check if the Storage permission is granted? You can see this from the app's info screen by following these steps:

1. Open the device's Settings
2. Go to Apps
3. Find and select "melonDS"
4. Click on Permissions
5. Check if the Storage permission is enabled

If the permission is enabled, then it's possible that you have an invalid BIOS file. If the permission is disabled, try enabling it and try again. If it was disabled, let me know since that shouldn't happen.

Could you also let me know where you placed your BIOS files? Was it in the internal storage? Or in an SD card?

**Comment by peteelandroide** [comment]
Both my BIOS and ROMS are in the same folder on internal storage, storage permission is enabled for Melonds', used the BIOS you provided.

**Comment by rafaelvcaetano** [comment]
Could you give me a screenshot of your Settings screen in the System section?

**Comment by rafaelvcaetano** [comment]
Try the latest [Beta 1.2.0](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.2.0) release without custom BIOS. It should fix the problem. Meanwhile, I will close this issue to avoid duplicates. If the problem persists, leave a comment on the referenced issue.
