### ISSUE TITLE
Seila

### ISSUE THREAD

**Issue by davidocreu13** [rafaelvcaetano/melonDS-android#622]
* **Device model:** Moto G (5) Plus
* **Android version:** Android API 27
* **melonDS version:** Beta 1.3.0

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$d: Failed to load firmware: BIOS9_MISSING
	at me.magnum.melonds.ui.emulator.h$c.a(Unknown Source:67)
	at f.a.b0.e.a.a.g(Unknown Source:10)
	at f.a.a.a(Unknown Source:14)
	at f.a.b0.e.a.e$a.run(Unknown Source:2)
	at f.a.r$a.run(Unknown Source:9)
	at f.a.b0.g.k.run(Unknown Source:13)
	at f.a.b0.g.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

```

**Configuration:**  
```
FirmwareCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=true, dsConfigDirectory=//, dsiConfigDirectory=//, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, useJit=false, consoleType=DS, soundEnabled=true, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), dsiBiosDirUri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FBios, dsBiosDirUri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FBios)
```

**Comment by davidocreu13** [comment]
Xngxtjd hmexgjzsgcek hf

**Comment by davidocreu13** [comment]
Rzlyevwktxwvktzdyk,wwdtkzstvkzwvbkxggxwj

**Comment by davidocreu13** [comment]
Lrbyxrnojrnpuucvfphevoyekheblh

**Comment by davidocreu13** [comment]
F lu dmh djfxm

**Comment by davidocreu13** [comment]
Nddxoyccwxcohrb

**Comment by davidocreu13** [comment]
Tou😚🙃😄😑

**Comment by davidocreu13** [comment]
Cuek😆😆😄

**Comment by davidocreu13** [comment]
Helctsxektw😂😌😌😘🤣😚

**Comment by davidocreu13** [comment]
Gskvskyvsyvkhsclyv as

**Comment by davidocreu13** [comment]
GG Diamantino ficando haha doce ngcdkyv

**Comment by davidocreu13** [comment]
H😭😘😘

**Comment by davidocreu13** [comment]
Mg😃🤣😅😘🖕😘😄😚😘😁😆

**Comment by davidocreu13** [comment]
Fhdktxjgzjgxgjziydtix😑

**Comment by davidocreu13** [comment]
Nfhkdohdhodiydyi

**Comment by davidocreu13** [comment]
Kdkgdgidyi

**Comment by davidocreu13** [comment]
Kgxkvdyi

**Comment by davidocreu13** [comment]
Kbxgkx

**Comment by rafaelvcaetano** [comment]
Please try the [latest version](https://github.com/rafaelvcaetano/melonDS-android/releases/latest) where this problem should be fixed. Or download it from the [Play Store](https://play.google.com/store/apps/details?id=me.magnum.melonds) to always keep the app up-to-date. If you still encounter errors after updating, please open a new issue.
