### ISSUE TITLE
Pokemon Black

### ISSUE THREAD

**Issue by ExtraCreditsMonika** [rafaelvcaetano/melonDS-android#661]
* **Device model:** GIONEE A1
* **Android version:** Android API 24
* **melonDS version:** Beta 1.6.1 PS

**Problem:**  
It says, "Could not load ROM" 
**Stack trace:**  
```
g6.c: Could not create temporary SRAM file at content://com.android.externalstorage.documents/tree/primary%3ADownload%2Fpokemon-black-version%5Bhexrom.com%5D.zip/document/primary%3ADownload%2Fpokemon-black-version%5Bhexrom.com%5D.zip
	at me.magnum.melonds.ui.emulator.EmulatorViewModel.I()
	at me.magnum.melonds.ui.emulator.d1.I()
	at me.magnum.melonds.ui.emulator.d1.i()
	at me.magnum.melonds.ui.emulator.c1.a()
	at c4.a.v()
	at o3.t.b()
	at c4.f$a.c()
	at c4.p$b.c()
	at c4.p$c.c()
	at z3.m$a.c()
	at z3.j$a.run()
	at o3.s$a.run()
	at e4.k.run()
	at e4.k.call()
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=false, showBootScreen=false, dsBios7Uri=null, dsBios9Uri=null, dsFirmwareUri=null, dsiBios7Uri=null, dsiBios9Uri=null, dsiFirmwareUri=null, dsiNandUri=null, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, useJit=true, consoleType=DS, soundEnabled=true, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1, randomizeMacAddress=false, internalMacAddress=00:09:BF:B8:3E:51), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2Fpokemon-black-version%5Bhexrom.com%5D.zip, romUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2Fpokemon-black-version%5Bhexrom.com%5D.zip/document/primary%3ADownload%2Fpokemon-black-version%5Bhexrom.com%5D.zip%005585%20-%20Pokemon%20-%20Black%20Version%20(DSi%20Enhanced)(USA)%20(E)(SweeTnDs).nds, sramUri=null)
```

**Comment by rafaelvcaetano** [comment]
While I try to fix this problem, please do not select the ZIP file as the ROM directory. Select the parent folder or extract the files.
