### ISSUE TITLE
Mano resolve a merda desse big do log

### ISSUE THREAD

**Issue by Foxygamer13432A** [rafaelvcaetano/melonDS-android#663]
* **Device model:** moto g(6) plus
* **Android version:** Android API 28
* **melonDS version:** Beta 1.5.0

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$d: Failed to load firmware: BIOS9_BAD
	at me.magnum.melonds.ui.emulator.i$c.a(Unknown Source:77)
	at f.a.c0.e.a.a.i(Unknown Source:10)
	at f.a.a.a(Unknown Source:14)
	at f.a.c0.e.a.e$a.run(Unknown Source:2)
	at f.a.s$a.run(Unknown Source:9)
	at f.a.c0.g.k.run(Unknown Source:13)
	at f.a.c0.g.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

```

**Configuration:**  
```
FirmwareCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=true, showBootScreen=false, dsBios7Uri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDSi/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDSi%2Fbios7.bin, dsBios9Uri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDSi/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDSi%2Fbios9.bin, dsFirmwareUri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDSi/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDSi%2Ffirmware.bin, dsiBios7Uri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDSi/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDSi%2Fbios7.bin, dsiBios9Uri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDSi/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDSi%2Fbios9.bin, dsiFirmwareUri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDSi/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDSi%2Ffirmware.bin, dsiNandUri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDSi/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDSi%2Fnand.bin, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, useJit=true, consoleType=DSi, soundEnabled=true, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1, randomizeMacAddress=false, internalMacAddress=00:09:BF:CC:83:D1), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), dsiBiosDirUri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDSi, dsBiosDirUri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDSi)
```

**Comment by rafaelvcaetano** [comment]
Mano, instala a última versão! Tens na [Play Store](https://play.google.com/store/apps/details?id=me.magnum.melonds).
