### ISSUE TITLE
Que puedo hacer?

### ISSUE THREAD

**Issue by JaffyGame** [rafaelvcaetano/melonDS-android#670]
* **Device model:** CPH2127
* **Android version:** Android API 30
* **melonDS version:** Beta 1.6.1 PS

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
g6.c: Could not create temporary SRAM file at content://com.file.explorer.manager.space.clean.storage.documents/tree/secondary1783-B64B%3ARoms%20DS%2FDragon%20Ball%20Z_%20Supersonic%20Warriors%202/document/secondary1783-B64B%3ARoms%20DS%2FDragon%20Ball%20Z_%20Supersonic%20Warriors%202
	at me.magnum.melonds.ui.emulator.EmulatorViewModel.I(Unknown Source:117)
	at me.magnum.melonds.ui.emulator.d1.I(Unknown Source:75)
	at me.magnum.melonds.ui.emulator.d1.i(Unknown Source:0)
	at me.magnum.melonds.ui.emulator.c1.a(Unknown Source:8)
	at c4.a.v(Unknown Source:10)
	at o3.t.b(Unknown Source:14)
	at c4.f$a.c(Unknown Source:27)
	at c4.p$b.c(Unknown Source:26)
	at c4.p$c.c(Unknown Source:4)
	at z3.m$a.c(Unknown Source:6)
	at z3.j$a.run(Unknown Source:21)
	at o3.s$a.run(Unknown Source:9)
	at e4.k.run(Unknown Source:13)
	at e4.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=false, showBootScreen=false, dsBios7Uri=null, dsBios9Uri=null, dsFirmwareUri=null, dsiBios7Uri=null, dsiBios9Uri=null, dsiFirmwareUri=null, dsiNandUri=null, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, useJit=true, consoleType=DS, soundEnabled=true, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1, randomizeMacAddress=false, internalMacAddress=00:09:BF:BA:0A:80), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.file.explorer.manager.space.clean.storage.documents/tree/secondary1783-B64B%3ARoms%20DS%2FDragon%20Ball%20Z_%20Supersonic%20Warriors%202, romUri=content://com.file.explorer.manager.space.clean.storage.documents/tree/secondary1783-B64B%3ARoms%20DS%2FDragon%20Ball%20Z_%20Supersonic%20Warriors%202/document/secondary1783-B64B%3ARoms%20DS%2FDragon%20Ball%20Z_%20Supersonic%20Warriors%202%2FDragon%20Ball%20Z%20-%20Supersonic%20Warriors%202%20(USA).nds, sramUri=null)
```

**Comment by rafaelvcaetano** [comment]
This should be fixed in the [Beta 1.7.0](https://github.com/rafaelvcaetano/melonDS-android/releases/latest) release. If it doesn't allow you to select the folder with the ROMs, try extracting them.
