### ISSUE TITLE
Can't run the ROM

### ISSUE THREAD

**Issue by AxelFp3** [rafaelvcaetano/melonDS-android#69]
* **Device model:** ZTE Blade V10 Vita
* **Android version:** Android API 28

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$f: Failed to load ROM: NDS_FAILED
	at me.magnum.melonds.ui.emulator.j$c$a$a.a(Unknown Source:205)
	at f.a.b0.e.e.a.m(Unknown Source:10)
	at f.a.s.a(Unknown Source:14)
	at f.a.b0.e.b.e$a.d(Unknown Source:26)
	at f.a.b0.e.b.l$a.d(Unknown Source:2)
	at f.a.b0.e.b.j$a.run(Unknown Source:21)
	at f.a.r$a.run(Unknown Source:9)
	at f.a.b0.g.j.run(Unknown Source:13)
	at f.a.b0.g.j.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

```

**Comment by rafaelvcaetano** [comment]
Try the latest [Beta 1.2.0](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.2.0) release without custom BIOS. It should fix the problem. Meanwhile, I will close this issue to avoid duplicates. If the problem persists, leave a comment on issue #62.
