### ISSUE TITLE
New Mario Bros

### ISSUE THREAD

**Issue by Talxon** [rafaelvcaetano/melonDS-android#692]
* **Device model:** Redmi Note 6 Pro
* **Android version:** Android API 28
* **melonDS version:** Beta 1.6.1 PS

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
g6.c: Could not create temporary SRAM file at content://com.android.externalstorage.documents/tree/primary%3Acitra-emu%2Fsdmc%2Fsdmc%2FSaves%20DS/document/primary%3Acitra-emu%2Fsdmc%2Fsdmc%2FSaves%20DS
	at me.magnum.melonds.ui.emulator.EmulatorViewModel.I(Unknown Source:117)
	at me.magnum.melonds.ui.emulator.d1.I(Unknown Source:75)
	at me.magnum.melonds.ui.emulator.d1.i(Unknown Source:0)
	at me.magnum.melonds.ui.emulator.c1.a(Unknown Source:8)
	at c4.a.v(Unknown Source:10)
	at o3.t.b(Unknown Source:14)
	at c4.f$a.c(Unknown Source:27)
	at c4.p$b.c(Unknown Source:26)
	at c4.p$c.c(Unknown Source:4)
	at z3.m$a.c(Unknown Source:6)
	at z3.j$a.run(Unknown Source:21)
	at o3.s$a.run(Unknown Source:9)
	at e4.k.run(Unknown Source:13)
	at e4.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=true, showBootScreen=false, dsBios7Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2Fnds%20bios/document/primary%3ADownload%2Fnds%20bios%2Fbios7.bin, dsBios9Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2Fnds%20bios/document/primary%3ADownload%2Fnds%20bios%2Fbios9.bin, dsFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2Fnds%20bios/document/primary%3ADownload%2Fnds%20bios%2Ffirmware.bin, dsiBios7Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2Fdsi%20bios/document/primary%3ADownload%2Fdsi%20bios%2Fbios7.bin, dsiBios9Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2Fdsi%20bios/document/primary%3ADownload%2Fdsi%20bios%2Fbios9.bin, dsiFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2Fdsi%20bios/document/primary%3ADownload%2Fdsi%20bios%2Ffirmware.bin, dsiNandUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2Fdsi%20bios/document/primary%3ADownload%2Fdsi%20bios%2Fnand.bin, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, useJit=true, consoleType=DS, soundEnabled=true, micSource=DEVICE, firmwareConfiguration=FirmwareConfiguration(nickname=Talx, message=Hello!, language=1, favouriteColour=2, birthdayMonth=4, birthdayDay=21, randomizeMacAddress=false, internalMacAddress=null), rendererConfiguration=RendererConfiguration(videoFiltering=NONE, threadedRendering=true)), romSearchDirUri=content://com.android.externalstorage.documents/tree/primary%3ADownload, romUri=content://com.android.externalstorage.documents/tree/primary%3ADownload/document/primary%3ADownload%2FNew%20Super%20Mario%20Bros.nds, sramUri=null)
```

**Comment by rafaelvcaetano** [comment]
This should be fixed in the [Beta 1.7.0](https://github.com/rafaelvcaetano/melonDS-android/releases/latest) release. If it doesn't allow you to select the folder with the ROMs, try extracting them.
