### ISSUE TITLE
No me deja jugar a los juegos

### ISSUE THREAD

**Issue by Yam1l** [rafaelvcaetano/melonDS-android#696]
* **Device model:** LM-X410.F
* **Android version:** Android API 25
* **melonDS version:** Beta 1.5.0

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.n.b: Could not create temporary SRAM file at content://com.android.externalstorage.documents/tree/primary%3ADownload%2FPokemon%20Soul%20Silver%20(David%20Nintenplay)%2FJuego%2FPokemon%20Soul%20Silver%20Espa%C3%B1ol.zip/document/primary%3ADownload%2FPokemon%20Soul%20Silver%20(David%20Nintenplay)%2FJuego
	at me.magnum.melonds.ui.emulator.EmulatorViewModel.B()
	at me.magnum.melonds.ui.emulator.k$e$a$a.a()
	at f.a.c0.e.e.a.q()
	at f.a.t.a()
	at f.a.c0.e.b.e$a.d()
	at f.a.c0.e.b.m$a.d()
	at f.a.c0.e.b.k$a.run()
	at f.a.s$a.run()
	at f.a.c0.g.k.run()
	at f.a.c0.g.k.call()
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=false, showBootScreen=false, dsBios7Uri=null, dsBios9Uri=null, dsFirmwareUri=null, dsiBios7Uri=null, dsiBios9Uri=null, dsiFirmwareUri=null, dsiNandUri=null, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, useJit=false, consoleType=DS, soundEnabled=true, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1, randomizeMacAddress=false, internalMacAddress=00:09:BF:D1:15:09), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FPokemon%20Soul%20Silver%20(David%20Nintenplay)%2FJuego%2FPokemon%20Soul%20Silver%20Espa%C3%B1ol.zip, romUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FPokemon%20Soul%20Silver%20(David%20Nintenplay)%2FJuego%2FPokemon%20Soul%20Silver%20Espa%C3%B1ol.zip/document/primary%3ADownload%2FPokemon%20Soul%20Silver%20(David%20Nintenplay)%2FJuego%2FPokemon%20Soul%20Silver%20Espa%C3%B1ol.zip%00Pokemon%20Soul%20Silver%20Espa%C3%B1ol.nds, sramUri=null)
```

**Comment by rafaelvcaetano** [comment]
Please try the [latest version](https://github.com/rafaelvcaetano/melonDS-android/releases/latest) where this problem should be fixed. Or download it from the [Play Store](https://play.google.com/store/apps/details?id=me.magnum.melonds) to always keep the app up-to-date. If you still encounter errors after updating, please open a new issue.
