### ISSUE TITLE
Golden sun

### ISSUE THREAD

**Issue by Teddyseddysjj** [rafaelvcaetano/melonDS-android#775]
* **Device model:** 5033A
* **Android version:** Android API 27

* **melonDS version:** Beta 1.7.0 PS

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$c: Failed to load ROM: NDS_FAILED
	at k6.q.N(Unknown Source:143)
	at k6.q.x(Unknown Source:0)
	at k6.p.a(Unknown Source:8)
	at a4.a.v(Unknown Source:10)
	at m3.t.b(Unknown Source:14)
	at a4.f$a.d(Unknown Source:27)
	at a4.p$b.c(Unknown Source:26)
	at a4.p$c.d(Unknown Source:4)
	at x3.m$a.a(Unknown Source:10)
	at x3.j$a.run(Unknown Source:27)
	at m3.s$a.run(Unknown Source:9)
	at c4.k.run(Unknown Source:13)
	at c4.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=true, showBootScreen=true, dsBios7Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FmelonDsBios_espa%C3%B1ol/document/primary%3ADownload%2FmelonDsBios_espa%C3%B1ol%2Fbios7.bin, dsBios9Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FmelonDsBios_espa%C3%B1ol/document/primary%3ADownload%2FmelonDsBios_espa%C3%B1ol%2Fbios9.bin, dsFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FmelonDsBios_espa%C3%B1ol/document/primary%3ADownload%2FmelonDsBios_espa%C3%B1ol%2Ffirmware.bin, dsiBios7Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FmelonDsBios_espa%C3%B1ol/document/primary%3ADownload%2FmelonDsBios_espa%C3%B1ol%2Fbios7.bin, dsiBios9Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FmelonDsBios_espa%C3%B1ol/document/primary%3ADownload%2FmelonDsBios_espa%C3%B1ol%2Fbios9.bin, dsiFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FmelonDsBios_espa%C3%B1ol/document/primary%3ADownload%2FmelonDsBios_espa%C3%B1ol%2Ffirmware.bin, dsiNandUri=null, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, rewindEnabled=false, rewindPeriodSeconds=10, rewindWindowSeconds=60, useJit=false, consoleType=DS, soundEnabled=true, audioInterpolation=NONE, audioBitrate=AUTO, volume=256, audioLatency=MEDIUM, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=teddy, message=Holi :), language=5, favouriteColour=4, birthdayMonth=12, birthdayDay=31, randomizeMacAddress=true, internalMacAddress=null), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FDownload, romUri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FDownload/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FDownload%2F5387%20-%20Golden%20Sun%20-%20Dark%20Dawn%20(Europe)%20(En%2CFr%2CDe%2CEs%2CIt).nds, sramUri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FDownload/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FDownload%2F5387%20-%20Golden%20Sun%20-%20Dark%20Dawn%20(Europe)%20(En%2CFr%2CDe%2CEs%2CIt).sav)
```

**Comment by rafaelvcaetano** [comment]
I can't seem to find any particular reason why this would happen. Could you send me a screenshot of the Settings -> ROMs screen?
