### ISSUE TITLE
issue :(

### ISSUE THREAD

**Issue by cadogamer** [rafaelvcaetano/melonDS-android#794]
* **Device model:** SM-A315G
* **Android version:** Android API 30
* **melonDS version:** Beta 1.7.0 PS

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
g6.c: Could not create temporary SRAM file at content://com.android.externalstorage.documents/tree/primary%3Asaves/document/primary%3Asaves
	at me.magnum.melonds.ui.emulator.EmulatorViewModel.N(Unknown Source:117)
	at k6.q.N(Unknown Source:75)
	at k6.q.x(Unknown Source:0)
	at k6.p.a(Unknown Source:8)
	at a4.a.v(Unknown Source:10)
	at m3.t.b(Unknown Source:14)
	at a4.f$a.d(Unknown Source:27)
	at a4.p$b.c(Unknown Source:26)
	at a4.p$c.d(Unknown Source:4)
	at x3.m$a.d(Unknown Source:6)
	at x3.j$a.run(Unknown Source:21)
	at m3.s$a.run(Unknown Source:9)
	at c4.k.run(Unknown Source:13)
	at c4.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=false, showBootScreen=false, dsBios7Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FNDS%20Firmware%20%26%20BIOs%2FNDS%20Bios%20%26%20Firmware/document/primary%3ADownload%2FNDS%20Firmware%20%26%20BIOs%2FNDS%20Bios%20%26%20Firmware%2Fbios7.bin, dsBios9Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FNDS%20Firmware%20%26%20BIOs%2FNDS%20Bios%20%26%20Firmware/document/primary%3ADownload%2FNDS%20Firmware%20%26%20BIOs%2FNDS%20Bios%20%26%20Firmware%2Fbios9.bin, dsFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FNDS%20Firmware%20%26%20BIOs%2FNDS%20Bios%20%26%20Firmware/document/primary%3ADownload%2FNDS%20Firmware%20%26%20BIOs%2FNDS%20Bios%20%26%20Firmware%2Ffirmware.bin, dsiBios7Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FNDS%20Firmware%20%26%20BIOs%2FNDS%20Bios%20%26%20Firmware/document/primary%3ADownload%2FNDS%20Firmware%20%26%20BIOs%2FNDS%20Bios%20%26%20Firmware%2Fbios7.bin, dsiBios9Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FNDS%20Firmware%20%26%20BIOs%2FNDS%20Bios%20%26%20Firmware/document/primary%3ADownload%2FNDS%20Firmware%20%26%20BIOs%2FNDS%20Bios%20%26%20Firmware%2Fbios9.bin, dsiFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FNDS%20Firmware%20%26%20BIOs%2FNDS%20Bios%20%26%20Firmware/document/primary%3ADownload%2FNDS%20Firmware%20%26%20BIOs%2FNDS%20Bios%20%26%20Firmware%2Ffirmware.bin, dsiNandUri=null, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=8.0, rewindEnabled=true, rewindPeriodSeconds=20, rewindWindowSeconds=60, useJit=true, consoleType=DS, soundEnabled=true, audioInterpolation=NONE, audioBitrate=AUTO, volume=74, audioLatency=MEDIUM, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1, randomizeMacAddress=false, internalMacAddress=00:09:BF:6E:1A:12), rendererConfiguration=RendererConfiguration(videoFiltering=LCD, threadedRendering=true)), romSearchDirUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FPokemon%20Volt%20White%202%20-%20Complete, romUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FPokemon%20Volt%20White%202%20-%20Complete/document/primary%3ADownload%2FPokemon%20Volt%20White%202%20-%20Complete%2FPokemon%20Volt%20White%202%20-%20Complete.nds, sramUri=null)
```

**Comment by rafaelvcaetano** [comment]
Could you send me a screenshot of the Settings > Save Files screen?

And could you confirm that the directory you selected in the "Save file directory" option really exists?

**Comment by cadogamer** [comment]
uhhh, i guess i already solved the issue by unistaling and reinstaling the apk, but thanks anyway
