### ISSUE TITLE
Pokémon Conquest

### ISSUE THREAD

**Issue by Platymek** [rafaelvcaetano/melonDS-android#843]
* **Device model:** MAR-LX1A
* **Android version:** Android API 29
* **melonDS version:** Beta 1.7.0 PS

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
g6.c: Could not create temporary SRAM file at content://com.android.externalstorage.documents/tree/DBEA-FD33%3AConsoles%2FNintendo%20DS/document/DBEA-FD33%3AConsoles%2FNintendo%20DS%2FPokemon%20Conquest%20(USA%2C%20Australia)%20(Rev%201)%20(NDSi%20Enhanced)
	at me.magnum.melonds.ui.emulator.EmulatorViewModel.N(Unknown Source:117)
	at k6.q.N(Unknown Source:75)
	at k6.q.x(Unknown Source:0)
	at k6.p.a(Unknown Source:8)
	at a4.a.v(Unknown Source:10)
	at m3.t.b(Unknown Source:14)
	at a4.f$a.d(Unknown Source:27)
	at a4.p$b.c(Unknown Source:26)
	at a4.p$c.d(Unknown Source:4)
	at x3.m$a.d(Unknown Source:6)
	at x3.j$a.run(Unknown Source:21)
	at m3.s$a.run(Unknown Source:9)
	at c4.k.run(Unknown Source:13)
	at c4.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=false, showBootScreen=false, dsBios7Uri=null, dsBios9Uri=null, dsFirmwareUri=null, dsiBios7Uri=null, dsiBios9Uri=null, dsiFirmwareUri=null, dsiNandUri=null, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, rewindEnabled=false, rewindPeriodSeconds=10, rewindWindowSeconds=60, useJit=true, consoleType=DS, soundEnabled=true, audioInterpolation=NONE, audioBitrate=AUTO, volume=256, audioLatency=MEDIUM, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1, randomizeMacAddress=false, internalMacAddress=00:09:BF:7B:35:B3), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.externalstorage.documents/tree/DBEA-FD33%3AConsoles%2FNintendo%20DS, romUri=content://com.android.externalstorage.documents/tree/DBEA-FD33%3AConsoles%2FNintendo%20DS/document/DBEA-FD33%3AConsoles%2FNintendo%20DS%2FPokemon%20Conquest%20(USA%2C%20Australia)%20(Rev%201)%20(NDSi%20Enhanced)%2FPokemon%20Conquest%20(USA%2C%20Australia)%20(Rev%201)%20(NDSi%20Enhanced).nds, sramUri=content://com.android.externalstorage.documents/tree/DBEA-FD33%3AConsoles%2FNintendo%20DS/document/DBEA-FD33%3AConsoles%2FNintendo%20DS%2FPokemon%20Conquest%20(USA%2C%20Australia)%20(Rev%201)%20(NDSi%20Enhanced)%2FPokemon%20Conquest%20(USA%2C%20Australia)%20(Rev%201)%20(NDSi%20Enhanced).sav)
```

**Comment by rafaelvcaetano** [comment]
Please try the [latest version](https://github.com/rafaelvcaetano/melonDS-android/releases/latest) where this problem should be fixed. Or download it from the [Play Store](https://play.google.com/store/apps/details?id=me.magnum.melonds) to always keep the app up-to-date. If you still encounter errors after updating, please open a new issue.
