### ISSUE TITLE
DS bootfirmware doesn't work

### ISSUE THREAD

**Issue by Jonasking09** [rafaelvcaetano/melonDS-android#895]
* **Device model:** M2101K6G
* **Android version:** Android API 31
* **melonDS version:** Beta 1.7.0 PS

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$b: Failed to load firmware: FIRMWARE_NOT_BOOTABLE
	at h6.c.n(Unknown Source:65)
	at h6.c.j(Unknown Source:0)
	at h6.a.a(Unknown Source:4)
	at w3.a.j(Unknown Source:10)
	at m3.a.a(Unknown Source:14)
	at a4.g$a.d(Unknown Source:20)
	at a4.i.v(Unknown Source:9)
	at m3.t.b(Unknown Source:14)
	at a4.g.j(Unknown Source:12)
	at m3.a.a(Unknown Source:14)
	at w3.e$a.run(Unknown Source:2)
	at m3.s$a.run(Unknown Source:9)
	at c4.k.run(Unknown Source:13)
	at c4.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)

```

**Configuration:**  
```
FirmwareCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=true, showBootScreen=true, dsBios7Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2Fdownloaded_rom/document/primary%3ADownload%2Fdownloaded_rom%2Fbios7.bin, dsBios9Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2Fdownloaded_rom/document/primary%3ADownload%2Fdownloaded_rom%2Fbios9.bin, dsFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2Fdownloaded_rom/document/primary%3ADownload%2Fdownloaded_rom%2Ffirmware.bin, dsiBios7Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2Fdsidump/document/primary%3ADownload%2Fdsidump%2Fbios7.bin, dsiBios9Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2Fdsidump/document/primary%3ADownload%2Fdsidump%2Fbios9.bin, dsiFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2Fdsidump/document/primary%3ADownload%2Fdsidump%2Ffirmware.bin, dsiNandUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2Fdsidump/document/primary%3ADownload%2Fdsidump%2Fnand.bin, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, rewindEnabled=false, rewindPeriodSeconds=10, rewindWindowSeconds=60, useJit=true, consoleType=DS, soundEnabled=true, audioInterpolation=NONE, audioBitrate=AUTO, volume=256, audioLatency=MEDIUM, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=malaika, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1, randomizeMacAddress=false, internalMacAddress=null), rendererConfiguration=RendererConfiguration(videoFiltering=LCD, threadedRendering=true)), dsiBiosDirUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2Fdownloaded_rom, dsBiosDirUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2Fdsidump)
```

**Comment by rafaelvcaetano** [comment]
This error should be fixed in the latest nightly build.
