### ISSUE TITLE
Couldn't Load The rom!

### ISSUE THREAD

**Issue by ASGAMING009** [rafaelvcaetano/melonDS-android#898]
* **Device model:** M2004J19C
* **Android version:** Android API 30
* **melonDS version:** Beta 1.7.0 (ca117bd) GH

**Problem:**  
The Rom Doesn't Load! (Maybe its because of i stored them in sd card)

**Stack trace:**  
```
j6.c: Could not create temporary SRAM file at content://com.android.externalstorage.documents/tree/primary%3ANINTENDO%2FDS%20Saves/document/primary%3ANINTENDO%2FDS%20Saves
	at me.magnum.melonds.ui.emulator.EmulatorViewModel.N(Unknown Source:117)
	at n6.q.N(Unknown Source:75)
	at n6.q.x(Unknown Source:0)
	at n6.p.a(Unknown Source:8)
	at c4.a.v(Unknown Source:10)
	at n3.u.b(Unknown Source:14)
	at c4.f$a.d(Unknown Source:27)
	at c4.p$b.c(Unknown Source:26)
	at c4.p$c.d(Unknown Source:4)
	at z3.m$a.d(Unknown Source:6)
	at z3.j$a.run(Unknown Source:21)
	at n3.t$a.run(Unknown Source:9)
	at e4.k.run(Unknown Source:13)
	at e4.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=true, showBootScreen=false, dsBios7Uri=content://com.android.externalstorage.documents/tree/981F-1CFF%3AGames%2FNINTENDO%2FDS%20Bios/document/981F-1CFF%3AGames%2FNINTENDO%2FDS%20Bios%2Fbios7.bin, dsBios9Uri=content://com.android.externalstorage.documents/tree/981F-1CFF%3AGames%2FNINTENDO%2FDS%20Bios/document/981F-1CFF%3AGames%2FNINTENDO%2FDS%20Bios%2Fbios9.bin, dsFirmwareUri=content://com.android.externalstorage.documents/tree/981F-1CFF%3AGames%2FNINTENDO%2FDS%20Bios/document/981F-1CFF%3AGames%2FNINTENDO%2FDS%20Bios%2Ffirmware.bin, dsiBios7Uri=null, dsiBios9Uri=null, dsiFirmwareUri=null, dsiNandUri=null, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, rewindEnabled=true, rewindPeriodSeconds=10, rewindWindowSeconds=60, useJit=true, consoleType=DS, soundEnabled=true, audioInterpolation=LINEAR, audioBitrate=BIT16, volume=79, audioLatency=HIGH, micSource=DEVICE, firmwareConfiguration=FirmwareConfiguration(nickname=Ayush, message=Hello!, language=1, favouriteColour=2, birthdayMonth=10, birthdayDay=14, randomizeMacAddress=false, internalMacAddress=null), rendererConfiguration=RendererConfiguration(videoFiltering=XBR2, threadedRendering=true)), romSearchDirUri=content://com.android.externalstorage.documents/tree/981F-1CFF%3AGames%2FNINTENDO%2FDS, romUri=content://com.android.externalstorage.documents/tree/981F-1CFF%3AGames%2FNINTENDO%2FDS/document/981F-1CFF%3AGames%2FNINTENDO%2FDS%2FPokemon%20-%20SoulSilver%20Version%20(USA)%20(NoSSL).nds, sramUri=null)
```

**Comment by ASGAMING009** [comment]
I WOULD APPRECIATE ANY KIND OF HELP!

**Comment by ASGAMING009** [comment]
AND YES MY KEYBOARD IS LOCKED IN CAPS.

**Comment by moriel5** [comment]
@ASGAMING009 why is your keyboard locked to caps?
If it a physical keyboard or a software keyboard?

**Comment by cyruzwings** [comment]
try video filtering to none, see if its work
