### ISSUE TITLE
A

### ISSUE THREAD

**Issue by MasterX88** [rafaelvcaetano/melonDS-android#900]
* **Device model:** CPH2273
* **Android version:** Android API 30
* **melonDS version:** Beta 1.7.0 (ca117bd) GH

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
j6.c: Could not create temporary SRAM file at content://com.android.externalstorage.documents/tree/primary%3AMelonDS%20savs/document/primary%3AMelonDS%20savs
	at me.magnum.melonds.ui.emulator.EmulatorViewModel.N(Unknown Source:117)
	at n6.q.N(Unknown Source:75)
	at n6.q.x(Unknown Source:0)
	at n6.p.a(Unknown Source:8)
	at c4.a.v(Unknown Source:10)
	at n3.u.b(Unknown Source:14)
	at c4.f$a.d(Unknown Source:27)
	at c4.p$b.c(Unknown Source:26)
	at c4.p$c.d(Unknown Source:4)
	at z3.m$a.d(Unknown Source:6)
	at z3.j$a.run(Unknown Source:21)
	at n3.t$a.run(Unknown Source:9)
	at e4.k.run(Unknown Source:13)
	at e4.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=true, showBootScreen=false, dsBios7Uri=content://com.android.externalstorage.documents/tree/primary%3ADS%20Bios%20%26%20Firmware%2FDS/document/primary%3ADS%20Bios%20%26%20Firmware%2FDS%2Fbios7.bin, dsBios9Uri=content://com.android.externalstorage.documents/tree/primary%3ADS%20Bios%20%26%20Firmware%2FDS/document/primary%3ADS%20Bios%20%26%20Firmware%2FDS%2Fbios9.bin, dsFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3ADS%20Bios%20%26%20Firmware%2FDS/document/primary%3ADS%20Bios%20%26%20Firmware%2FDS%2Ffirmware.bin, dsiBios7Uri=null, dsiBios9Uri=null, dsiFirmwareUri=null, dsiNandUri=null, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, rewindEnabled=false, rewindPeriodSeconds=10, rewindWindowSeconds=60, useJit=true, consoleType=DS, soundEnabled=true, audioInterpolation=NONE, audioBitrate=AUTO, volume=256, audioLatency=MEDIUM, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1, randomizeMacAddress=false, internalMacAddress=null), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.externalstorage.documents/tree/primary%3AConsole%20Games%2FNintendo%20DS, romUri=content://com.android.externalstorage.documents/tree/primary%3AConsole%20Games%2FNintendo%20DS/document/primary%3AConsole%20Games%2FNintendo%20DS%2F3787%20-%20Pokemon%20-%20Edicion%20Platino%20(ES)(Independent).nds, sramUri=null)
```

**Comment by bphd** [comment]
Full stock? No unlock/debug/flash?

**Comment by Gamemulatorer** [comment]
@MasterX88 please update your melonDS app https://github.com/melonDS-emu/melonDS/releases/tag/0.9.5

**Comment by rafaelvcaetano** [comment]
Please try the [latest version](https://github.com/rafaelvcaetano/melonDS-android/releases/latest) where this problem should be fixed. Or download it from the [Play Store](https://play.google.com/store/apps/details?id=me.magnum.melonds) to always keep the app up-to-date. If you still encounter errors after updating, please open a new issue.
