### ISSUE TITLE
ROM crash

### ISSUE THREAD

**Issue by CarlOso31** [rafaelvcaetano/melonDS-android#905]
* **Device model:** M2004J19C
* **Android version:** Android API 30
* **melonDS version:** Beta 1.7.0 PS

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
g6.c: Could not create temporary SRAM file at content://com.android.externalstorage.documents/tree/primary%3AMelonDs%2FSaves/document/primary%3AMelonDs%2FSaves
	at me.magnum.melonds.ui.emulator.EmulatorViewModel.N(Unknown Source:117)
	at k6.q.N(Unknown Source:75)
	at k6.q.x(Unknown Source:0)
	at k6.p.a(Unknown Source:8)
	at a4.a.v(Unknown Source:10)
	at m3.t.b(Unknown Source:14)
	at a4.f$a.d(Unknown Source:27)
	at a4.p$b.c(Unknown Source:26)
	at a4.p$c.d(Unknown Source:4)
	at x3.m$a.d(Unknown Source:6)
	at x3.j$a.run(Unknown Source:21)
	at m3.s$a.run(Unknown Source:9)
	at c4.k.run(Unknown Source:13)
	at c4.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=true, showBootScreen=false, dsBios7Uri=content://com.android.externalstorage.documents/tree/primary%3ARoms%2FDS/document/primary%3ARoms%2FDS%2Fbios7.bin, dsBios9Uri=content://com.android.externalstorage.documents/tree/primary%3ARoms%2FDS/document/primary%3ARoms%2FDS%2Fbios9.bin, dsFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3ARoms%2FDS/document/primary%3ARoms%2FDS%2Ffirmware.bin, dsiBios7Uri=null, dsiBios9Uri=null, dsiFirmwareUri=null, dsiNandUri=null, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=2.0, rewindEnabled=false, rewindPeriodSeconds=10, rewindWindowSeconds=60, useJit=true, consoleType=DS, soundEnabled=true, audioInterpolation=NONE, audioBitrate=AUTO, volume=256, audioLatency=HIGH, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=CarlOso, message=RAWR, language=5, favouriteColour=0, birthdayMonth=7, birthdayDay=31, randomizeMacAddress=false, internalMacAddress=null), rendererConfiguration=RendererConfiguration(videoFiltering=HQ4X, threadedRendering=false)), romSearchDirUri=content://com.android.externalstorage.documents/tree/primary%3ARoms, romUri=content://com.android.externalstorage.documents/tree/primary%3ARoms/document/primary%3ARoms%2FPok%C3%A9mon%20-%20Edici%C3%B3n%20Platino.nds, sramUri=null)
```

**Comment by cyruzwings** [comment]
you must located the bios file

**Comment by ipkpjersi** [comment]
#938 and #947 and #952 and #962 and #984 and #985 and #997 and #1001 and #1009 and #1010 and #1011 and probably so many more I'm missing are duplicates of this.

**Comment by rafaelvcaetano** [comment]
Please try the [latest version](https://github.com/rafaelvcaetano/melonDS-android/releases/latest) where this problem should be fixed. Or download it from the [Play Store](https://play.google.com/store/apps/details?id=me.magnum.melonds) to always keep the app up-to-date. If you still encounter errors after updating, please open a new issue.
