### ISSUE TITLE
?

### ISSUE THREAD

**Issue by ggpokerbiel** [rafaelvcaetano/melonDS-android#926]
* **Device model:** SM-J260M
* **Android version:** Android API 27
* **melonDS version:** Beta 1.7.0 GH

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$c: Failed to load ROM: NDS_FAILED
	at n6.q.N(Unknown Source:143)
	at n6.q.x(Unknown Source:0)
	at n6.p.a(Unknown Source:8)
	at b4.a.v(Unknown Source:10)
	at m3.u.b(Unknown Source:14)
	at b4.f$a.d(Unknown Source:27)
	at b4.p$b.c(Unknown Source:26)
	at b4.p$c.d(Unknown Source:4)
	at y3.m$a.a(Unknown Source:10)
	at y3.j$a.run(Unknown Source:27)
	at m3.t$a.run(Unknown Source:9)
	at d4.k.run(Unknown Source:13)
	at d4.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=true, showBootScreen=false, dsBios7Uri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FBIOS%20(1)%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDS/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FBIOS%20(1)%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDS%2Fbios7.bin, dsBios9Uri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FBIOS%20(1)%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDS/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FBIOS%20(1)%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDS%2Fbios9.bin, dsFirmwareUri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FBIOS%20(1)%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDS/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FBIOS%20(1)%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDS%2Ffirmware.bin, dsiBios7Uri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FBIOS%20(1)%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDSi/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FBIOS%20(1)%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDSi%2Fbios7.bin, dsiBios9Uri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FBIOS%20(1)%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDSi/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FBIOS%20(1)%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDSi%2Fbios9.bin, dsiFirmwareUri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FBIOS%20(1)%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDSi/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FBIOS%20(1)%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDSi%2Ffirmware.bin, dsiNandUri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FBIOS%20(1)%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDSi/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FBIOS%20(1)%2FDS%20firmware%20%2B%20DSi%20NAND%20and%20firmware%2FDSi%2Fnand.bin, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, rewindEnabled=false, rewindPeriodSeconds=10, rewindWindowSeconds=60, useJit=false, consoleType=DS, soundEnabled=true, audioInterpolation=NONE, audioBitrate=AUTO, volume=256, audioLatency=MEDIUM, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1, randomizeMacAddress=false, internalMacAddress=null), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FPokemon%20Platinum%20-%20Traducao%20(BR), romUri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FPokemon%20Platinum%20-%20Traducao%20(BR)/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FPokemon%20Platinum%20-%20Traducao%20(BR)%2FPokemon%20Platinum%20(BR).nds, sramUri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FPokemon%20Platinum%20-%20Traducao%20(BR)/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FPokemon%20Platinum%20-%20Traducao%20(BR)%2FPokemon%20Platinum%20(BR).sav)
```

**Comment by rafaelvcaetano** [comment]
It looks like you are using a bad ROM. Try launching it on another emulator and they also fail, it means the ROM is broken. If other emulators work fine, please open another issue.
