### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by SparklingWaterBurns** [rafaelvcaetano/melonDS-android#947]
* **Device model:** SM-A125U
* **Android version:** Android API 30
* **melonDS version:** Beta 1.7.0 PS

**Problem:** 
I tried to boot up a DS Download Station rom of Pokémon Battle Revolution but I get a black screen and it kicks me out of emulation. Other Download Station files work for me.
**Stack trace:**  
```
g6.c: Could not create temporary SRAM file at content://com.android.externalstorage.documents/tree/primary%3AROMS3DS%2Fsav/document/primary%3AROMS3DS%2Fsav
	at me.magnum.melonds.ui.emulator.EmulatorViewModel.N(Unknown Source:117)
	at k6.q.N(Unknown Source:75)
	at k6.q.x(Unknown Source:0)
	at k6.p.a(Unknown Source:8)
	at a4.a.v(Unknown Source:10)
	at m3.t.b(Unknown Source:14)
	at a4.f$a.d(Unknown Source:27)
	at a4.p$b.c(Unknown Source:26)
	at a4.p$c.d(Unknown Source:4)
	at x3.m$a.d(Unknown Source:6)
	at x3.j$a.run(Unknown Source:21)
	at m3.s$a.run(Unknown Source:9)
	at c4.k.run(Unknown Source:13)
	at c4.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=true, showBootScreen=true, dsBios7Uri=content://com.android.externalstorage.documents/tree/primary%3ADS/document/primary%3ADS%2Fbios7.bin, dsBios9Uri=content://com.android.externalstorage.documents/tree/primary%3ADS/document/primary%3ADS%2Fbios9.bin, dsFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3ADS/document/primary%3ADS%2Ffirmware.bin, dsiBios7Uri=content://com.android.externalstorage.documents/tree/primary%3ADSi/document/primary%3ADSi%2Fbios7.bin, dsiBios9Uri=content://com.android.externalstorage.documents/tree/primary%3ADSi/document/primary%3ADSi%2Fbios9.bin, dsiFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3ADSi/document/primary%3ADSi%2Ffirmware.bin, dsiNandUri=content://com.android.externalstorage.documents/tree/primary%3ADSi/document/primary%3ADSi%2Fnand.bin, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=8.0, rewindEnabled=false, rewindPeriodSeconds=10, rewindWindowSeconds=60, useJit=true, consoleType=DS, soundEnabled=true, audioInterpolation=NONE, audioBitrate=AUTO, volume=256, audioLatency=HIGH, micSource=DEVICE, firmwareConfiguration=FirmwareConfiguration(nickname=ctayl, message=guh?, language=1, favouriteColour=10, birthdayMonth=1, birthdayDay=2, randomizeMacAddress=false, internalMacAddress=null), rendererConfiguration=RendererConfiguration(videoFiltering=LCD, threadedRendering=false)), romSearchDirUri=content://com.android.externalstorage.documents/tree/primary%3AROMSDS, romUri=content://com.android.externalstorage.documents/tree/primary%3AROMSDS/document/primary%3AROMSDS%2FPokemon%20Battle%20Revolution%20-%20Video%20(USA)%20(Demo)%20(DS%20Download%20Station).nds, sramUri=null)
```

**Comment by rafaelvcaetano** [comment]
Please try the [latest version](https://github.com/rafaelvcaetano/melonDS-android/releases/latest) where this problem should be fixed. Or download it from the [Play Store](https://play.google.com/store/apps/details?id=me.magnum.melonds) to always keep the app up-to-date. If you still encounter errors after updating, please open a new issue.
