### ISSUE TITLE
JORGE 

### ISSUE THREAD

**Issue by JORGE1929292929292992929292** [rafaelvcaetano/melonDS-android#952]
* **Device model:** SM-J260T1
* **Android version:** Android API 27
* **melonDS version:** Beta 1.7.0 (04dcd3e) GH

**Problem:**  
Insert a small description of the problem. Nada

**Stack trace:**  ok
```
j6.c: Could not create temporary SRAM file at content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FInazuma%20Eleven%202%20-%20Tormenta%20de%20Fuego%20(Spain)%20%5Bb%5D/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FInazuma%20Eleven%202%20-%20Tormenta%20de%20Fuego%20(Spain)%20%5Bb%5D
	at me.magnum.melonds.ui.emulator.EmulatorViewModel.N(Unknown Source:117)
	at n6.q.N(Unknown Source:75)
	at n6.q.x(Unknown Source:0)
	at n6.p.a(Unknown Source:8)
	at c4.a.v(Unknown Source:10)
	at n3.u.b(Unknown Source:14)
	at c4.f$a.d(Unknown Source:27)
	at c4.p$b.c(Unknown Source:26)
	at c4.p$c.d(Unknown Source:4)
	at z3.m$a.a(Unknown Source:10)
	at z3.j$a.run(Unknown Source:27)
	at n3.t$a.run(Unknown Source:9)
	at e4.k.run(Unknown Source:13)
	at e4.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=false, showBootScreen=false, dsBios7Uri=null, dsBios9Uri=null, dsFirmwareUri=null, dsiBios7Uri=null, dsiBios9Uri=null, dsiFirmwareUri=null, dsiNandUri=null, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, rewindEnabled=false, rewindPeriodSeconds=10, rewindWindowSeconds=60, useJit=false, consoleType=DS, soundEnabled=true, audioInterpolation=NONE, audioBitrate=AUTO, volume=256, audioLatency=MEDIUM, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1, randomizeMacAddress=false, internalMacAddress=00:09:BF:8B:1C:35), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FInazuma%20Eleven%202%20-%20Tormenta%20de%20Fuego%20(Spain)%20%5Bb%5D, romUri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FInazuma%20Eleven%202%20-%20Tormenta%20de%20Fuego%20(Spain)%20%5Bb%5D/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FInazuma%20Eleven%202%20-%20Tormenta%20de%20Fuego%20(Spain)%20%5Bb%5D%2Fz098%20-%20Inazuma%20Eleven%202%20-%20Tormenta%20de%20Fuego%20(Spain)%20%5Bb%5D.nds, sramUri=null)
```

**Comment by JORGE1929292929292992929292** [comment]
Ningúno
