### ISSUE TITLE
No me deja abrir ninguna ROM ¡Ayuda por favor!

### ISSUE THREAD

**Issue by ChisakiXDX** [rafaelvcaetano/melonDS-android#96]
* **Device model:** SM-G531H
* **Android version:** Android API 22

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$f: Failed to load ROM: NDS_FAILED
	at me.magnum.melonds.ui.emulator.j$c$a$a.a()
	at f.a.b0.e.e.a.m()
	at f.a.s.a()
	at f.a.b0.e.b.e$a.d()
	at f.a.b0.e.b.l$a.d()
	at f.a.b0.e.b.j$a.run()
	at f.a.r$a.run()
	at f.a.b0.g.j.run()
	at f.a.b0.g.j.call()
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

```

**Comment by rafaelvcaetano** [comment]
Try the latest [Beta 1.2.0](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.2.0) release without custom BIOS. It should fix the problem. Meanwhile, I will close this issue to avoid duplicates. If the problem persists, leave a comment on issue #62.
