### ISSUE TITLE
O

### ISSUE THREAD

**Issue by Porteee** [rafaelvcaetano/melonDS-android#978]
* **Device model:** SM-A207M
* **Android version:** Android API 30
* **melonDS version:** Beta 1.7.0 (23d09b5) GH

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$b: Failed to load firmware: FIRMWARE_NOT_BOOTABLE
	at b9.c.n(Unknown Source:57)
	at b9.c.j(Unknown Source:0)
	at b9.b.a(Unknown Source:4)
	at f6.a.k(Unknown Source:10)
	at v5.b.b(Unknown Source:14)
	at k6.f$a.c(Unknown Source:20)
	at k6.h.t(Unknown Source:9)
	at v5.u.b(Unknown Source:14)
	at k6.f.k(Unknown Source:12)
	at v5.b.b(Unknown Source:14)
	at f6.e$a.run(Unknown Source:2)
	at v5.t$a.run(Unknown Source:9)
	at m6.k.run(Unknown Source:13)
	at m6.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```

**Configuration:**  
```
FirmwareCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=true, showBootScreen=false, dsBios7Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FmelonDS%20APK%20Nightly%20rev.23d09b5%2FBIOS%20DS%20%2B%20firmware%20DS/document/primary%3ADownload%2FmelonDS%20APK%20Nightly%20rev.23d09b5%2FBIOS%20DS%20%2B%20firmware%20DS%2Fbios7.bin, dsBios9Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FmelonDS%20APK%20Nightly%20rev.23d09b5%2FBIOS%20DS%20%2B%20firmware%20DS/document/primary%3ADownload%2FmelonDS%20APK%20Nightly%20rev.23d09b5%2FBIOS%20DS%20%2B%20firmware%20DS%2Fbios9.bin, dsFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FmelonDS%20APK%20Nightly%20rev.23d09b5%2FBIOS%20DS%20%2B%20firmware%20DS/document/primary%3ADownload%2FmelonDS%20APK%20Nightly%20rev.23d09b5%2FBIOS%20DS%20%2B%20firmware%20DS%2Ffirmware.bin, dsiBios7Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FmelonDS%20APK%20Nightly%20rev.23d09b5%2FBIOS%20DS%20%2B%20firmware%20DS/document/primary%3ADownload%2FmelonDS%20APK%20Nightly%20rev.23d09b5%2FBIOS%20DS%20%2B%20firmware%20DS%2Fbios7.bin, dsiBios9Uri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FmelonDS%20APK%20Nightly%20rev.23d09b5%2FBIOS%20DS%20%2B%20firmware%20DS/document/primary%3ADownload%2FmelonDS%20APK%20Nightly%20rev.23d09b5%2FBIOS%20DS%20%2B%20firmware%20DS%2Fbios9.bin, dsiFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FmelonDS%20APK%20Nightly%20rev.23d09b5%2FBIOS%20DS%20%2B%20firmware%20DS/document/primary%3ADownload%2FmelonDS%20APK%20Nightly%20rev.23d09b5%2FBIOS%20DS%20%2B%20firmware%20DS%2Ffirmware.bin, dsiNandUri=null, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, rewindEnabled=false, rewindPeriodSeconds=10, rewindWindowSeconds=60, useJit=true, consoleType=DS, soundEnabled=true, audioInterpolation=NONE, audioBitrate=AUTO, volume=256, audioLatency=MEDIUM, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1, randomizeMacAddress=false, internalMacAddress=00:09:BF:97:36:E5), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), dsiBiosDirUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FmelonDS%20APK%20Nightly%20rev.23d09b5%2FBIOS%20DS%20%2B%20firmware%20DS, dsBiosDirUri=content://com.android.externalstorage.documents/tree/primary%3ADownload%2FmelonDS%20APK%20Nightly%20rev.23d09b5%2FBIOS%20DS%20%2B%20firmware%20DS)
```

**Comment by xxmichibxx** [comment]
Please verify your firmware binaries. Furthermore, adding a few more details, like when did the error occurred or steps to reproduce the issue, would help.

**Comment by rafaelvcaetano** [comment]
This error should be fixed in the latest nightly build.
