### ISSUE TITLE
New super mario bros

### ISSUE THREAD

**Issue by Krampus-update** [rafaelvcaetano/melonDS-android#979]
* **Device model:** M30
* **Android version:** Android API 29
* **melonDS version:** Beta 1.7.0 PS

**Problem:**  
I tried to open the new super mario bros and that's what happened

**Stack trace:**  
```
g6.c: Could not create temporary SRAM file at content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FDs%20rom/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FDs%20rom
	at me.magnum.melonds.ui.emulator.EmulatorViewModel.N(Unknown Source:117)
	at k6.q.N(Unknown Source:75)
	at k6.q.x(Unknown Source:0)
	at k6.p.a(Unknown Source:8)
	at a4.a.v(Unknown Source:10)
	at m3.t.b(Unknown Source:14)
	at a4.f$a.d(Unknown Source:27)
	at a4.p$b.c(Unknown Source:26)
	at a4.p$c.d(Unknown Source:4)
	at x3.m$a.a(Unknown Source:10)
	at x3.j$a.run(Unknown Source:27)
	at m3.s$a.run(Unknown Source:9)
	at c4.k.run(Unknown Source:13)
	at c4.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=false, showBootScreen=false, dsBios7Uri=content://com.android.externalstorage.documents/tree/primary%3Ads%20bios/document/primary%3Ads%20bios%2Fbios7.bin, dsBios9Uri=content://com.android.externalstorage.documents/tree/primary%3Ads%20bios/document/primary%3Ads%20bios%2Fbios9.bin, dsFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3Ads%20bios/document/primary%3Ads%20bios%2Ffirmware.bin, dsiBios7Uri=content://com.android.externalstorage.documents/tree/primary%3Ads%20bios/document/primary%3Ads%20bios%2Fbios7.bin, dsiBios9Uri=content://com.android.externalstorage.documents/tree/primary%3Ads%20bios/document/primary%3Ads%20bios%2Fbios9.bin, dsiFirmwareUri=content://com.android.externalstorage.documents/tree/primary%3Ads%20bios/document/primary%3Ads%20bios%2Ffirmware.bin, dsiNandUri=content://com.android.externalstorage.documents/tree/primary%3Ads%20bios/document/primary%3Ads%20bios%2Fnand.bin, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, rewindEnabled=true, rewindPeriodSeconds=10, rewindWindowSeconds=60, useJit=true, consoleType=DSi, soundEnabled=true, audioInterpolation=NONE, audioBitrate=AUTO, volume=256, audioLatency=MEDIUM, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Krampus , message=Coe @do, language=1, favouriteColour=6, birthdayMonth=12, birthdayDay=6, randomizeMacAddress=false, internalMacAddress=00:09:BF:F6:6B:F2), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FDs%20rom, romUri=content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FDs%20rom/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2FDs%20rom%2F0434%20-%20New%20Super%20Mario%20Bros.%20(U)(Psyfer).nds, sramUri=null)
```

**Comment by rafaelvcaetano** [comment]
Please try the [latest version](https://github.com/rafaelvcaetano/melonDS-android/releases/latest) where this problem should be fixed. Or download it from the [Play Store](https://play.google.com/store/apps/details?id=me.magnum.melonds) to always keep the app up-to-date. If you still encounter errors after updating, please open a new issue.
